Repository tobymao/18xx, pull requests merged in 2020-11, with the labels that each got.

#2239 18MEX: Rename PAC to FCP
  lib/engine/config/game/g_18_mex.rb
  lib/engine/game/g_18_mex.rb
  public/logos/18_mex/FCP.svg
  public/logos/18_mex/PAC.svg
Labels: migration

#2323 18TN: Civil War should affect triggering company (fixes #1873)
  lib/engine/game/g_18_tn.rb
Labels: pins

#2330 Activate players using id
  assets/app/view/game/game_log.rb
  assets/app/view/game_page.rb
  lib/engine/game/base.rb
  migrate_names.rb
  spec/fixtures/1817/13707.json
  spec/fixtures/1817/15528.json
  spec/fixtures/1836_jr30/2809.json
  spec/fixtures/1836_jr30/2851.json
  spec/fixtures/1846/3099.json
  spec/fixtures/1846_2p_variant/hs_pzdxtics_1601680033.json
  spec/fixtures/1882/5236.json
  spec/fixtures/1882/5585.json
  spec/fixtures/1889/314.json
  spec/fixtures/1889/962.json
  spec/fixtures/18_al/1446.json
  spec/fixtures/18_al/4714.json
  spec/fixtures/18_chesapeake/1277.json
  spec/fixtures/18_chesapeake/1905.json
  spec/fixtures/18_chesapeake/2593.json
  spec/fixtures/18_chesapeake/3055.json
  spec/fixtures/18_ga/9222.json
  spec/fixtures/18_los_angeles/hs_srwgrtvq_1602711223.json
  spec/fixtures/18_mex/13315.json
  spec/fixtures/18_ms/14375.json
  spec/fixtures/18_tn/7818.json
  spec/lib/engine/games/game_spec.rb
Labels: migration

#2333 Fix consecutively operating receivership corporations
  lib/engine/round/operating.rb
  spec/fixtures/1846/hs_ymymwsiv_16134.json
  spec/lib/engine/games/game_spec.rb
Labels: pins

#2343 1817 misc bugs
  lib/engine/game/g_1817.rb
  lib/engine/round/g_1817/merger.rb
  lib/engine/step/g_1817/bankrupt.rb
  lib/engine/step/g_1817/buy_sell_par_shares.rb
Labels: pins

#2352 1817: Correct share count being invalid after bankrupcy
  lib/engine/share_pool.rb
  lib/engine/step/g_1817/bankrupt.rb
Labels: pins

#2362 1817 minor fixes
  lib/engine/step/g_1817/acquire.rb
  lib/engine/step/g_1817/bankrupt.rb
  spec/fixtures/1817/15528.json
  spec/lib/engine/games/game_spec.rb
Labels: pins

#2307 Allow using abilities with "when: owning_corp_or_turn" during BuyCompany step
  DEVELOPMENT.md
  assets/app/view/game/buy_trains.rb
  lib/engine/abilities.rb
  lib/engine/config/game/g_1846.rb
  lib/engine/config/game/g_1882.rb
  lib/engine/config/game/g_1889.rb
  lib/engine/config/game/g_18_los_angeles.rb
  lib/engine/corporation.rb
  lib/engine/game/base.rb
  lib/engine/game/g_1817.rb
  lib/engine/game/g_1846.rb
  lib/engine/minor.rb
  lib/engine/phase.rb
  lib/engine/round/base.rb
  lib/engine/step/buy_company.rb
  lib/engine/step/g_1846/buy_company.rb
  lib/engine/step/g_1882/special_nwr.rb
  lib/engine/step/g_1889/special_track.rb
  lib/engine/step/special_buy_train.rb
  lib/engine/step/special_track.rb
  migrate_game.rb
  spec/assets_spec.rb
  spec/fixtures/1846/11181.json
  spec/fixtures/1846/12666.json
  spec/fixtures/1846/hs_cvjhogoy_1599504419.json
  spec/fixtures/1846/hs_gcumggit_1595777670.json
  spec/fixtures/1846/hs_ymymwsiv_16134.json
  spec/fixtures/1846_2p_variant/hs_pzdxtics_1601680033.json
  spec/fixtures/18_ga/9487.json
  spec/fixtures/18_los_angeles/hs_srwgrtvq_1602711223.json
  spec/lib/engine/games/game_spec.rb
  validate.rb
Labels: ability timing, migration

#2373 1817: Acquisitions check on bidding did not include treasury shares (…
  lib/engine/step/g_1817/acquire.rb
  migrate_game.rb
Labels: migration

#2387 1817: 2+ trains should count towards train limit
  assets/app/view/game/stock_market.rb
  assets/app/view/welcome.rb
  lib/engine/game/base.rb
  lib/engine/game/g_1817.rb
  lib/engine/step/discard_train.rb
  lib/engine/step/train.rb
  spec/fixtures/1817/15528.json
Labels: migration, pins

#2321 18TN: Fix "company buy during OR1" bug (fixes #1887)
  lib/engine/config/game/g_18_tn.rb
  lib/engine/game/g_1889.rb
  lib/engine/game/g_18_tn.rb
  lib/engine/step/buy_company.rb
  lib/engine/step/g_1889/special_track.rb
  lib/engine/step/g_18_tn/buy_company.rb
  lib/engine/step/g_18_tn/track.rb
  spec/fixtures/18_tn/7818.json
Labels: 18TN, pins

#2405 waterfall auction: prevent over-committing
  assets/app/view/game/round/auction.rb
  lib/engine/game/base.rb
  lib/engine/game/g_18_chesapeake.rb
  lib/engine/step/auctioner.rb
  lib/engine/step/waterfall_auction.rb
Labels: pins

#2406 1817 Fixes
  lib/engine/config/game/g_1817.rb
  lib/engine/step/g_1817/acquire.rb
  lib/engine/step/g_1817/cash_crisis.rb
  lib/engine/step/g_1817/post_conversion.rb
  migrate_game.rb
  spec/fixtures/1817/13707.json
  spec/fixtures/1817/15528.json
Labels: migration, pins

#2417 recalculate_order was not being called in 1817 some times
  lib/engine/round/operating.rb
  lib/engine/step/emergency_money.rb
  lib/engine/step/g_1817/bankrupt.rb
  lib/engine/step/train.rb
Labels: pins
