Repository tobymao/18xx, pull requests merged in 2020-12, with the labels that each got.

#2529 Bug fix: make abilities of 18LA optional companies only activate if explicitly chosen
  lib/engine/ability/README.md
  lib/engine/ability/token.rb
  lib/engine/config/game/g_18_los_angeles.rb
  lib/engine/step/g_18_ga/token.rb
  lib/engine/step/g_18_ms/token.rb
  lib/engine/step/tokener.rb
Labels: migration, pins

#2588 1817 Bug Fixes, and make production
  assets/app/view/game/round/stock.rb
  assets/app/view/welcome.rb
  lib/engine/game/g_1817.rb
  lib/engine/step/g_1817/acquire.rb
  lib/engine/step/g_1817/buy_sell_par_shares.rb
  lib/engine/step/g_1817/post_conversion.rb
  migrate_game.rb
  spec/fixtures/1817/15528.json
  spec/fixtures/1817_na/17386.json
Labels: migration, pins

#2580 Bug fix, 1846: add potential cash from minor to entity's buying power
  lib/engine/game/g_1846.rb
  lib/engine/step/g_1846/buy_train.rb
  lib/engine/step/g_1846/track_and_token.rb
  spec/assets_spec.rb
  spec/fixtures/1846/11181.json
  spec/fixtures/1846/3099.json
Labels: migration

#2624 18MEX: Closed corporation caused exception (fixes #2623)
  lib/engine/round/operating.rb
Labels: 18MEX

#2636 1817 Bugs:
  lib/engine/round/g_1817/stock.rb
  lib/engine/step/g_1817/acquire.rb
  lib/engine/step/g_1817/reduce_tokens.rb
  migrate_game.rb
Labels: migration, pins

#2666 Allow mergers in 1817 that end in the president holding 20%
  lib/engine/step/g_1817/conversion.rb
Labels: migration, pins

#2667 [1817, 1817WO] Ohio Bridge Company should only be usable once
  lib/engine/config/game/g_1817.rb
  lib/engine/config/game/g_1817_na.rb
  lib/engine/config/game/g_1817_wo.rb
Labels: pins

#2693 Fix immortal 2+ trains in 1817WO
  lib/engine/config/game/g_1817_wo.rb
Labels: pins

#2725 18CO - Transferred trains should reset
  lib/engine/step/g_18_co/takeover.rb
Labels: 18CO

#2720 18CO - Fix when the DSNG closes
  lib/engine/config/game/g_18_co.rb
  lib/engine/step/g_18_co/dividend.rb
Labels: 18CO

#2719 1860 home tile placement and priority deal fixes
  lib/engine/game/g_1860.rb
  lib/engine/step/g_1860/buy_sell_par_shares.rb
  lib/engine/step/g_1860/exchange.rb
  lib/engine/step/g_1860/home_track.rb
Labels: 1860

#2717 Corporate Share Fixes
  assets/app/view/game/corporate_buy_shares.rb
  lib/engine/step/corporate_buy_shares.rb
  lib/engine/step/corporate_sell_shares.rb
Labels: 18CO

#2705 Terrain costs for 1849
  lib/engine/config/game/g_1849.rb
  lib/engine/game/g_1849.rb
  lib/engine/part/path.rb
  lib/engine/step/g_1849/track.rb
  lib/engine/tile.rb
Labels: 1849

#2740 Allow for generic tile cost discount and use in 18CO
  lib/engine/ability/README.md
  lib/engine/ability/tile_discount.rb
  lib/engine/config/game/g_18_co.rb
  lib/engine/game/base.rb
  lib/engine/step/tracker.rb
Labels: 18CO

#2735 1860 Fix for #2734
  lib/engine/step/g_1860/home_track.rb
  lib/engine/step/g_1860/tracker.rb
Labels: 1860

#2739 Bug fix: fix cert limits after a corp closes in 1846 2p and 18 Los Angeles
  lib/engine/config/game/g_18_los_angeles.rb
  lib/engine/game/g_1846_two_player_variant.rb
Labels: 18 Los Angeles, 1846, pins

#2728 Token fees, extra shares, at float
  lib/engine/config/game/g_1849.rb
  lib/engine/g_1849/corporation.rb
  lib/engine/game/g_1849.rb
  lib/engine/step/g_1849/buy_sell_par_shares.rb
Labels: 1849

#2731 Fix all_bundles_for_corporation sorting when same % share exists
  lib/engine/game/base.rb
Labels: 18CO

#2732 18CO - Fix detection of city having max stations
  lib/engine/game/g_18_co.rb
Labels: 18CO

#2690 1870: share redemption and reissue
  assets/app/view/game/corporation.rb
  assets/app/view/game/issue_shares.rb
  assets/app/view/game/round/stock.rb
  lib/engine/g_1870/stock_market.rb
  lib/engine/game/g_1870.rb
  lib/engine/share_pool.rb
  lib/engine/step/g_1870/buy_sell_par_shares.rb
  lib/engine/step/g_1870/price_protection.rb
Labels: 1870

#2698 1856 variable cap
  assets/app/view/game/corporation.rb
  lib/engine/corporation.rb
  lib/engine/g_1856/corporation.rb
  lib/engine/g_1856/share_pool.rb
  lib/engine/game/g_1856.rb
  lib/engine/round/g_1856/operating.rb
  lib/engine/step/g_1856/buy_sell_par_shares.rb
Labels: 1856

#2757 1860 add first two options, fix map UI to allow missing row/column
  assets/app/view/game/axis.rb
  assets/app/view/game/hex.rb
  assets/app/view/game/map.rb
  lib/engine/config/game/g_1860.rb
  lib/engine/game/base.rb
  lib/engine/game/g_1860.rb
  lib/engine/step/g_1860/route.rb
Labels: 1860

#2759 Game based allow/disallow cross corp abilities
  assets/app/view/game/abilities.rb
  lib/engine/game/base.rb
  lib/engine/game/g_18_co.rb
Labels: 18CO

#2704 Hex trains for 1849
  lib/engine/config/game/g_1849.rb
  lib/engine/game/g_1849.rb
  lib/engine/part/path.rb
Labels: 1849

#2758 Allow for Phase Jumping
  assets/app/view/game/game_info.rb
  lib/engine/config/game/g_18_co.rb
  lib/engine/phase.rb
Labels: 18CO

#2771 1817WO can actually end now
  lib/engine/config/game/g_1817_wo.rb
Labels: 1817WO

#2766 Allow for increased control over who can use a company
  assets/app/view/game/abilities.rb
  lib/engine/game/base.rb
  lib/engine/game/g_18_co.rb
Labels: 18CO

#2769 1849 share price behavior
  lib/engine/config/game/g_1849.rb
  lib/engine/g_1849/stock_market.rb
  lib/engine/game/g_1849.rb
  lib/engine/step/g_1849/dividend.rb
Labels: 1849

#2768 1817 bugs
  assets/app/view/game/corporation.rb
  lib/engine/game/base.rb
  lib/engine/game/g_1817.rb
  lib/engine/game/g_1867.rb
  lib/engine/step/g_1817/acquire.rb
  lib/engine/step/g_1817/buy_sell_par_shares.rb
  lib/engine/step/g_1867/automatic_loan.rb
  lib/engine/step/g_1867/buy_train.rb
  migrate_game.rb
  spec/assets_spec.rb
  spec/fixtures/1817/13707.json
  spec/fixtures/1817/16281.json
  spec/fixtures/1817/16852.json
  spec/lib/engine/games/game_spec.rb
Labels: migration, pins

#2794 1860: fix for logging leased trains
  lib/engine/step/g_1860/route.rb
Labels: 1860

#2798 1860 spec test case
  spec/assets_spec.rb
  spec/fixtures/1860/19_354.json
  spec/lib/engine/games/game_spec.rb
Labels: 1860

#2833 skip implicit use of tile-laying abilities
  lib/engine/step/tracker.rb
Labels: pins

#2839 Minor tile_lay ability tweaks
  lib/engine/ability/README.md
  lib/engine/ability/tile_lay.rb
  lib/engine/config/game/g_1828.rb
  lib/engine/config/game/g_1846.rb
  lib/engine/config/game/g_1889.rb
  lib/engine/config/game/g_18_chesapeake.rb
  lib/engine/config/game/g_18_los_angeles.rb
  lib/engine/config/game/g_18_ms.rb
  lib/engine/step/special_track.rb
Labels: pins

#2847 1860 show layer and par prices on corp cards
  assets/app/view/game/corporation.rb
  lib/engine/game/g_1860.rb
Labels: 1860

#2843 Properly remove reservations when a token is placed, fix cert limit in 1846 games
  lib/engine/game/base.rb
  lib/engine/game/g_1846.rb
  lib/engine/part/city.rb
  spec/fixtures/1846/19962.json
  spec/fixtures/1846_2p_variant/11098.json
  spec/game_state_spec.rb
  spec/lib/engine/games/game_spec.rb
Labels: pins

#2898 1867 bug sweep
  lib/engine/config/game/g_1867.rb
  lib/engine/game/g_1867.rb
  lib/engine/step/g_1867/buy_sell_par_shares.rb
  lib/engine/step/g_1867/merge.rb
Labels: pins

#2902 1867 Bug Fixes part 2
  lib/engine/config/game/g_1867.rb
  lib/engine/game/g_1867.rb
  lib/engine/step/g_1867/merge.rb
  lib/engine/step/g_1867/post_merger_shares.rb
Labels: pins

#2870 only allow actions from the relevant company during a blocking SpecialTrack step
  lib/engine/game/base.rb
  lib/engine/game/g_1817.rb
  lib/engine/game/g_1817_wo.rb
  lib/engine/game/g_1828.rb
  lib/engine/game/g_1836_jr30.rb
  lib/engine/game/g_1846.rb
  lib/engine/game/g_1848.rb
  lib/engine/game/g_1849.rb
  lib/engine/game/g_1856.rb
  lib/engine/game/g_1860.rb
  lib/engine/game/g_1867.rb
  lib/engine/game/g_1870.rb
  lib/engine/game/g_1882.rb
  lib/engine/game/g_1889.rb
  lib/engine/game/g_18_al.rb
  lib/engine/game/g_18_chesapeake.rb
  lib/engine/game/g_18_co.rb
  lib/engine/game/g_18_ga.rb
  lib/engine/game/g_18_los_angeles.rb
  lib/engine/game/g_18_mex.rb
  lib/engine/game/g_18_ms.rb
  lib/engine/game/g_18_tn.rb
  lib/engine/step/special_track.rb
Labels: ability timing, migration
