Repository tobymao/18xx, pull requests merged in 2021-03, with the labels that each got.

#4221 [18CZ] remove unused yellow value from large offboards
  lib/engine/game/g_18_cz/game.rb
Labels: archive_alpha_games

#4225 [1822] English channel
  lib/engine/game/g_1822/game.rb
  lib/engine/game/g_1822/step/minor_acquisition.rb
Labels: archive_alpha_games

#4227 [1822] Cert limit and corporation reorder
  lib/engine/game/g_1822/game.rb
  lib/engine/game/g_1822/round/operating.rb
  lib/engine/game/g_1822/step/buy_sell_par_shares.rb
Labels: archive_alpha_games

#4228 fixes typo in 1830 market
  lib/engine/game/g_1830/game.rb
Labels: pins

#4232 Clear routes after earthquake (#4230)
  lib/engine/game/g_1849/game.rb
Labels: pins

#4234 [18CZ] Added validation for buying a corporation
  lib/engine/game/g_18_cz/step/buy_corporation.rb
Labels: archive_alpha_games

#4191 updates to fix ability timing issues
  assets/app/view/game/abilities.rb
  lib/engine/ability/README.md
  lib/engine/ability/teleport.rb
  lib/engine/game/base.rb
  lib/engine/game/g_1817/game.rb
  lib/engine/game/g_1817_na/game.rb
  lib/engine/game/g_1817_wo/game.rb
  lib/engine/game/g_1828/game.rb
  lib/engine/game/g_1836_jr30/game.rb
  lib/engine/game/g_1846/step/assign.rb
  lib/engine/game/g_1882/game.rb
  lib/engine/game/g_1882/step/special_nwr.rb
  lib/engine/game/g_1889/game.rb
  lib/engine/game/g_18_al/game.rb
  lib/engine/game/g_18_mex/game.rb
  lib/engine/game/g_18_ms/game.rb
  lib/engine/round/base.rb
  lib/engine/round/operating.rb
  lib/engine/step/buy_company.rb
  lib/engine/step/special_track.rb
  lib/engine/step/tracker.rb
  spec/assets_spec.rb
  spec/fixtures/1828.Games/23366.json
  spec/fixtures/1836Jr30/2809.json
  spec/fixtures/18AL/1446.json
  spec/fixtures/18AL/4714.json
  spec/fixtures/18CO/22032.json
  spec/fixtures/18CZ/29247.json
  spec/fixtures/18CZ/hs_gwurdqhs_1613616655.json
  spec/fixtures/18Chesapeake/1277.json
  spec/fixtures/18Chesapeake/1905.json
  spec/fixtures/18Chesapeake/2593.json
  spec/fixtures/18Chesapeake/3055.json
  spec/fixtures/18GA/9222.json
  spec/fixtures/18GA/9487.json
  spec/fixtures/18MEX/17849.json
  spec/fixtures/18SJ/19.json
  spec/fixtures/18TN/7818.json
  spec/game_state_spec.rb
Labels: migration, pins

#4253 [1822] Corporation reorder
  assets/app/view/game/buy_trains.rb
  lib/engine/game/g_1822/round/operating.rb
Labels: archive_alpha_games

#4251 [1822] Timing was wrong on M&GNR
  assets/app/view/game/round/choices.rb
  assets/app/view/game_page.rb
  lib/engine/game/g_1822/game.rb
  lib/engine/game/g_1822/round/choices.rb
  lib/engine/game/g_1822/step/choose.rb
  lib/engine/round/choices.rb
Labels: archive_alpha_games

#4245 Fixes #4189
  lib/engine/game/g_1817_wo/game.rb
  lib/engine/game/g_1817_wo/step/buy_sell_par_shares.rb
  lib/engine/game/g_1817_wo/step/home_token.rb
Labels: pins

#4259 [18CO] removes villages from hexes array for GJGR company #4208
  lib/engine/game/g_18_co/game.rb
  lib/engine/game/g_18_co/step/special_track.rb
Labels: pins

#4296 [1822] Strange behaviour in stock round
  lib/engine/game/g_1822/step/buy_sell_par_shares.rb
Labels: archive_alpha_games

#4298 [1822] Show P18 on trackstep
  lib/engine/game/g_1822/game.rb
  lib/engine/game/g_1822/step/track.rb
Labels: archive_alpha_games

#4330 1861/67: Fix share price movement down rather than left
  lib/engine/game/base.rb
  lib/engine/game/g_1867/game.rb
Labels: pins

#4338 [1822] Wrong number of 5 trains
  lib/engine/game/g_1822/game.rb
Labels: archive_alpha_games

#4366 Only look at positive shares for short squeeze check [#4363]
  lib/engine/game/g_1817/round/stock.rb
Labels: pins

#4384 OO tile layer decides token placement
  lib/engine/game/g_1828/game.rb
  lib/engine/game/g_1828/step/track.rb
  lib/engine/step/tracker.rb
Labels: pins

#4388 1849K2S change names of corporations to historical ones (pin everyone 😕)
  lib/engine/game/g_1849_boot/game.rb
  lib/engine/game/g_1849_boot/step/token.rb
  public/logos/1849_boot/AL.svg
  public/logos/1849_boot/BTR.svg
  public/logos/1849_boot/FCU.svg
  public/logos/1849_boot/IFP.svg
  public/logos/1849_boot/MC.svg
  public/logos/1849_boot/PL.svg
  public/logos/1849_boot/SFCS.svg
  public/logos/1849_boot/SFM.svg
  public/logos/1849_boot/SFR.svg
  public/logos/1849_boot/TSR.svg
Labels: pins

#4415 1861: RSR if trainless must buy cheapest, otherwise must buy from depot.
  lib/engine/game/g_1861/meta.rb
  lib/engine/game/g_1861/step/buy_train.rb
Labels: pins

#4495 [1822] 14 not restricted to London
  lib/engine/game/g_1822/step/pending_token.rb
Labels: archive_alpha_games

#4505 [1846, bug fix] fix closing corporations during bankruptcy
  lib/engine/game/g_1846/step/bankrupt.rb
  lib/engine/step/message.rb
  spec/fixtures/1846/16904.json
Labels: pins

#4509 [1846, bug fix] prevent illegal bankruptcy--fix total_emr_buying_power calculation
  assets/app/view/game/buy_trains.rb
  lib/engine/game/g_1846/game.rb
  lib/engine/game/g_1846/step/bankrupt.rb
  spec/fixtures/1846/20381.json
  spec/game_state_spec.rb
Labels: pins

#4510 [1822] Phase 6 floated companies
  lib/engine/game/g_1822/game.rb
  lib/engine/game/g_1822/step/dividend.rb
Labels: archive_alpha_games

#4511 [1822] Player debts
  lib/engine/game/g_1822/game.rb
  lib/engine/game/g_1822/step/dividend.rb
Labels: archive_alpha_games

#4518 1860: prohibit bankrupt company from buying train; allow repar with …
  lib/engine/corporation.rb
  lib/engine/game/g_1860/game.rb
  lib/engine/game/g_1860/step/buy_train.rb
Labels: pins

#4520 [1846] bankruptcy - don't drop prices when selling normally unsellable shares
  lib/engine/game/g_1846/step/bankrupt.rb
  spec/fixtures/1846/11181.json
  spec/fixtures/1846/16904.json
  spec/fixtures/1846/hs_gcumggit_1595777670.json
  spec/fixtures/1846/hs_ymymwsiv_16134.json
Labels: pins

#4500 1882: Fix NWR private and OO tile if it already has a token on it
  lib/engine/step/tracker.rb
Labels: pins

#4521 [1817, 1846, many others] during bankruptcy, sell remaining shares based on operating order
  lib/engine/corporation.rb
  lib/engine/game/g_1817/step/bankrupt.rb
  lib/engine/game/g_1846/step/bankrupt.rb
  lib/engine/game/g_1849/step/bankrupt.rb
  lib/engine/game/g_1856/step/bankrupt.rb
  lib/engine/share_holder.rb
  lib/engine/step/bankrupt.rb
  spec/assets_spec.rb
  spec/fixtures/1817NA/25351.json
  spec/fixtures/1817NA/27066.json
Labels: pins

#4555 1870: Fort Worth should be a P City (closes #4550)
  lib/engine/game/g_1870/game.rb
Labels: archive_alpha_games

#4557 1870: Using river tile discount shouldn't close the private (#4554)
  lib/engine/game/g_1870/step/special_track.rb
  spec/fixtures/1870/hs_ufqpdrvi_1615279805.json
Labels: archive_alpha_games

#4558 1870: Connection dividend wasn't pay for corp shares (fixes #4549)
  lib/engine/game/g_1870/step/connection_dividend.rb
  spec/fixtures/1870/hs_ufqpdrvi_1615279805.json
Labels: archive_alpha_games

#4560 1870: Fix partition "outer" restrict (fixes #4539)
  lib/engine/part/partition.rb
Labels: archive_alpha_games

#4586 [1822] Train removed when bid on last minor
  lib/engine/game/g_1822/round/stock.rb
Labels: archive_alpha_games

#4651 [1822] Destination token
  lib/engine/game/g_1822/game.rb
Labels: pins

#4624 1870: Fixed error on migration (fixes #4600 again)
  lib/engine/game/g_1870/game.rb
  spec/fixtures/1870/README.md
  spec/fixtures/1870/hs_ufqpdrvi_1615279805.json
Labels: archive_alpha_games

#4696 [1822] Purchase of redeemed treasury share in phase 6+
  lib/engine/game/g_1822/game.rb
Labels: archive_alpha_games

#4699 [1822NRS] London to London
  lib/engine/game/g_1822_nrs/game.rb
Labels: archive_alpha_games

#4701 1870: Improve/simplify upgrade of P Hexes
  lib/engine/game/g_1870/step/track.rb
Labels: archive_alpha_games

#4709 [18 Los Angeles] bug fix - LA Title's neutral token
  lib/engine/step/tokener.rb
  spec/fixtures/18 Los Angeles/30265.json
  spec/game_state_spec.rb
Labels: pins

#4760 1828: C&P should pay 15 revenue once purchased by a corporation. #4727
  lib/engine/game/g_1828/game.rb
  lib/engine/game/g_1828/step/buy_company.rb
  spec/fixtures/1828.Games/23366.json
Labels: pins

#4791 1873: check buy_train prices; adjust map for upgrades
  lib/engine/game/g_1873/game.rb
  lib/engine/game/g_1873/step/buy_train.rb
Labels: archive_alpha_games

#4784 Fix bull token private in 18FL not counting as normal token for token…
  lib/engine/game/g_18_fl/step/special_token.rb
Labels: archive_alpha_games

#4794 18FL: Only one hotel per hex
  lib/engine/game/g_18_fl/step/token.rb
Labels: archive_alpha_games

#4774 1870: Fix pd after price protection
  lib/engine/game/g_1870/step/price_protection.rb
Labels: archive_alpha_games

#4792 1817: Skips incorrectly if auction is automatically resolved
  lib/engine/game/g_1817/step/selection_auction.rb
Labels: pins
