Repository tobymao/18xx, pull requests merged in 2021-02, with the labels that each got.

#3628 1867: Previous corp nationalizes causes skip of train buy
  lib/engine/step/g_1867/buy_train.rb
Labels: pins

#3656 1867: Enforce the one token per hex rule after a merger
  lib/engine/step/g_1867/merge.rb
  lib/engine/step/g_1867/reduce_tokens.rb
  lib/engine/step/token_merger.rb
Labels: pins

#3659 18Mag: Auto-lay token on yellow OO tiles
  lib/engine/game/g_18_mag.rb
  lib/engine/step/g_18_mag/track.rb
  lib/engine/step/tracker.rb
Labels: pins

#3672 1861 bugs:
  lib/engine/config/game/g_1861.rb
  lib/engine/game/g_1867.rb
  public/logos/1861/RSR.svg
  scripts/generate_logos.rb
Labels: delete_alpha_games

#3693 1861 bug fixes:
  lib/engine/game/g_1861.rb
  lib/engine/game/g_1867.rb
Labels: delete_alpha_games

#3694 1860: relocate bankruptcy check
  lib/engine/game/g_1860.rb
  lib/engine/step/g_1860/dividend.rb
Labels: pins

#3727 18Mag: Rule tweaks from Lonny
  assets/app/view/game/stock_market.rb
  lib/engine/game/g_18_mag.rb
  lib/engine/step/g_18_mag/dividend.rb
  lib/engine/step/g_18_mag/route.rb
Labels: pins

#3734 18CO Fixes ( EBuy Cross-purchase, 2P removed on Discard, Share Sell Operating Order, GJGR Timing )
  DEVELOPMENT.md
  lib/engine/config/game/g_18_co.rb
  lib/engine/game/g_18_co.rb
  lib/engine/step/corporate_sell_shares.rb
  lib/engine/step/g_18_co/buy_train.rb
  lib/engine/step/g_18_co/discard_train.rb
  migrate_game.rb
  spec/assets_spec.rb
  spec/fixtures/18CO/22032.json
Labels: 18CO, migration, pins

#3774 1828 Simple logos, flag for non-buyable IPO shares, and remove cert limit from spreadsheet if no cert limit
  assets/app/view/game/corporation.rb
  assets/app/view/game/spreadsheet.rb
  lib/engine/config/game/g_1828.rb
  public/logos/1828/BM.alt.svg
  public/logos/1828/BO.alt.svg
  public/logos/1828/CO.alt.svg
  public/logos/1828/CP.alt.svg
  public/logos/1828/CPR.alt.svg
  public/logos/1828/ERIE.alt.svg
  public/logos/1828/GT.alt.svg
  public/logos/1828/IC.alt.svg
  public/logos/1828/MC.alt.svg
  public/logos/1828/MP.alt.svg
  public/logos/1828/NKP.alt.svg
  public/logos/1828/NW.alt.svg
  public/logos/1828/NYC.alt.svg
  public/logos/1828/NYH.alt.svg
  public/logos/1828/OSH.alt.svg
  public/logos/1828/PRR.alt.svg
  public/logos/1828/WAB.alt.svg
Labels: pins

#3814 1860: fix sell in blocks; fix insolvent tile laying
  lib/engine/game/g_1860.rb
  lib/engine/step/g_1860/buy_sell_par_shares.rb
  lib/engine/step/g_1860/tracker.rb
Labels: pins

#3816 1861: Trains don't upgrade
  lib/engine/config/game/g_1861.rb
  spec/fixtures/1861/26037.json
  spec/fixtures/1861/26650.json
Labels: delete_alpha_games, migration

#3862 1861 bug fixes
  lib/engine/config/game/g_1861.rb
  lib/engine/step/g_1861/buy_train.rb
  lib/engine/step/g_1867/merge.rb
  public/logos/1861/GRR.svg
  public/logos/1861/MKV.svg
  spec/fixtures/1861/26650.json
Labels: pins

#3908 1817/1817NA/1817WO/1877: Remove need to purchase tokens manually
  assets/app/view/game/round/stock.rb
  lib/engine/action/buy_tokens.rb
  lib/engine/step/g_1817/buy_sell_par_shares.rb
  lib/engine/step/g_1817_wo/buy_sell_par_shares.rb
  lib/engine/step/g_1877/buy_sell_par_shares.rb
  migrate_game.rb
  spec/assets_spec.rb
  spec/fixtures/1817/15528.json
  spec/fixtures/1817/16281.json
  spec/fixtures/1817NA/20584.json
  spec/fixtures/1817WO/19926.json
  spec/fixtures/1877/26036.json
  spec/fixtures/1877/26232.json
Labels: migration, pins

#4027 18CZ Fixed Dividend rounding
  lib/engine/game/g_18_cz.rb
  lib/engine/step/g_18_cz/dividend.rb
Labels: delete_alpha_games

#4103 18MEX remove P2's ability if Copper Canyon is laid [Fixes #2855]
  lib/engine/game/g_18_mex/game.rb
  lib/engine/game/g_18_mex/step/special_track.rb
Labels: migration, pins

#4139 [18CZ] only one #2
  lib/engine/config/game/g_18_cz.rb
Labels: pins

#4142 1828: Additional stock price movements only apply to sold out corporations [fixes #4140]
  lib/engine/game/g_1828/round/stock.rb
  spec/fixtures/1828/23459.json
  spec/lib/engine/round/stock_spec.rb
Labels: pins

#4165 1849 bug fixes
  lib/engine/game/g_1849/game.rb
  lib/engine/game/g_1849/step/buy_train.rb
Labels: pins

#4135 [18CZ] autopass draft if player doesn't have cash for any privates
  lib/engine/game/g_18_cz/step/draft.rb
Labels: pins
