Repository tobymao/18xx, pull requests merged in 2021-04, with the labels that each got.

#4919 1873: fix machine scrapping for indie mines
  lib/engine/game/g_1873/step/buy_train.rb
Labels: pins

#4847 [18CZ] Fixed float track lay and ability
  lib/engine/game/g_18_cz/game.rb
  lib/engine/game/g_18_cz/step/sell_company_and_special_track.rb
Labels: archive_alpha_games

#4914 Remove hotels in Key West Hurricane (18FL)
  lib/engine/game/g_18_fl/game.rb
Labels: archive_alpha_games

#4872 [1828.Games] Fix odd share player choice
  lib/engine/game/g_1828/step/merger.rb
Labels: pins

#4890 [1846] remove steamboat markers if not bought in by brown
  lib/engine/game/g_1846/game.rb
Labels: pins

#4932 [18LA, 18MEX] token abilities: fix 'from_owner', rename 'extra' -> 'extra_action'
  lib/engine/ability/README.md
  lib/engine/ability/token.rb
  lib/engine/game/g_1822/entities.rb
  lib/engine/game/g_1822/step/pending_token.rb
  lib/engine/game/g_1828/step/token.rb
  lib/engine/game/g_1846/entities.rb
  lib/engine/game/g_1849/step/token.rb
  lib/engine/game/g_1882/game.rb
  lib/engine/game/g_1882/step/special_nwr.rb
  lib/engine/game/g_18_al/step/token.rb
  lib/engine/game/g_18_cz/step/home_track.rb
  lib/engine/game/g_18_fl/game.rb
  lib/engine/game/g_18_fl/step/special_token.rb
  lib/engine/game/g_18_los_angeles/entities.rb
  lib/engine/game/g_18_ms/step/token.rb
  lib/engine/step/home_token.rb
  lib/engine/step/special_token.rb
  lib/engine/step/tokener.rb
  spec/fixtures/18 Los Angeles/19984.json
  spec/fixtures/18 Los Angeles/30265.json
  spec/game_state_spec.rb
Labels: pins

#4961 [1846] don't skip MC/O&I second tile lay on Message
  lib/engine/game/g_1846/game.rb
Labels: pins

#4989 [1822] Discard Train
  lib/engine/game/g_1822/game.rb
  lib/engine/game/g_1822/step/discard_train.rb
  lib/engine/game/g_1822_mrs/game.rb
  lib/engine/game/g_1822_nrs/game.rb
Labels: archive_alpha_games

#4981 1873: player order w/ties; x-corp diesels; price drop in insolvency
  lib/engine/game/g_1873/game.rb
  lib/engine/game/g_1873/step/buy_train.rb
Labels: archive_alpha_games

#4977 Generalises multiple buy from market only. Add it to 1870.
  lib/engine/game/base.rb
  lib/engine/game/g_1830/game.rb
  lib/engine/game/g_1830/step/buy_sell_par_shares.rb
  lib/engine/game/g_1870/game.rb
  lib/engine/step/buy_sell_par_shares.rb
Labels: archive_alpha_games, pins

#5001 1873: prohibit all illegal compulsory train buys
  lib/engine/game/g_1873/step/buy_train.rb
Labels: archive_alpha_games

#5026 [1822] Multiple E-Trains
  lib/engine/game/g_1822/step/buy_train.rb
Labels: archive_alpha_games

#5036 [1822] Certificate limit not enforced
  lib/engine/game/g_1822/game.rb
  lib/engine/game/g_1822/step/buy_sell_par_shares.rb
Labels: archive_alpha_games

#5023 18FL Stock market enforces 5 share price cap
  lib/engine/game/g_18_fl/game.rb
  lib/engine/game/g_18_fl/step/dividend.rb
  lib/engine/game/g_18_fl/stock_market.rb
Labels: archive_alpha_games

#5050 Fixes 5049
  lib/engine/game/g_18_fl/step/dividend.rb
Labels: archive_alpha_games

#5021 1849K2S balance changes
  lib/engine/game/g_1849_boot/game.rb
  spec/fixtures/1849 Two Sicilies/hs_yoynlhyo_32488.json
Labels: pins

#5083 1817DE - Balance update
  lib/engine/game/g_1817_de/entities.rb
  lib/engine/game/g_1817_de/game.rb
  lib/engine/game/g_1817_de/map.rb
Labels: pins

#5081 1822: fix tile numbers, add slot for gray S
  lib/engine/game/g_1822/entities.rb
  lib/engine/game/g_1822/game.rb
  lib/engine/game/g_1822/map.rb
  lib/engine/game/g_1822_mrs/game.rb
  lib/engine/game/g_1822_nrs/game.rb
  spec/fixtures/1822/33845.json
Labels: pins

#5098 1817: Add ability for base special track to consume a lay
  lib/engine/ability/README.md
  lib/engine/ability/tile_lay.rb
  lib/engine/game/g_1817/game.rb
  lib/engine/game/g_1817/step/special_track.rb
  lib/engine/game/g_1817_de/entities.rb
  lib/engine/game/g_1817_na/game.rb
  lib/engine/game/g_1817_wo/game.rb
  lib/engine/step/special_track.rb
  lib/engine/step/tracker.rb
Labels: pins

#5085 [18MS] Fix Birmingham Southern Railroad's ability timing
  lib/engine/abilities.rb
  lib/engine/ability/README.md
  lib/engine/ability/base.rb
  lib/engine/game/g_18_ms/entities.rb
  lib/engine/game/g_18_ms/game.rb
  lib/engine/game/g_18_ms/map.rb
Labels: pins

#5086 [1870] fix can_sell? to check for cert limit before corp % limit
  lib/engine/game/base.rb
  lib/engine/game/g_1828/game.rb
  lib/engine/game/g_1870/game.rb
  lib/engine/step/buy_sell_par_shares.rb
Labels: archive_alpha_games

#5113 1817WO: Shouldn't be able to redeem shares in liquidation
  lib/engine/game/g_1817_wo/game.rb
Labels: pins

#5114 1830: Tile reservations on Erie should block others placing token
  lib/engine/game/g_1830/game.rb
Labels: pins

#5104 1873: move price correctly after insolvency grant
  lib/engine/game/g_1873/game.rb
Labels: archive_alpha_games

#5165 [18CZ] Optimized token reservation for ATE
  lib/engine/game/g_18_cz/game.rb
  lib/engine/game/g_18_cz/step/buy_corporation.rb
  lib/engine/game/g_18_cz/step/token.rb
  spec/fixtures/18CZ/hs_gwurdqhs_1613616655.json
Labels: pins
