Repository tobymao/18xx, pull requests merged in 2021-08, with the labels that each got.

#6165 Fix 5905 - 18CO EMR Bundles
  lib/engine/game/g_18_co/game.rb
Labels: 18CO, pins

#6205 18Carolinas: modify phases, add "voting" for final track
  lib/engine/game/g_18_carolinas/game.rb
  lib/engine/game/g_18_carolinas/map.rb
  lib/engine/game/g_18_carolinas/step/convert_track.rb
  lib/engine/game/g_18_carolinas/step/track.rb
Labels: archive_alpha_games

#6211 18Carolinas: change both northern and southern track to use $20 dits
  lib/engine/game/base.rb
  lib/engine/game/g_18_carolinas/game.rb
  lib/engine/game/g_18_carolinas/map.rb
Labels: 18Carolinas, archive_alpha_games

#6221 18Carolinas: more rule changes
  lib/engine/game/g_18_carolinas/game.rb
  lib/engine/game/g_18_carolinas/map.rb
  lib/engine/game/g_18_carolinas/step/buy_power.rb
  lib/engine/game/g_18_carolinas/step/track.rb
Labels: 18Carolinas, archive_alpha_games

#6232 [1893] Improve player order after drafting (fixes #6204)
  lib/engine/game/g_1893/game.rb
  lib/engine/game/g_1893/step/buy_minor.rb
  lib/engine/game/g_1893/step/starting_package_forced_auction.rb
  lib/engine/game/g_1893/step/starting_package_initial_auction.rb
  spec/fixtures/1893/46448.json
Labels: pins, 1893

#6228 18Texas: Add new auction type: SimultaneousAuction
  lib/engine/game/g_18_texas/entities.rb
  lib/engine/game/g_18_texas/game.rb
  lib/engine/game/g_18_texas/map.rb
  lib/engine/game/g_18_texas/step/simultaneous_auction.rb
Labels: archive_alpha_games, 18Texas

#6245 1862: Fix freight revenue calc; LNER cert limit bug
  lib/engine/game/g_1862/game.rb
  lib/engine/game/g_1862/step/buy_sell_par_shares.rb
Labels: pins

#6268 18EU - Allow choice of keeping token during exchange
  lib/engine/game/g_18_eu/game.rb
  lib/engine/game/g_18_eu/step/buy_sell_par_shares.rb
  lib/engine/game/g_18_eu/step/merge.rb
  lib/engine/game/g_18_eu/step/minor_exchange.rb
  lib/engine/game/g_18_eu/step/replace_token.rb
Labels: 18EU

#6270 18EU Mountain Upgrade
  lib/engine/game/g_18_eu/game.rb
  lib/engine/game/g_18_eu/step/track.rb
Labels: 18EU

#6293 1860: fix train discard step
  lib/engine/game/g_1860/game.rb
  lib/engine/game/g_1860/round/operating.rb
  lib/engine/game/g_1860/step/discard_train.rb
Labels: pins
