Repository tobymao/18xx, pull requests merged in 2021-06, with the labels that each got.

#5581 18ZOO: remove the M / MM labels when a tile is put back into tile list
  lib/engine/game/g_18_zoo/step/tracker.rb
Labels: archive_alpha_games

#5596 1856: Fix CGR losing tokens in the case of duplicate tokens in city (toronto, OO)
  lib/engine/game/g_1856/game.rb
Labels: archive_alpha_games

#5601 [1840] Adds error when multiple trains were assigned
  lib/engine/game/g_1840/step/reassign_trains.rb
Labels: archive_alpha_games

#5607 [1840] Fixed Laying of orange framed tiles + fixed dividend
  lib/engine/game/g_1840/game.rb
  lib/engine/game/g_1840/map.rb
  lib/engine/game/g_1840/step/acquisition_auction.rb
  lib/engine/game/g_1840/step/buy_train.rb
  lib/engine/game/g_1840/step/dividend.rb
  lib/engine/game/g_1840/step/special_track.rb
  lib/engine/game/g_1840/step/track_and_token.rb
  lib/engine/step/dividend.rb
Labels: archive_alpha_games

#5633 18ZOO: change grey tile to three different tiles with own icon
  lib/engine/game/g_18_zoo/game.rb
  lib/engine/game/g_18_zoo/map.rb
  public/icons/18_zoo/BB.svg
  public/icons/18_zoo/GI.svg
  public/icons/18_zoo/TI.svg
  spec/fixtures/18ZOO/or_power.rabbits.home_to_gray.json
  spec/fixtures/18ZOO/or_power.rabbits.home_to_gray_li.json
  spec/lib/engine/games/g_18_zoo_spec.rb
Labels: archive_alpha_games

#5638 1856: Waterloo cannot be used outside of a corporation's OR now
  lib/engine/game/g_1856/game.rb
Labels: archive_alpha_games

#5641 1830jr30 fix stock market
  lib/engine/game/g_1836_jr30/game.rb
Labels: pins

#5646 18ZOO: home track is mandatory; fix company price for three companies
  lib/engine/game/g_18_zoo/entities.rb
  lib/engine/game/g_18_zoo/step/home_track.rb
  spec/fixtures/18ZOO/17.json
  spec/fixtures/18ZOO/18.json
  spec/fixtures/18ZOO/2.json
  spec/fixtures/18ZOO/4.json
  spec/fixtures/18ZOO/5.json
  spec/fixtures/18ZOO/bankrupt.player_debt.json
  spec/fixtures/18ZOO/dividend_as_president.json
  spec/fixtures/18ZOO/home_tile_mandatory.json
  spec/fixtures/18ZOO/or_power.moles.json
  spec/fixtures/18ZOO/or_power.on_a_diet.json
  spec/fixtures/18ZOO/sell_ticket_zoo_in_any_phase.json
  spec/fixtures/18ZOO/sell_ticket_zoo_in_any_step.json
  spec/fixtures/18ZOO/sr_power.days_off.json
  spec/lib/engine/games/g_18_zoo_spec.rb
Labels: archive_alpha_games

#5662 [1840] More fixes
  assets/app/view/game/game_info.rb
  lib/engine/game/base.rb
  lib/engine/game/g_1840/entities.rb
  lib/engine/game/g_1840/game.rb
  lib/engine/game/g_1840/step/buy_train.rb
  lib/engine/game/g_1840/step/dividend.rb
  lib/engine/game/g_1840/step/reassign_trains.rb
  lib/engine/game/g_1840/step/selection_auction.rb
Labels: archive_alpha_games

#5741 1862: fix PD after enforcing obligations
  lib/engine/game/g_1862/game.rb
Labels: pins

#5743 18Ireland fixes:
  lib/engine/company.rb
  lib/engine/game/g_18_ireland/game.rb
  validate.rb
Labels: archive_alpha_games

#5805 Fix erroneous price bubbles in 18FL
  lib/engine/game/g_18_fl/game.rb
  spec/fixtures/18FL/34258.json
  spec/fixtures/18FL/34832.json
  spec/fixtures/18FL/44940.json
  spec/fixtures/18FL/hotseat05.json
Labels: 18FL, pins

#5869 1860: remove valid route check from must_buy
  lib/engine/game/g_1860/step/buy_train.rb
Labels: pins

#5857 1873: add color check for non-concession laying concession tile
  lib/engine/game/g_1873/game.rb
  lib/engine/game/g_1873/step/track.rb
Labels: pins

#5793 18ZOO: fix https://github.com/tobymao/18xx/issues/5717
  lib/engine/game/g_18_zoo/game.rb
  lib/engine/step/tracker.rb
  spec/fixtures/18ZOO/or_power.rabbits.cannot_upgrade.json
  spec/lib/engine/games/g_18_zoo_spec.rb
Labels: archive_alpha_games
