Repository tobymao/18xx, pull requests merged in 2021-07, with the labels that each got.

#5892 1889 Beginner Game rules
  lib/engine/game/g_1889/game.rb
  lib/engine/game/g_1889/meta.rb
Labels: 1889, optional rules

#5896 1873: rounding issue on half dividend withholds
  lib/engine/game/g_1873/step/dividend.rb
Labels: Harzbahn 1873, pins

#5903 [1846] remove_from_group! - don't mutate the passed in group
  lib/engine/game/g_1846/game.rb
Labels: pins

#5918 [1840] Fixes forced buy and auction order
  lib/engine/game/g_1840/step/acquisition_auction.rb
  lib/engine/game/g_1840/step/buy_train.rb
Labels: archive_alpha_games

#5915 [18CZ] Fixes rusting bug
  lib/engine/game/g_18_cz/game.rb
Labels: pins

#5929 [1828.Games] Systems get 10x share price in their treasury
  lib/engine/game/g_1828/step/merger.rb
  lib/engine/game/g_1828/system.rb
Labels: pins

#5947 [1840] Remove Tokens is now an own action
  assets/app/view/game/part/city_slot.rb
  lib/engine/game/g_1840/game.rb
  lib/engine/game/g_1840/step/track_and_token.rb
  spec/fixtures/1840/2player.json
  spec/fixtures/1840/large_map.json
Labels: archive_alpha_games

#5951 Fix CMDs not paying correctly in 18VA & initial auction reordering
  lib/engine/game/g_18_va/game.rb
  lib/engine/game/g_18_va/step/dividend.rb
  lib/engine/game/g_18_va/step/waterfall_auction.rb
  spec/fixtures/18VA/README.md
  spec/fixtures/18VA/hotseat002.json
Labels: archive_alpha_games

#5996 1873: fix another half-dividend rounding issue
  lib/engine/game/g_1873/step/dividend.rb
  spec/fixtures/1873/hs_gwlftpex_33770.json
Labels: pins

#6010 1861/1867: Nationalization should repay loans if exact amount is left
  lib/engine/game/g_1867/game.rb
Labels: pins

#6011 1882: Fix behaviour if NWR owner places token on NWR tile
  lib/engine/game/g_1882/game.rb
  lib/engine/game/g_1882/step/special_nwr.rb
Labels: pins

#6026 18Ireland/61/67: Skip player for bidding if they are at cert limit
  lib/engine/step/buy_sell_par_shares_via_bid.rb
  migrate_game.rb
  spec/fixtures/18Ireland/39547.json
Labels: pins

#6075 1856/1836jr56: Stop buy-until-float autoaction on floatable?
  lib/engine/game/g_1856/step/buy_sell_par_shares.rb
Labels: pins

#6084 1862: cert change at LNER formation; freight-train UI fix
  lib/engine/game/g_1862/game.rb
Labels: pins

#6094 [1893] Do not allow buy of company when cert limit reached
  lib/engine/game/g_1893/step/buy_sell_par_shares.rb
Labels: 1893, pins

#6101 [18SJ] Change implementation to support version 0.8
  lib/engine/game/g_18_sj/game.rb
  lib/engine/game/g_18_sj/meta.rb
  lib/engine/game/g_18_sj/step/buy_company.rb
  lib/engine/game/g_18_sj/step/buy_train_action.rb
  lib/engine/game/g_18_sj/step/route.rb
  spec/fixtures/18SJ/19.json
  spec/fixtures/18SJ/21769.json
Labels: 18SJ, archive_alpha_games

#6115 18Carolinas: map tweak from Scott; fix spurs
  lib/engine/game/g_18_carolinas/map.rb
Labels: archive_alpha_games

#6130 18VA: Offmap cities are cities; they are doubled by 4Ds if untokened
  lib/engine/game/g_18_va/game.rb
Labels: archive_alpha_games

#6145 1840 fixed some smaller issues
  lib/engine/game/g_1840/entities.rb
  lib/engine/game/g_1840/game.rb
  lib/engine/game/g_1840/step/track_and_token.rb
Labels: archive_alpha_games

#6152 18Carolinas: rule change for private distribution
  lib/engine/game/g_18_carolinas/game.rb
Labels: archive_alpha_games
