Repository tobymao/18xx, pull requests merged in 2021-11, with the labels that each got.

#6485 18 tokaido running tweaks
  lib/engine/game/g_18_tokaido/entities.rb
  lib/engine/game/g_18_tokaido/game.rb
  lib/engine/game/g_18_tokaido/map.rb
  lib/engine/game/g_18_tokaido/meta.rb
  lib/engine/game/g_18_tokaido/step/buy_company.rb
  public/icons/18_tokaido/fm_token.svg
  public/logos/18_tokaido/TYR.alt.svg
  public/logos/18_tokaido/TYR.svg
Labels: 18Tokaido

#6502 1856: Fix CGR paying for kitchener token when it shouldn't need to
  lib/engine/game/g_1856/game.rb
  spec/fixtures/1856/51745.json
  spec/fixtures/1856/README.md
Labels: pins, 1856

#6511 [18 Tokaido] fix bug with stationmaster tama
  lib/engine/game/g_18_tokaido/step/buy_company.rb
Labels: bug, 18Tokaido

#6520 [1870] fix cert limit definition
  lib/engine/game/g_1870/game.rb
Labels: pins

#6527 [18NY] NYC Formation
  lib/engine/game/base.rb
  lib/engine/game/g_18_ireland/round/stock.rb
  lib/engine/game/g_18_ms/game.rb
  lib/engine/game/g_18_ny/entities.rb
  lib/engine/game/g_18_ny/game.rb
  lib/engine/game/g_18_ny/round/nyc_formation.rb
  lib/engine/game/g_18_ny/share_pool.rb
  lib/engine/game/g_18_ny/step/acquire_corporation.rb
  lib/engine/game/g_18_ny/step/bankrupt.rb
  lib/engine/game/g_18_ny/step/buy_sell_par_shares.rb
  lib/engine/game/g_18_ny/step/buy_train.rb
  lib/engine/game/g_18_ny/step/check_nyc_formation.rb
  lib/engine/game/g_18_ny/step/dividend.rb
  lib/engine/game/g_18_ny/step/emergency_money_raising.rb
  lib/engine/game/g_18_ny/step/merge_with_nyc.rb
  lib/engine/game/g_18_ny/step/route.rb
  lib/engine/game/g_18_ny/step/token.rb
  lib/engine/round/stock.rb
  lib/engine/share_pool.rb
  lib/engine/step/dividend.rb
  lib/engine/step/minor_half_pay.rb
  spec/fixtures/18TN/7818.json
Labels: pins

#6545 18Carolinas balance changes
  lib/engine/game/g_18_carolinas/map.rb
  lib/engine/game/g_18_carolinas/step/buy_power.rb
Labels: pins

#6546 18Texas - Rule change, always allow two yellow tiles
  lib/engine/game/g_18_texas/game.rb
Labels: pins
