Repository tobymao/18xx, pull requests merged in 2021-05, with the labels that each got.

#5224 18Ireland merger fixes:
  lib/engine/game/g_18_ireland/round/merger.rb
  lib/engine/game/g_18_ireland/step/merge.rb
  migrate_game.rb
Labels: migration

#5225 1873: increase cert limit; skips steps after closing mine; better diesel UI
  lib/engine/game/g_1873/game.rb
  lib/engine/game/g_1873/step/buy_train.rb
  lib/engine/game/g_1873/step/convert.rb
  lib/engine/game/g_1873/step/dividend.rb
Labels: archive_alpha_games

#5251 1870: Clear graph after placing destination token (closes #5068)
  lib/engine/game/g_1870/step/connection_token.rb
Labels: archive_alpha_games

#5250 1870: Don't count towards cert limit shares that may go to yellow (fixes #5076)
  lib/engine/game/g_1870/game.rb
Labels: archive_alpha_games

#5234 1870: Any share price is a valid par price for reissuing (fixes #5060)
  lib/engine/game/g_1870/step/buy_sell_par_shares.rb
Labels: archive_alpha_games

#5211 1828.Games: Fix merger bug
  lib/engine/game/g_1828/step/merger.rb
Labels: pins

#5235 1870: Fix stock movements (fixes #5067)
  lib/engine/game/g_1870/step/price_protection.rb
  lib/engine/game/g_1870/stock_market.rb
Labels: archive_alpha_games

#5243 [1822] If Tax Haven makes company float, it doesnt gain money when fu…
  lib/engine/game/g_1822/game.rb
Labels: pins

#5252 1870: Fix error on closing corporation (fixes #4987)
  lib/engine/game/g_1870/step/check_connection.rb
  lib/engine/step/buy_sell_par_shares.rb
Labels: archive_alpha_games

#5254 1870: Enforce "must sell down to 60%" rule during EMR (fixes #4566)
  lib/engine/game/g_1870/game.rb
  lib/engine/game/g_1870/step/buy_train.rb
Labels: archive_alpha_games

#5242 [1822] Minors shouldnt be able to run E trains
  lib/engine/game/g_1822/step/route.rb
Labels: pins

#5246 [1822] P21-HSBC is not working as described
  lib/engine/game/g_1822/step/tracker.rb
  lib/engine/step/tracker.rb
Labels: pins

#5315 18Ireland: Unused token after 2 corp merger should be £50 rather than £0
  lib/engine/game/g_18_ireland/step/merge.rb
  validate.rb
Labels: archive_alpha_games

#5316 18Ireland: Clarify which tiles apply for CDSPC
  lib/engine/game/g_18_ireland/entities.rb
  lib/engine/game/g_18_ireland/map.rb
Labels: archive_alpha_games

#5335 18Ireland: Disallow repeating the same merger proposal
  lib/engine/game/g_18_ireland/step/merge.rb
Labels: archive_alpha_games

#5354 1828: Allow player to retain soon-to-be system share and trade for a system share from another
  lib/engine/game/g_1828/step/merger.rb
Labels: pins

#5355 18zoo update names fix maps
  lib/engine/game/g_18_zoo/entities.rb
  lib/engine/game/g_18_zoo/game.rb
  lib/engine/game/g_18_zoo/map.rb
  lib/engine/game/g_18_zoo/step/assign.rb
  lib/engine/game/g_18_zoo/step/choose_ability_on_or.rb
  lib/engine/game/g_18_zoo/step/choose_ability_on_sr.rb
  lib/engine/game/g_18_zoo/step/special_token.rb
  lib/engine/game/g_18_zoo/step/train_protection.rb
  public/icons/18_zoo/patch.svg
  public/icons/18_zoo/wheat.svg
  spec/fixtures/18ZOO/2.json
  spec/fixtures/18ZOO/README.md
  spec/fixtures/18ZOO/hs_ofmjiayq_1617902980.json
  spec/fixtures/18ZOO/or_power.a_tip_of_sugar.json
  spec/fixtures/18ZOO/or_power.on_a_diet.json
  spec/fixtures/18ZOO/or_power.patch.json
  spec/fixtures/18ZOO/or_power.patch.with_whatsup.json
  spec/fixtures/18ZOO/or_power.shining_gold.json
  spec/fixtures/18ZOO/or_power.that_s_mine.cannot_convert_if_already_tokened.json
  spec/fixtures/18ZOO/or_power.that_s_mine.cannot_convert_if_no_money.json
  spec/fixtures/18ZOO/or_power.that_s_mine.cannot_convert_if_no_token.json
  spec/fixtures/18ZOO/or_power.that_s_mine.json
  spec/fixtures/18ZOO/or_power.wheat.json
  spec/fixtures/18ZOO/sr_power.days_off.json
  spec/fixtures/18ZOO/sr_power.it_s_all_greek_to_me.json
  spec/lib/engine/games/g_18_zoo_spec.rb
Labels: archive_alpha_games

#5376 1862 fixes: merges, map, London highlighting
  lib/engine/game/g_1862/game.rb
  lib/engine/game/g_1862/map.rb
  lib/engine/game/g_1862/step/token.rb
  lib/engine/game/g_1862/step/track.rb
Labels: archive_alpha_games

#5415 [18ZOO] many bugfixes
  lib/engine/game/g_18_zoo/entities.rb
  lib/engine/game/g_18_zoo/game.rb
  lib/engine/game/g_18_zoo/map.rb
  lib/engine/game/g_18_zoo/meta.rb
  lib/engine/game/g_18_zoo/round/operating.rb
  lib/engine/game/g_18_zoo/step/assign.rb
  lib/engine/game/g_18_zoo/step/dividend.rb
  spec/fixtures/18ZOO/or_power.a_tip_of_sugar.json
  spec/fixtures/18ZOO/or_power.patch.json
  spec/fixtures/18ZOO/or_power.patch.with_whatsup.json
  spec/fixtures/18ZOO/remove_3s_long_by_current_player.json
  spec/fixtures/18ZOO/remove_4s_by_current_player.json
  spec/game_state_spec.rb
  spec/lib/engine/games/g_18_zoo_spec.rb
Labels: archive_alpha_games

#5420 1862: Fix Hudson manoeuvre; Obligations should not impact share limit
  lib/engine/game/g_1862/game.rb
  lib/engine/game/g_1862/step/dividend.rb
Labels: archive_alpha_games

#5446 [1893] Implement FdSD private allowing for exchange for RAG
  lib/engine/game/g_1893/game.rb
  lib/engine/game/g_1893/step/buy_sell_par_shares.rb
  lib/engine/game/g_1893/step/par_and_buy_actions.rb
Labels: 1893

#5425 [1846] Implement 2E Private Companies, add 1E Optional Rule
  lib/engine/game/g_1846/entities.rb
  lib/engine/game/g_1846/game.rb
  lib/engine/game/g_1846/map.rb
  lib/engine/game/g_1846/meta.rb
  lib/engine/game/g_18_los_angeles/game.rb
  public/icons/1846/boom.svg
  public/icons/1846/bt_token.svg
  public/icons/1846/lm.svg
  spec/fixtures/1846 2p Variant/11098.json
  spec/fixtures/1846 2p Variant/hs_pzdxtics_1601680033.json
  spec/fixtures/1846/10264.json
  spec/fixtures/1846/12666.json
  spec/fixtures/1846/16904.json
  spec/fixtures/1846/19962.json
  spec/fixtures/1846/20381.json
  spec/fixtures/1846/22071.json
  spec/fixtures/1846/3099.json
  spec/fixtures/1846/hs_cvjhogoy_1599504419.json
  spec/fixtures/1846/hs_gcumggit_1595777670.json
  spec/fixtures/1846/hs_sudambau_1600037415.json
  spec/lib/engine/round/operating_spec.rb
Labels: migration

#5487 1862: fix chartered corp treasury buys; check london connection for links
  lib/engine/game/g_1862/game.rb
  lib/engine/game/g_1862/step/buy_sell_par_shares.rb
  lib/engine/game/g_1862/step/token.rb
Labels: archive_alpha_games

#5497 18Ireland: Disallow selling shares if corp can afford cheapest train
  assets/app/view/game/buy_trains.rb
  lib/engine/game/g_18_ireland/game.rb
  lib/engine/game/g_18_ireland/step/buy_train.rb
  lib/engine/step/buy_train.rb
  lib/engine/step/train.rb
Labels: archive_alpha_games

#5503 18ZOO: fixes 5495
  lib/engine/game/g_18_zoo/game.rb
  spec/fixtures/18ZOO/or_power.rabbits.home_to_gray_li.json
  spec/lib/engine/games/g_18_zoo_spec.rb
Labels: archive_alpha_games

#5512 1860: no out-of-turn exchanges; allow some exchanges after parring
  lib/engine/game/g_1860/game.rb
  lib/engine/game/g_1860/step/buy_sell_par_shares.rb
Labels: pins
