Repository tobymao/18xx, pull requests merged in 2021-09, with the labels that each got.

#6302 1862: fix ebuy bugs
  lib/engine/game/g_1862/step/buy_train.rb
Labels: pins, 1862

#6309 18Texas - Update private company descriptions
  lib/engine/game/g_18_texas/entities.rb
  lib/engine/game/g_18_texas/map.rb
Labels: archive_alpha_games

#6318 1873: enforce bids are multiples of 10
  lib/engine/game/g_1873/game.rb
Labels: pins

#6320 1860: four fixes
  lib/engine/game/g_1860/game.rb
  lib/engine/game/g_1860/step/buy_sell_par_shares_companies.rb
Labels: pins

#6334 1840 Fix 2player issues
  lib/engine/game/g_1840/game.rb
  spec/fixtures/1840/2player.json
Labels: pins

#6340 1825: fix inappropriate loan for track lay
  lib/engine/game/g_1825/step/track_and_token.rb
Labels: archive_alpha_games

#6366 1825: fix tile upgrade bugs
  lib/engine/game/g_1825/game.rb
  lib/engine/game/g_1825/map.rb
Labels: archive_alpha_games
