Repository tobymao/18xx, pull requests merged in 2021-01, with the labels that each got.

#2974 1867 Bug fixes
  lib/engine/config/game/g_1867.rb
  lib/engine/game/g_1867.rb
  lib/engine/round/g_1867/operating.rb
  lib/engine/step/g_1867/buy_sell_par_shares.rb
  lib/engine/step/g_1867/track.rb
  migrate_game.rb
  spec/fixtures/1867/hs_ahjzadkh_19792.json
Labels: migration, pins

#2992 18Mag map and tiles
  lib/engine/config/game/g_18_mag.rb
  lib/engine/game/base.rb
  lib/engine/game/g_18_mag.rb
  lib/engine/publisher.rb
  public/logos/18_mag/1.svg
  public/logos/18_mag/10.svg
  public/logos/18_mag/11.svg
  public/logos/18_mag/12.svg
  public/logos/18_mag/13.svg
  public/logos/18_mag/2.svg
  public/logos/18_mag/3.svg
  public/logos/18_mag/4.svg
  public/logos/18_mag/5.svg
  public/logos/18_mag/6.svg
  public/logos/18_mag/7.svg
  public/logos/18_mag/8.svg
  public/logos/18_mag/9.svg
  public/logos/18_mag/mine.svg
Labels: 18Mag

#3027 1867 Bug Fixes
  assets/app/view/game/buy_trains.rb
  lib/engine/config/game/g_1867.rb
  lib/engine/game/g_1867.rb
  lib/engine/round/g_1867/operating.rb
  lib/engine/round/operating.rb
  lib/engine/step/g_1817/track.rb
  lib/engine/step/g_1867/buy_train.rb
  lib/engine/step/g_1867/merge.rb
  lib/engine/step/g_1867/track.rb
  lib/engine/step/train.rb
  lib/engine/step/upgrade_track_max_exits.rb
  migrate_game.rb
Labels: migration, pins

#3035 1867: Disallow convert while a merge is in progress
  lib/engine/step/g_1867/merge.rb
Labels: pins

#3033 1867: In initial auction if declining to bid can rejoin after another…
  lib/engine/step/g_1867/single_item_auction.rb
  migrate_game.rb
Labels: migration

#3063 1867: Fix maximum merger price
  lib/engine/step/g_1867/merge.rb
Labels: pins

#3078 1824: 2nd edn. logos
  public/logos/1824/BH.svg
  public/logos/1824/BK.svg
  public/logos/1824/C1.svg
  public/logos/1824/C2.svg
  public/logos/1824/C3.svg
  public/logos/1824/C4.svg
  public/logos/1824/CL.svg
  public/logos/1824/K1.svg
  public/logos/1824/K2.svg
  public/logos/1824/KK.svg
  public/logos/1824/MS.svg
  public/logos/1824/S1.svg
  public/logos/1824/S2.svg
  public/logos/1824/S3.svg
  public/logos/1824/SB.svg
  public/logos/1824/SD.svg
  public/logos/1824/U1.svg
  public/logos/1824/U2.svg
  public/logos/1824/UG.svg
Labels: 1824

#3077 1867: Improve performance by not calculating token cost or list of co…
  lib/engine/step/g_1867/merge.rb
  lib/engine/step/g_1867/token.rb
  migrate_game.rb
  spec/assets_spec.rb
  spec/fixtures/1867/21268.json
Labels: migration

#2936 18CO Force Pass Player out of Cash
  DEVELOPMENT.md
  lib/engine/step/g_18_co/moving_bid_auction.rb
  migrate_game.rb
Labels: migration

#3007 Fix 18CO Closed companies being available for purchase
  lib/engine/game/g_18_co.rb
  migrate_game.rb
  spec/assets_spec.rb
  spec/fixtures/18CO/20708.json
Labels: migration

#2947 Ability timing refactor
  DEVELOPMENT.md
  assets/app/view/game/buy_trains.rb
  assets/app/view/game/part/blocker.rb
  lib/engine/ability/README.md
  lib/engine/ability/base.rb
  lib/engine/config/game/g_1817.rb
  lib/engine/config/game/g_1817_na.rb
  lib/engine/config/game/g_1817_wo.rb
  lib/engine/config/game/g_1828.rb
  lib/engine/config/game/g_1836_jr30.rb
  lib/engine/config/game/g_1846.rb
  lib/engine/config/game/g_1856.rb
  lib/engine/config/game/g_1882.rb
  lib/engine/config/game/g_1889.rb
  lib/engine/config/game/g_18_al.rb
  lib/engine/config/game/g_18_chesapeake.rb
  lib/engine/config/game/g_18_chesapeake_off_the_rails.rb
  lib/engine/config/game/g_18_co.rb
  lib/engine/config/game/g_18_ga.rb
  lib/engine/config/game/g_18_los_angeles.rb
  lib/engine/config/game/g_18_mex.rb
  lib/engine/config/game/g_18_ms.rb
  lib/engine/config/game/g_18_sj.rb
  lib/engine/config/game/g_18_tn.rb
  lib/engine/depot.rb
  lib/engine/game/base.rb
  lib/engine/game/g_1882.rb
  lib/engine/game/g_18_chesapeake.rb
  lib/engine/game/g_18_co.rb
  lib/engine/game/g_18_ga.rb
  lib/engine/game/g_18_sj.rb
  lib/engine/game/g_18_tn.rb
  lib/engine/ownable.rb
  lib/engine/phase.rb
  lib/engine/player.rb
  lib/engine/round/base.rb
  lib/engine/round/operating.rb
  lib/engine/round/stock.rb
  lib/engine/step/base.rb
  lib/engine/step/buy_company.rb
  lib/engine/step/g_1846/assign.rb
  lib/engine/step/g_1882/special_nwr.rb
  lib/engine/step/g_18_co/dividend.rb
  lib/engine/step/g_18_ga/special_track.rb
  lib/engine/step/g_18_ga/track.rb
  lib/engine/step/g_18_mex/special_track.rb
  lib/engine/step/g_18_mex/track.rb
  lib/engine/step/g_18_ms/special_track.rb
  lib/engine/step/g_18_ms/track.rb
  lib/engine/step/g_18_tn/special_track.rb
  lib/engine/step/g_18_tn/track.rb
  lib/engine/step/special_buy_train.rb
  lib/engine/step/special_track.rb
  lib/engine/step/tracker.rb
  spec/fixtures/1846/10264.json
  spec/fixtures/1882/10526.json
  spec/fixtures/18Chesapeake/14377.json
  spec/game_state_spec.rb
Labels: ability timing

#3183 fix "when" config for 18Chesapeake and Off the Rails
  lib/engine/config/game/g_18_chesapeake.rb
  lib/engine/config/game/g_18_chesapeake_off_the_rails.rb
  spec/assets_spec.rb
  spec/fixtures/18Chesapeake/1277.json
  spec/fixtures/18Chesapeake/14377.json
  spec/fixtures/18Chesapeake/1905.json
  spec/fixtures/18Chesapeake/2593.json
  spec/game_state_spec.rb
Labels: migration, pins

#3154 18SJ: Redesign main line tile lay/upgrade checks (fixes #3143)
  lib/engine/game/g_18_sj.rb
  lib/engine/step/g_18_sj/track.rb
  spec/fixtures/18SJ/19.json
Labels: pins

#3149 1867: Don't pay interest on loans already taken since it's already paid
  lib/engine/game/g_1817.rb
  lib/engine/game/g_1867.rb
  lib/engine/game/interest_on_loans.rb
  lib/engine/step/g_1867/buy_train.rb
  lib/engine/step/g_1867/post_merger_shares.rb
  migrate_game.rb
Labels: migration

#3206 1846, 18 Los Angeles: fix ability timing
  lib/engine/config/game/g_1846.rb
  lib/engine/config/game/g_18_los_angeles.rb
  lib/engine/game/base.rb
  lib/engine/game/g_1846.rb
  lib/engine/game/g_18_los_angeles.rb
  lib/engine/round/base.rb
  lib/engine/step/g_1846/assign.rb
Labels: pins

#3209 1817: Repeated log occurs if the buyer enters acquisition
  lib/engine/step/g_1817/acquire.rb
  migrate_game.rb
Labels: migration

#3249 1860: remove pass as option after winning auction
  lib/engine/step/g_1860/buy_cert.rb
Labels: pins

#3255 1867 bugs + move to beta
  lib/engine/game/g_1867.rb
  lib/engine/step/g_1867/loan_operations.rb
  lib/engine/step/g_1867/post_merger_shares.rb
  migrate_game.rb
Labels: migration

#3253 1817(+NA/WO) bugs needing migration/pins
  lib/engine/config/game/g_1817.rb
  lib/engine/config/game/g_1817_na.rb
  lib/engine/config/game/g_1817_wo.rb
  lib/engine/game/g_1817.rb
  lib/engine/step/g_1817/acquire.rb
  lib/engine/step/g_1817/buy_sell_par_shares.rb
  migrate_game.rb
  spec/fixtures/1817/15528.json
  spec/fixtures/1817WO/19926.json
Labels: migration, pins

#3271 18SJ: Fix Motala Verkstad (fixes #3267)
  lib/engine/config/game/g_18_sj.rb
  lib/engine/step/g_18_sj/buy_train.rb
  lib/engine/step/g_18_sj/buy_train_action.rb
  lib/engine/step/g_18_sj/buy_train_before_run_route.rb
Labels: migration

#3312 1882 NWR Ability timing
  lib/engine/config/game/g_1882.rb
Labels: migration, pins

#3377 [1828] various fixes
  lib/engine/game/g_1828.rb
Labels: bug

#3373 1867 bugs/improvements
  lib/engine/game/g_1867.rb
  lib/engine/step/g_1867/reduce_tokens.rb
Labels: pins

#3390 1867 bug fixes:
  lib/engine/game/g_1867.rb
  lib/engine/step/train.rb
Labels: pins

#3408 1817: Fix cash crisis when corp is in market
  lib/engine/step/g_1817/acquire.rb
Labels: pins

#3430 18Mag: fix phase change effect on next round
  lib/engine/game/g_18_mag.rb
Labels: 18Mag, pins

#3432 18SJ: Correct E train token handling (fixes #3173)
  lib/engine/game/g_18_sj.rb
  lib/engine/round/g_18_sj/operating.rb
  lib/engine/step/g_18_sj/buy_train_action.rb
  lib/engine/step/g_18_sj/dividend.rb
Labels: pins

#3474 1828: Bug fixes
  lib/engine/game/base.rb
  lib/engine/game/g_1828.rb
  lib/engine/phase.rb
  lib/engine/step/g_1828/buy_train.rb
  lib/engine/step/g_1828/merger.rb
Labels: pins

#3433 Add possibility to specify a selection of corporations for exchange
  assets/app/view/game/buy_sell_shares.rb
  assets/app/view/game/exchange.rb
  lib/engine/ability/README.md
  lib/engine/ability/exchange.rb
  lib/engine/config/game/g_1824.rb
  lib/engine/config/game/g_1828.rb
  lib/engine/config/game/g_1835.rb
  lib/engine/config/game/g_1836_jr30.rb
  lib/engine/config/game/g_1860.rb
  lib/engine/config/game/g_1882.rb
  lib/engine/config/game/g_1889.rb
  lib/engine/game/base.rb
  lib/engine/game/g_1882.rb
  lib/engine/step/exchange.rb
  lib/engine/step/g_1860/exchange.rb
Labels: 1824, 1828.Games, 1835, 1836Jr30, 1860, 1882, 1889

#3473 18Mag: K-tile bug fix; end-game bug fix
  lib/engine/game/g_18_mag.rb
  lib/engine/step/g_18_mag/track.rb
  lib/engine/tile.rb
Labels: pins

#3500 1867 bug fixes
  lib/engine/game/g_1867.rb
  lib/engine/step/g_1867/post_merger_shares.rb
Labels: pins

#3545 18CO - Issue Multiple Shares
  DEVELOPMENT.md
  lib/engine/game/g_18_co.rb
  migrate_game.rb
  spec/assets_spec.rb
  spec/fixtures/18CO/22032.json
Labels: 18CO, migration, pins

#3580 1860: fix bankruptcy bugs
  lib/engine/game/g_1860.rb
  lib/engine/round/g_1860/operating.rb
Labels: pins
