Repository tobymao/18xx, pull requests merged in 2022-01, with the labels that each got.

#6755 1825: lays on green/brown hexes are upgrades
  lib/engine/game/g_1825/step/track_and_token.rb
Labels: pins

#6765 Refactor buying_power
  lib/engine/game/base.rb
  lib/engine/game/g_1822/game.rb
  lib/engine/game/g_1846/game.rb
  lib/engine/game/g_1849/game.rb
  lib/engine/game/g_18_co/game.rb
  lib/engine/game/g_18_ireland/game.rb
  lib/engine/game/g_18_texas/game.rb
  spec/fixtures/18NewEngland/67847.json
Labels: pins

#6776 18NewEngland 2 - Improve Portland/Hartford
  lib/engine/game/g_18_new_england_north/map.rb
Labels: archive_alpha_games

#6794 18NewEngland: fix mergers when minors are "out of order"
  lib/engine/game/g_18_new_england/step/merge.rb
Labels: pins

#6802 18NewEngland: fix player reordering after first stock round
  lib/engine/game/g_18_new_england/game.rb
Labels: pins

#6815 18FL: Phase3 new corps must be 5 share, not 10
  lib/engine/game/g_18_fl/game.rb
Labels: pins, 18FL

#6826 [1822] Prevent London from being hit multiple times
  lib/engine/game/g_1822/map.rb
Labels: pins
