Repository tobymao/18xx, pull requests merged in 2022-02, with the labels that each got.

#6928 [1822MRS] Fixed the MT&P problem
  lib/engine/game/g_1822_mrs/game.rb
Labels: pins

#6964 1862: Prevent bidding when at cert limit
  lib/engine/game/g_1862/step/charter_auction.rb
Labels: pins

#6984 1877 - Add mine tiles, add "No Mine Tiles" optional variant
  assets/app/view/game/buy_trains.rb
  lib/engine/game/g_1877/game.rb
  lib/engine/game/g_1877/meta.rb
  spec/fixtures/1877/26036.json
Labels: pins

#6994 Implemented deferred second token falls for 2p 1846
  lib/engine/game/g_1846/game.rb
  lib/engine/game/g_1846/step/special_track.rb
  lib/engine/game/g_1846/step/track_and_token.rb
  lib/engine/game/g_18_los_angeles/game.rb
Labels: pins

#7005 [1840] make private symbols shorter to fit in spreadsheet
  lib/engine/game/g_1840/entities.rb
  spec/fixtures/1840/3player.json
Labels: pins

#7098 [1840] fixed reassign
  lib/engine/game/g_1840/step/reassign_trains.rb
  spec/fixtures/1840/3player.json
Labels: pins

#7139 18EU Alpha Fixes
  assets/app/view/game/part/city_slot.rb
  assets/app/view/game/round/auction.rb
  lib/engine/game/base.rb
  lib/engine/game/g_18_eu/entities.rb
  lib/engine/game/g_18_eu/game.rb
  lib/engine/game/g_18_eu/map.rb
  lib/engine/game/g_18_eu/step/buy_sell_par_shares.rb
  lib/engine/game/g_18_eu/step/final_exchange.rb
  lib/engine/game/g_18_eu/step/minor_exchange.rb
  lib/engine/game/g_18_eu/step/modified_dutch_auction.rb
  lib/engine/minor.rb
  lib/engine/step/share_buying.rb
  lib/engine/step/tracker.rb
Labels: 18EU, archive_alpha_games

#7161 18EU Fix 7160 Purchased Minor should place token
  lib/engine/game/g_18_eu/step/modified_dutch_auction.rb
Labels: 18EU

#7237 21 Moon: EMR fix; new price-change rule; better icons for color blindness
  assets/app/view/game/buy_trains.rb
  assets/app/view/game/issue_shares.rb
  lib/engine/game/g_21_moon/game.rb
  lib/engine/game/g_21_moon/step/buy_train.rb
  public/icons/21Moon/R_brown.svg
  public/icons/21Moon/R_gray.svg
  public/icons/21Moon/R_green.svg
  public/icons/21Moon/R_yellow.svg
Labels: archive_alpha_games

#7241 18EU Fix 7236 Force Discard Pullman on Merge
  lib/engine/game/g_18_eu/game.rb
  lib/engine/game/g_18_eu/step/minor_exchange.rb
Labels: archive_alpha_games

#7249 18MO: bug fixes and rules changes
  lib/engine/ability/README.md
  lib/engine/game/g_1835/entities.rb
  lib/engine/game/g_18_mo/entities.rb
  lib/engine/game/g_18_mo/game.rb
  lib/engine/game/g_18_mo/step/draft_purchase.rb
  lib/engine/game/g_18_mo/step/exchange.rb
  lib/engine/game/g_18_mo/step/special_token.rb
  lib/engine/game/g_18_neb/game.rb
Labels: archive_alpha_games

#7252 [18NY] Second rules iteration of 18NY second edition prototype
  lib/engine/depot.rb
  lib/engine/game/base.rb
  lib/engine/game/g_18_ny/game.rb
  lib/engine/game/g_18_ny/map.rb
Labels: pins, 18NY

#7340 [18USA] Bug fixes
  lib/engine/game/g_18_usa/game.rb
  lib/engine/game/g_18_usa/step/acquire.rb
  lib/engine/game/g_18_usa/step/conversion.rb
  lib/engine/game/g_18_usa/step/loan.rb
  lib/engine/game/g_18_usa/step/post_conversion_loans.rb
  lib/engine/game/g_18_usa/step/scrap_train_module.rb
Labels: archive_alpha_games

#7348 [18USA] Rulebook has the incorrect value for DFW's brown tile.
  lib/engine/game/g_18_usa/entities.rb
  lib/engine/game/g_18_usa/game.rb
  lib/engine/game/g_18_usa/map.rb
  lib/engine/game/g_18_usa/step/special_token.rb
Labels: archive_alpha_games
