Repository tobymao/18xx, pull requests merged in 2022-05, with the labels that each got.

#7692 [18USA] Offer pullman scrapping even if its the only post acquisition action
  lib/engine/game/g_18_usa/entities.rb
  lib/engine/game/g_18_usa/game.rb
  lib/engine/game/g_18_usa/step/acquire.rb
  lib/engine/game/g_18_usa/step/buy_sell_par_shares.rb
Labels: pins

#7704 [18NY] Bug fixes and enhancements
  assets/app/view/game/map.rb
  lib/engine/game/base.rb
  lib/engine/game/g_1825/game.rb
  lib/engine/game/g_18_ny/entities.rb
  lib/engine/game/g_18_ny/game.rb
  lib/engine/game/g_18_ny/step/dividend.rb
  lib/engine/game/g_21_moon/game.rb
  lib/engine/step/special_buy_train.rb
  lib/engine/step/special_track.rb
  lib/engine/step/tracker.rb
  lib/engine/step/train.rb
Labels: pins

#7707 [18NY] Next wave of 2nd edition changes requested by Pierre
  lib/engine/game/g_18_ny/game.rb
  lib/engine/game/g_18_ny/step/token.rb
Labels: pins

#7714 [18USA] Allow pullman scrapping, even when there are no loan actions
  lib/engine/game/g_18_usa/step/loan.rb
  lib/engine/game/g_18_usa/step/post_conversion_loans.rb
Labels: pins

#7712 [1828.Games] Bug fixes
  lib/engine/game/g_1828/game.rb
  lib/engine/game/g_1828/step/merger.rb
  lib/engine/game/g_1828/step/route.rb
  lib/engine/game/g_1840/game.rb
  lib/engine/graph.rb
  lib/engine/step/tracker.rb
  spec/lib/engine/round/operating_spec.rb
Labels: pins

#7743 New prototype version (0.92) with breaking changes
  assets/app/view/welcome.rb
  lib/engine/game/g_18_sj/entities.rb
  lib/engine/game/g_18_sj/game.rb
  lib/engine/game/g_18_sj/map.rb
  lib/engine/game/g_18_sj/meta.rb
  lib/engine/game/g_18_sj/round/operating.rb
  lib/engine/game/g_18_sj/step/assign_gotakanalbolaget.rb
  lib/engine/game/g_18_sj/step/assign_sveabolaget.rb
  lib/engine/game/g_18_sj/step/buy_company.rb
  lib/engine/game/g_18_sj/step/buy_train_before_run_route.rb
  lib/engine/game/g_18_sj/step/route.rb
  public/icons/18_sj/20.svg
  public/icons/18_sj/30.svg
  public/icons/18_sj/50.svg
  spec/fixtures/18SJ/hs_aaqpquno_1627552247.json
Labels: pins, 18SJ

#7762 18SJ: Add spec file and some minor fixes
  lib/engine/game/g_18_sj/meta.rb
  lib/engine/game/g_18_sj/step/buy_company.rb
  spec/fixtures/18SJ/hs_gswmvkvs_5.json
Labels: 18SJ

#7769 18Rhl: Fix some tiles
  lib/engine/game/g_18_rhl/map.rb
Labels: 18Rhl

#7770 18SJ: Correct bug with GKB (fixes #7768)
  lib/engine/game/g_18_sj/game.rb
  lib/engine/game/g_18_sj/step/route.rb
Labels: 18SJ

#7838 18GB 2E Updates
  lib/engine/game/g_18_gb/entities.rb
  lib/engine/game/g_18_gb/game.rb
  lib/engine/game/g_18_gb/step/buy_sell_par_shares.rb
Labels: archive_alpha_games

#7844 18usa - fix toronto gray value
  lib/engine/game/g_18_usa/map.rb
Labels: pins

#7853 [18NY, 18USA] Bug fixes
  lib/engine/game/g_18_ny/game.rb
  lib/engine/game/g_18_ny/map.rb
  lib/engine/game/g_18_ny/step/buy_train.rb
  lib/engine/game/g_18_usa/step/buy_sell_par_shares.rb
Labels: pins
