Repository tobymao/18xx, pull requests merged in 2022-12, with the labels that each got.

#8552 [1848] add missing token for CAR
  lib/engine/game/g_1848/game.rb
  spec/fixtures/1848/1848_game.json
  spec/fixtures/1848/online.json
Labels: pins

#8556 [1822MX,1822PNW] allow LP train to use Mail Contract privates
  lib/engine/game/g_1822/game.rb
  lib/engine/game/g_1822_mx/game.rb
  lib/engine/game/g_1822_pnw/game.rb
Labels: pins, archive_alpha_games

#8559 [TOP 1871] enforce MUST_SELL_IN_BLOCKS in BuyTrain#can_sell? override
  lib/engine/game/g_1871/step/buy_train.rb
Labels: archive_alpha_games

#8596 [1846 2p] deferred token fixes
  lib/engine/game/g_1846/game.rb
  lib/engine/game/g_18_los_angeles/game.rb
  lib/engine/game/g_18_los_angeles1/game.rb
Labels: pins

#8601 [1846] prevent cross-buying train from presidentless corporation
  lib/engine/game/g_1846/step/buy_train.rb
Labels: pins
