Repository tobymao/18xx, pull requests merged in 2022-06, with the labels that each got.

#7870 [1817] Implement Volatility expansion
  assets/app/view/welcome.rb
  lib/engine/ability/train_scrapper.rb
  lib/engine/depot.rb
  lib/engine/game/g_1817/entities.rb
  lib/engine/game/g_1817/game.rb
  lib/engine/game/g_1817/map.rb
  lib/engine/game/g_1817/meta.rb
  lib/engine/game/g_1817/round/merger.rb
  lib/engine/game/g_1817/step/acquire.rb
  lib/engine/game/g_1817/step/buy_sell_par_shares.rb
  lib/engine/game/g_1817/step/selection_auction.rb
  lib/engine/game/g_1817/step/special_track.rb
  lib/engine/game/g_1817/step/track.rb
  lib/engine/game/g_1817_na/game.rb
  lib/engine/game/g_1817_wo/game.rb
  lib/engine/game/g_18_usa/game.rb
  public/icons/1817/ranch_token.svg
Labels: pins

#7912 Prohibit entities from buying trains from themselves
  lib/engine/step/train.rb
Labels: pins

#7921 1873: don't allow out of phase tile colors if not concession route building
  lib/engine/game/g_1873/step/track.rb
Labels: pins

#7939 21Moon: close P2, P4 and P6 after use
  lib/engine/game/g_21_moon/entities.rb
  lib/engine/game/g_21_moon/game.rb
  lib/engine/game/g_21_moon/step/assign.rb
  lib/engine/game/g_21_moon/step/exchange.rb
  spec/fixtures/21Moon/73613.json
Labels: pins

#7952 [1822MX] Bug fixes
  lib/engine/game/g_1822/entities.rb
  lib/engine/game/g_1822/game.rb
  lib/engine/game/g_1822/step/minor_acquisition.rb
  lib/engine/game/g_1822_mx/entities.rb
  lib/engine/game/g_1822_mx/step/minor_acquisition.rb
  lib/engine/part/city.rb
  spec/fixtures/1822_mx/85808.json
Labels: pins

#8007 18SJ: Implement changes for alpha
  assets/app/view/welcome.rb
  lib/engine/game/g_18_sj/game.rb
  lib/engine/game/g_18_sj/map.rb
  lib/engine/game/g_18_sj/meta.rb
  lib/engine/game/g_18_sj/step/issue_shares.rb
  spec/fixtures/18SJ/hs_gswmvkvs_5.json
Labels: pins, 18SJ, archive_alpha_games

#8025 [18NY] 2E balance changes
  lib/engine/game/g_18_ny/game.rb
Labels: pins, 18NY

#8021 18SJ: Align tiles to AAG standard (fixes #8020)
  lib/engine/game/g_18_sj/map.rb
Labels: pins, 18SJ
