Repository tobymao/18xx, pull requests merged in 2022-03, with the labels that each got.

#7379 1873: more stringent concession route checks
  lib/engine/game/g_1873/game.rb
  lib/engine/game/g_1873/step/route.rb
Labels: pins

#7395 18GB Alpha changes
  lib/engine/game/g_18_gb/entities.rb
  lib/engine/game/g_18_gb/meta.rb
Labels: archive_alpha_games

#7406 [18USA] Bug fixes
  lib/engine/game/base.rb
  lib/engine/game/g_1817/step/buy_sell_par_shares.rb
  lib/engine/game/g_18_usa/game.rb
  lib/engine/game/g_18_usa/step/assign.rb
  lib/engine/game/g_18_usa/step/buy_sell_par_shares.rb
  lib/engine/game/g_18_usa/step/special_track.rb
  lib/engine/part/city.rb
  lib/engine/step/tracker.rb
  migrate_game.rb
Labels: migration, 18USA

#7423 18MEX: Handle NdM 5% corner case (fixes #7360)
  lib/engine/game/g_18_mex/step/buy_sell_par_shares.rb
  lib/engine/game/g_18_mex/step/swap_buy_sell.rb
Labels: pins

#7469 18Mag: Fix map E14
  lib/engine/game/g_18_mag/game.rb
  spec/fixtures/18MAG/32695.json
Labels: pins

#7462 18MEX: Allow buying from IPO for "yellow" corps (fixes #7446)
  lib/engine/game/g_18_mex/step/buy_sell_par_shares.rb
Labels: pins

#7513 [1866] Wrong palace car price
  lib/engine/game/g_1866/game.rb
Labels: archive_alpha_games

#7528 close_corporation now closes corporations
  lib/engine/corporation.rb
  lib/engine/game/base.rb
  lib/engine/game/g_1825/game.rb
  lib/engine/game/g_1840/game.rb
  lib/engine/game/g_1846/step/bankrupt.rb
  lib/engine/game/g_1849/game.rb
  lib/engine/game/g_1856/game.rb
  lib/engine/game/g_1870/game.rb
  lib/engine/game/g_18_co/game.rb
  lib/engine/game/g_18_co/step/acquisition_auction.rb
  lib/engine/game/g_18_co/step/moving_bid_auction.rb
  lib/engine/game/g_18_co/step/takeover.rb
  lib/engine/game/g_18_cz/step/buy_corporation.rb
  lib/engine/game/g_18_cz/step/reduce_tokens.rb
  lib/engine/game/g_18_eu/step/bankrupt.rb
  lib/engine/game/g_18_eu/step/replace_token.rb
  lib/engine/game/g_18_ireland/game.rb
  lib/engine/game/g_18_mt/step/takeover.rb
  lib/engine/game/g_18_new_england/step/bankrupt.rb
  lib/engine/game/g_18_ny/game.rb
  lib/engine/game/g_18_ny/step/bankrupt.rb
  lib/engine/game/g_18_va/game.rb
  lib/engine/game/g_21_moon/step/bankrupt.rb
  lib/engine/minor.rb
Labels: pins

#7555 [1866] Same hex twice
  lib/engine/game/g_1866/game.rb
Labels: archive_alpha_games
