Repository tobymao/18xx, pull requests merged in 2023-01, with the labels that each got.

#8616 [18Rhl] Fix CMV bug for RhE (fixes #8608)
  lib/engine/game/g_18_rhl/game.rb
  spec/fixtures/18Rhl/96576.json
Labels: pins

#8626 [18USA] Add-in additional no subsidy subsidies
  lib/engine/game/g_18_usa/entities.rb
Labels: pins, 18USA

#8633 [1861/1867] Fix nationalisation order
  lib/engine/game/g_1867/game.rb
  spec/fixtures/1861/167259.json
  spec/game_state_spec.rb
Labels: pins, 1867, 1861

#8689 [1861/1867] Fix merger token bugs (issue #8589)
  lib/engine/game/g_1867/step/merge.rb
  lib/engine/game/g_1867/step/reduce_tokens.rb
Labels: pins, 1867, 1861

#8732 [1822PNW] Change spelling 'grey' to 'gray' on tile 455
  lib/engine/game/g_1822_pnw/map.rb
Labels: 1822PNW

#8746 Extend Engine::Step::BuySellParSharesViaBid to handle company auctions
  lib/engine/step/buy_sell_par_shares_via_bid.rb
Labels: 1858
