Repository tobymao/18xx, pull requests merged in 2023-09, with the labels that each got.

#9527 Clear `selected_company` when processing an action received from server
  assets/app/view/game_page.rb
Labels: Core

#9528 [1846] Don't allow president contributions when a cheaper Discarded train is available
  assets/app/view/game/buy_trains.rb
  lib/engine/game/g_1846/step/buy_train.rb
Labels: pins

#9548 fix(1840): fixed company round sorting
  lib/engine/game/g_1840/game.rb
  lib/engine/game/g_1840/round/acquisition.rb
  lib/engine/game/g_1840/round/company.rb
  public/fixtures/1840/2player.json
  public/fixtures/1840/3player.json
Labels: pins

#9564 [1822Africa] Fix unnecessary removal of unpurchased minors
  lib/engine/game/g_1822_africa/round/stock.rb
Labels: archive_alpha_games

#9568 1822Africa - Playtest Change - Change market
  lib/engine/game/g_1822_africa/game.rb
Labels: archive_alpha_games

#9571 [1822Africa] Adjust water tile
  lib/engine/game/g_1822_africa/map.rb
Labels: archive_alpha_games

#9590 Changed interface messages: end of game description and choice explanations
  assets/app/view/game/choose.rb
  lib/engine/game/base.rb
  lib/engine/game/g_1858/step/private_closure.rb
Labels: game UI, 1858, Core

#9593 Don't return `nil` in methods returning rendered items
  assets/app/view/game/bank.rb
  assets/app/view/game/buy_trains.rb
  assets/app/view/game/corporate_buy_shares.rb
  assets/app/view/game/flexible_buy.rb
  assets/app/view/game/game_info.rb
  assets/app/view/game/hex.rb
  assets/app/view/game/issue_shares.rb
  assets/app/view/game/map_controls.rb
  assets/app/view/game/par_chart.rb
  assets/app/view/game/round/unordered.rb
  assets/app/view/game/scrap_trains.rb
  assets/app/view/game/tranches.rb
  assets/app/view/game_card.rb
  assets/app/view/game_row_filters.rb
Labels: Core

#9585 1841: adjust new prez calc, ignore corp auto actions, allow partial b…
  lib/engine/game/g_1841/game.rb
  lib/engine/game/g_1841/step/corporate_buy_sell_par_shares.rb
Labels: archive_alpha_games

#9611 [1858] Private railway exchange approval. Move to public alpha status.
  lib/engine/game/g_1858/entities.rb
  lib/engine/game/g_1858/game.rb
  lib/engine/game/g_1858/meta.rb
  lib/engine/game/g_1858/step/exchange.rb
  lib/engine/game/g_1858/step/exchange_approval.rb
  lib/engine/game/g_1858/step/home_token.rb
  lib/engine/game/g_1858/step/private_closure.rb
  lib/engine/game/g_1858/step/private_exchange.rb
Labels: 1858

#9602 18tokaido beta prototype tweaks
  lib/engine/game/g_18_tokaido/entities.rb
  lib/engine/game/g_18_tokaido/game.rb
  lib/engine/game/g_18_tokaido/meta.rb
  lib/engine/game/g_18_tokaido/step/buy_sell_par_shares.rb
  lib/engine/game/g_18_tokaido/tiles.rb
Labels: 18Tokaido

#9589 [18Ardennes] Track laying, tokening, running trains
  assets/app/view/game/round/auction.rb
  assets/app/view/game/route_selector.rb
  lib/engine/action/run_routes.rb
  lib/engine/game/base.rb
  lib/engine/game/g_18_ardennes/entities.rb
  lib/engine/game/g_18_ardennes/game.rb
  lib/engine/game/g_18_ardennes/map.rb
  lib/engine/game/g_18_ardennes/market.rb
  lib/engine/game/g_18_ardennes/step/collect_forts.rb
  lib/engine/game/g_18_ardennes/step/dividend.rb
  lib/engine/game/g_18_ardennes/step/home_hex_tile.rb
  lib/engine/game/g_18_ardennes/step/route.rb
  lib/engine/game/g_18_ardennes/step/token.rb
  lib/engine/game/g_18_ardennes/step/track.rb
  lib/engine/game/g_18_ardennes/trains.rb
  lib/engine/step/dividend.rb
  lib/engine/step/route.rb
  public/icons/18_ardennes/east.svg
  public/icons/18_ardennes/north.svg
  public/icons/18_ardennes/south.svg
  public/icons/18_ardennes/west.svg
  public/logos/18_ardennes/fort.svg
  public/logos/18_ardennes/mine.svg
  public/logos/18_ardennes/port.svg
Labels: Core, 18Ardennes

#9630 Adds 1858 alpha announcement to the welcome page
  assets/app/view/welcome.rb
Labels: front page, 1858

#9660 [18USA] Company contributions beyond bid amount don't refund cash to …
  lib/engine/game/g_18_usa/step/buy_sell_par_shares.rb
Labels: pins, 18USA

#9653 [1844] Misc OR functionality
  assets/app/view/game/buy_trains.rb
  lib/engine/game/base.rb
  lib/engine/game/g_1841/step/buy_train.rb
  lib/engine/game/g_1844/entities.rb
  lib/engine/game/g_1844/game.rb
  lib/engine/game/g_1844/map.rb
  lib/engine/game/g_1844/round/operating.rb
  lib/engine/game/g_1844/step/buy_company.rb
  lib/engine/game/g_1844/step/buy_train.rb
  lib/engine/game/g_1844/step/destination.rb
  lib/engine/game/g_1844/step/dividend.rb
  lib/engine/game/g_1844/step/mountain_railway_track.rb
  lib/engine/step/dividend.rb
  lib/engine/step/tracker.rb
  lib/engine/step/train.rb
  public/fixtures/1889/314.json
  public/fixtures/18GB/18gb-3p.json
  public/fixtures/18GB/18gb-6p.json
  public/fixtures/18Texas/65394.json
  spec/assets_spec.rb
Labels: migrate_game

#9650 1841: give money to corp when upgrading merger shares
  lib/engine/game/g_1841/game.rb
  public/fixtures/1841/132002.json
Labels: archive_alpha_games

#9629 [1822Africa] Refactor E trains
  assets/app/view/welcome.rb
  lib/engine/game/g_1822_africa/game.rb
  lib/engine/game/g_1822_africa/meta.rb
  lib/engine/game/g_1822_africa/step/choose_express_train.rb
  lib/engine/game/g_1822_africa/step/choose_safari_train.rb
  lib/engine/game/g_1822_africa/step/route.rb
  lib/engine/train.rb
Labels: archive_alpha_games

#9643 [1858] Fix incorrect home hex descriptions on privates
  lib/engine/game/g_1858/entities.rb
Labels: 1858

#9680 [1822Africa] Allow placing Gold Mine if corporation is out of tokens
  lib/engine/game/g_1822_africa/game.rb
  lib/engine/game/g_1822_africa/step/special_token.rb
  lib/engine/game/g_1822_africa/step/token.rb
Labels: 1822Africa

#9690 [1861/1867] Fix share-buying order, RSR train purchasing, and malformed log message
  lib/engine/game/g_1861/game.rb
  lib/engine/game/g_1861/step/buy_train.rb
  lib/engine/game/g_1867/step/merge.rb
Labels: pins, 1867, 1861

#9703 [1861/1867] Show unstarted corporations on entities page
  lib/engine/game/g_1861/game.rb
  lib/engine/game/g_1867/game.rb
Labels: 1867, 1861

#9704 [1858] Add missing home hex markers
  lib/engine/game/g_1858/map.rb
Labels: 1858
