Repository tobymao/18xx, pull requests merged in 2023-10, with the labels that each got.

#9697 [1861/1867] Switch merger round PostMergerShares and ReduceTokens steps
  lib/engine/game/g_1867/game.rb
  migrate_game.rb
  public/fixtures/1867/hs_ahjzadkh_19792.json
Labels: 1867, 1861, migrate_game

#9715 [18Tokaido] color plus name changes to match print version
  lib/engine/game/g_18_tokaido/entities.rb
  lib/engine/game/g_18_tokaido/tiles.rb
  public/logos/18_tokaido/ARC.alt.svg
  public/logos/18_tokaido/ARC.svg
  public/logos/18_tokaido/KRC.alt.svg
  public/logos/18_tokaido/KRC.svg
  public/logos/18_tokaido/NAN.alt.svg
  public/logos/18_tokaido/NAN.svg
  public/logos/18_tokaido/SHI.alt.svg
  public/logos/18_tokaido/SHI.svg
  public/logos/18_tokaido/SRC.alt.svg
  public/logos/18_tokaido/SRC.svg
  public/logos/18_tokaido/YSL.alt.svg
  public/logos/18_tokaido/YSL.svg
Labels: pins, 18Tokaido

#9721 [1870] adds missing arguments for can_sell?
  lib/engine/game/g_1870/step/price_protection.rb
Labels: pins, 1870

#9723 [1870] re-order corps after destination run
  lib/engine/game/g_1870/step/connection_dividend.rb
  public/fixtures/1870/1638406193 brown price protect at cert limit allowed.json
  public/fixtures/1870/41645.json
Labels: pins, 1870

#9741 [1858] Move to beta
  assets/app/view/welcome.rb
  lib/engine/game/g_1858/meta.rb
Labels: 1858

#9746 [1822Africa] Fix bugs
  lib/engine/game/g_1822_africa/entities.rb
  lib/engine/game/g_1822_africa/game.rb
  lib/engine/game/g_1822_africa/step/assign.rb
Labels: pins

#9774 [1822 family] never let minors use a private to lay brown or gray tiles
  lib/engine/game/g_1822/step/special_track.rb
Labels: pins

#9796 [1822Africa] Change P5 from Pullman to Add Town
  lib/engine/game/g_1822_africa/entities.rb
  lib/engine/game/g_1822_africa/game.rb
  lib/engine/game/g_1822_africa/step/special_track.rb
Labels: pins

#9814 [21Moon] New Corps and Logos
  lib/engine/game/g_21_moon/entities.rb
  migrate_moon.rb
  public/logos/21Moon/DSE.svg
  public/logos/21Moon/HMQ.svg
  public/logos/21Moon/IPI.svg
  public/logos/21Moon/ITC.svg
  public/logos/21Moon/KR.svg
  public/logos/21Moon/LG.svg
  public/logos/21Moon/LP.svg
  public/logos/21Moon/MA.svg
  public/logos/21Moon/ME.svg
  public/logos/21Moon/MV.svg
  public/logos/21Moon/SM.svg
  public/logos/21Moon/SSF.svg
  public/logos/21Moon/SWP.svg
  public/logos/21Moon/VH.svg
Labels: migration

#9836 1841: prohibit x-corp EMR buy; prohibit selling last non-pass placed token
  lib/engine/game/g_1841/step/buy_token.rb
  lib/engine/game/g_1841/step/buy_train.rb
Labels: archive_alpha_games

#9842 [1844] Trigger destination check before skipping steps
  lib/engine/game/g_1844/game.rb
  lib/engine/game/g_1844/step/destination_check.rb
  lib/engine/round/base.rb
Labels: migrate_game, 1844
