Repository tobymao/18xx, pull requests merged in 2023-08, with the labels that each got.

#9320 Reservation icons
  assets/app/view/game/map.rb
  assets/app/view/game/part/city_slot.rb
  lib/engine/ability/reservation.rb
  lib/engine/game/g_1858/entities.rb
  lib/engine/game/g_1858/game.rb
  lib/engine/game/g_1858/step/track.rb
  public/icons/1858/CM+CS.svg
  public/icons/1858/CS+SJC.svg
  public/icons/1858/MZ+ZP.svg
Labels: map, 1858, Core

#9301 [1856] fixes train limit increase for CGR
  lib/engine/game/g_1856/entities.rb
Labels: pins

#9392 1841: deal with pres cert xfer during merger
  lib/engine/game/g_1841/game.rb
  lib/engine/share_pool.rb
Labels: archive_alpha_games

#9399 1841: fix issues with post-merger stock prices
  lib/engine/game/g_1841/game.rb
Labels: archive_alpha_games

#9377 18Dixie: Only allow "buying" one thing during a SR turn
  lib/engine/game/g_18_dixie/step/buy_sell_par_shares.rb
Labels: 18Dixie

#9385 1858 fixes
  lib/engine/game/g_1858/entities.rb
  lib/engine/game/g_1858/game.rb
  lib/engine/game/g_1858/map.rb
  lib/engine/game/g_1858/meta.rb
  lib/engine/game/g_1858/step/buy_sell_par_shares.rb
  lib/engine/game/g_1858/step/token.rb
  public/icons/1858/AS.svg
  public/icons/1858/BCR.svg
  public/icons/1858/BM.svg
  public/icons/1858/CB.svg
  public/icons/1858/CM.svg
  public/icons/1858/CS.svg
  public/icons/1858/LC.svg
  public/icons/1858/MA.svg
  public/icons/1858/MC.svg
  public/icons/1858/MV.svg
  public/icons/1858/MZ.svg
  public/icons/1858/PL.svg
  public/icons/1858/RT.svg
  public/icons/1858/SJC.svg
  public/icons/1858/VJ.svg
  public/icons/1858/ZP.svg
  public/logos/1858/AS.svg
  public/logos/1858/BCR.svg
  public/logos/1858/BM.svg
  public/logos/1858/CB.svg
  public/logos/1858/CM.svg
  public/logos/1858/CMP.svg
  public/logos/1858/CS.svg
  public/logos/1858/HG.svg
  public/logos/1858/LC.svg
  public/logos/1858/LG.svg
  public/logos/1858/MA.svg
  public/logos/1858/MC.svg
  public/logos/1858/MS.svg
  public/logos/1858/MV.svg
  public/logos/1858/MZ.svg
  public/logos/1858/OV.svg
  public/logos/1858/PL.svg
  public/logos/1858/RT.svg
  public/logos/1858/SC.svg
  public/logos/1858/SJC.svg
  public/logos/1858/VJ.svg
  public/logos/1858/ZP.svg
Labels: 1858

#9403 1841: Fix who decides on merger tokens; fix problem with minor merger…
  lib/engine/game/g_1841/game.rb
Labels: archive_alpha_games

#9384 Allow consent checks to be required for choose actions
  assets/app/view/game/choose.rb
  lib/engine/game/base.rb
  lib/engine/game/g_1858/game.rb
  lib/engine/game/g_1858/step/private_closure.rb
Labels: game UI, 1858, Core

#9420 1841: 2 fixes + fixture
  lib/engine/game/g_1841/game.rb
  public/fixtures/1841/132002.json
Labels: archive_alpha_games

#9428 1841: fix share offer on minor xform
  lib/engine/game/g_1841/game.rb
Labels: archive_alpha_games

#9450 [1858] performance improvements and fixes
  lib/engine/game/g_1858/step/buy_sell_par_shares.rb
  lib/engine/game/g_1858/step/token.rb
  lib/engine/game/g_1858/step/track.rb
  public/logos/1858/AS.svg
  public/logos/1858/BCR.svg
  public/logos/1858/BM.svg
  public/logos/1858/CB.svg
  public/logos/1858/CM.svg
  public/logos/1858/CMP.svg
  public/logos/1858/CS.svg
  public/logos/1858/HG.svg
  public/logos/1858/LC.svg
  public/logos/1858/LG.svg
  public/logos/1858/MA.svg
  public/logos/1858/MC.svg
  public/logos/1858/MS.svg
  public/logos/1858/MV.svg
  public/logos/1858/MZ.svg
  public/logos/1858/OV.svg
  public/logos/1858/PL.svg
  public/logos/1858/RT.svg
  public/logos/1858/SC.svg
  public/logos/1858/SJC.svg
  public/logos/1858/VJ.svg
  public/logos/1858/ZP.svg
Labels: 1858

#9469 [18Texas] Fixes train discard
  lib/engine/game/g_18_texas/game.rb
  lib/engine/game/g_18_texas/step/discard_train.rb
Labels: pins

#9463 [1888] fixes market to match final production copy
  lib/engine/game/g_1888/game.rb
  public/fixtures/1888/128097.json
  public/fixtures/1888/129026.json
  public/fixtures/1888/63897.json
Labels: pins

#9456 [1848] take loan for 2E if trainlocked
  lib/engine/game/g_1848/step/buy_train.rb
  public/fixtures/1848/1848_game.json
  public/fixtures/1848/1848_hotseat_game.json
  public/fixtures/1848/online.json
Labels: pins

#9479 [1822Africa] */E train fixes
  lib/engine/game/g_1822_africa/game.rb
Labels: pins

#9487 1822Africa - change bidding tokens for 3p/4p
  lib/engine/game/g_1822_africa/game.rb
Labels: pins

#9495 [1822CA, 1822MX] if a city has multiple tokens from one corp, return extra to charter
  lib/engine/game/g_1822/step/tracker.rb
  lib/engine/game/g_1822_mx/step/track.rb
Labels: pins

#9498 [18Ardennes] Initial commit
  assets/app/view/game/round/auction.rb
  lib/engine/game/g_18_ardennes.rb
  lib/engine/game/g_18_ardennes/entities.rb
  lib/engine/game/g_18_ardennes/game.rb
  lib/engine/game/g_18_ardennes/map.rb
  lib/engine/game/g_18_ardennes/market.rb
  lib/engine/game/g_18_ardennes/meta.rb
  lib/engine/game/g_18_ardennes/step/home_hex_tile.rb
  lib/engine/game/g_18_ardennes/step/minor_auction.rb
  lib/engine/game/g_18_ardennes/tiles.rb
  lib/engine/game/g_18_ardennes/trains.rb
  public/logos/18_ardennes/1.svg
  public/logos/18_ardennes/10.svg
  public/logos/18_ardennes/11.svg
  public/logos/18_ardennes/12.svg
  public/logos/18_ardennes/13.svg
  public/logos/18_ardennes/14.svg
  public/logos/18_ardennes/15.svg
  public/logos/18_ardennes/2.svg
  public/logos/18_ardennes/3.svg
  public/logos/18_ardennes/4.svg
  public/logos/18_ardennes/5.svg
  public/logos/18_ardennes/6.svg
  public/logos/18_ardennes/7.svg
  public/logos/18_ardennes/8.svg
  public/logos/18_ardennes/9.svg
  public/logos/18_ardennes/BE.svg
  public/logos/18_ardennes/BY.svg
  public/logos/18_ardennes/E.svg
  public/logos/18_ardennes/N.svg
  public/logos/18_ardennes/NL.svg
  public/logos/18_ardennes/P.svg
Labels: new games, Core, 18Ardennes

#9504 1841: remove rounding on minor merger price
  lib/engine/game/g_1841/game.rb
Labels: archive_alpha_games

#9505 1849K2S - Remove hex N18
  lib/engine/game/g_1849_boot/map.rb
Labels: pins

#9512 [1822Africa] Only increase loans after SR x.2
  lib/engine/game/g_1822_africa/round/stock.rb
Labels: archive_alpha_games
