Repository tobymao/18xx, pull requests merged in 2023-05, with the labels that each got.

#9165 [1858] Don't check graph in Step::BuySellParShares.actions
  lib/engine/game/g_1858/step/buy_sell_par_shares.rb
  lib/engine/game/g_1858/step/private_exchange.rb
Labels: 1858

#9167 [1858] Use sticky icons for private railway home hexes
  lib/engine/game/g_1858/map.rb
  lib/engine/game/g_1858/step/track.rb
Labels: 1858

#9152 [1822, 1822MX] fix London/Mexico City stub/permission rules, [core] log when consent is needed and allow multiple consenters
  assets/app/view/game/acquire_companies.rb
  assets/app/view/game/actionable.rb
  assets/app/view/game/buy_company_from_other_player.rb
  assets/app/view/game/buy_trains.rb
  assets/app/view/game/buy_value_input.rb
  assets/app/view/game/issue_shares.rb
  assets/app/view/game/part/blocker.rb
  assets/app/view/game/round/merger.rb
  assets/app/view/game/round/stock.rb
  assets/app/view/game/tile_confirmation.rb
  lib/engine/ability/blocks_hexes.rb
  lib/engine/ability/blocks_hexes_consent.rb
  lib/engine/action/log.rb
  lib/engine/game/base.rb
  lib/engine/game/g_1822/entities.rb
  lib/engine/game/g_1822/game.rb
  lib/engine/game/g_1822/step/pending_token.rb
  lib/engine/game/g_1822_mx/entities.rb
  lib/engine/game/g_1822_mx/game.rb
  lib/engine/game/g_1822_mx/step/special_track.rb
  lib/engine/game/g_1822_mx/step/track.rb
  lib/engine/game/g_1825/game.rb
  lib/engine/game/g_1828/game.rb
  lib/engine/game/g_18_eu/game.rb
  lib/engine/game/g_18_gb/game.rb
  lib/engine/game/g_18_rhl/game.rb
  lib/engine/step/message.rb
  lib/engine/tile.rb
Labels: Core

#9168 [1817] Verify loans valid
  lib/engine/game/g_1817/game.rb
Labels: 1817, pins

#9164 [18MEX] set EBUY_OTHER_VALUE to false
  lib/engine/game/g_18_mex/game.rb
  lib/engine/step/buy_train.rb
Labels: pins

#9153 [1868WY] Fix DEV rounds being displayed incorrectly on spreadsheet
  lib/engine/player_info.rb
Labels: Core

#9138 Improve 1822 family destination information, allow hiding location name
  assets/app/view/game/tile.rb
  lib/engine/game/base.rb
  lib/engine/game/g_1822/game.rb
  lib/engine/game/g_1822_mx/map.rb
  lib/engine/hex.rb
Labels: Core

#9141 [1822 family, core] add `lay_count` and `upgrade_count` to `tile_lay` settings
  lib/engine/ability/README.md
  lib/engine/ability/base.rb
  lib/engine/ability/tile_lay.rb
  lib/engine/game/g_1822/entities.rb
  lib/engine/game/g_1822/step/special_track.rb
  lib/engine/game/g_1822_mx/entities.rb
  lib/engine/game/g_1822_mx/step/special_track.rb
  lib/engine/game/g_1822_pnw/entities.rb
  lib/engine/step/special_track.rb
  lib/engine/step/track_lay_when_company_sold.rb
Labels: pins, Core

#9156 update game.shares to utilize both corporation and player shares
  lib/engine/game/base.rb
Labels: Core

#9170 [1817] Handle loans internally, ignoring loan provided from view
  lib/engine/game/g_1817/game.rb
Labels: 1817, pins

#9169 [1822, 1822MRS] stop using P5 automatically for English Channel token
  lib/engine/ability/README.md
  lib/engine/ability/teleport.rb
  lib/engine/game/g_1822/entities.rb
  lib/engine/game/g_1822/game.rb
  lib/engine/game/g_1822/step/token.rb
  lib/engine/step/special_token.rb
  lib/engine/step/tokener.rb
  migrate_game.rb
  spec/fixtures/1822/36685.json
Labels: migration, pins

#9174 [core] allow icons and upgrades to have a `loc` set to specify rendering location, use for DTs in 1868WY
  TILES.md
  assets/app/view/game/part/base.rb
  assets/app/view/game/part/icons.rb
  assets/app/view/game/part/small_item.rb
  assets/app/view/game/part/upgrade.rb
  assets/app/view/game/part/upgrades.rb
  assets/app/view/game/tile.rb
  lib/engine/game/g_1868_wy/game.rb
  lib/engine/game/g_1868_wy/map.rb
  lib/engine/hex.rb
  lib/engine/part/base.rb
  lib/engine/part/icon.rb
  lib/engine/part/upgrade.rb
  lib/engine/tile.rb
Labels: tile rendering, Core

#9181 [1822] stop P8 ability from working with swamps
  lib/engine/game/g_1822/entities.rb
  lib/engine/game/g_1822/game.rb
  lib/engine/game/g_1822/step/special_track.rb
Labels: pins

#9182 [1822 family] set `must_lay_together` to true for "extra tile lay" privates
  lib/engine/game/g_1822/entities.rb
  lib/engine/game/g_1822/step/special_track.rb
  lib/engine/game/g_1822_mx/entities.rb
  lib/engine/game/g_1822_mx/step/special_track.rb
  lib/engine/game/g_1822_pnw/entities.rb
  lib/engine/game/g_1822_pnw/step/special_track.rb
  migrate_game.rb
Labels: migration, pins

#9190 fixes impassable edge 5 border on hex I21
  lib/engine/game/g_18_ny/map.rb
  lib/engine/game/g_18_ny_1e/map.rb
Labels: pins

#9194 1841 graph changes; track and token laying rules
  lib/engine/game/g_1841/entities.rb
  lib/engine/game/g_1841/game.rb
  lib/engine/game/g_1841/map.rb
  lib/engine/game/g_1841/step/track.rb
  lib/engine/graph.rb
Labels: 1841

#9196 [1822 family] Private company legal hex/tile/timing tweaks
  lib/engine/ability/README.md
  lib/engine/game/g_1822/entities.rb
  lib/engine/game/g_1822/game.rb
  lib/engine/game/g_1822/step/special_track.rb
  lib/engine/game/g_1822/step/token.rb
  lib/engine/game/g_1822/step/track.rb
  lib/engine/game/g_1822_mx/game.rb
  lib/engine/game/g_1822_pnw/game.rb
  public/fixtures/1822/35975.json
Labels: migration, pins

#9214 Rolling Stock: one more ipo fix
  lib/engine/game/g_rolling_stock/step/ipo_company.rb
Labels: RollingStock

#9193 Add a :future track type for paths
  assets/app/view/game/part/track.rb
  assets/app/view/game/tile.rb
  lib/engine/game/g_1840/map.rb
  lib/engine/game/g_1873/game.rb
  lib/engine/game/g_18_sj/map.rb
  lib/engine/tile.rb
Labels: 18SJ, Harzbahn 1873, map, 1840, Core

#9200 1841: corporation start operations (stock purchase, token placement, …
  lib/engine/game/g_1841/entities.rb
  lib/engine/game/g_1841/game.rb
  lib/engine/game/g_1841/map.rb
  lib/engine/game/g_1841/step/buy_sell_par_shares.rb
  lib/engine/game/g_1841/step/buy_tokens.rb
  lib/engine/game/g_1841/step/corp_start.rb
  lib/engine/game/g_1841/step/home_token.rb
Labels: 1841
