Repository tobymao/18xx, pull requests merged in 2023-11, with the labels that each got.

#9840 1822Africa - Remove sold out increase
  lib/engine/game/g_1822_africa/game.rb
  lib/engine/game/g_1822_africa/round/stock.rb
Labels: pins

#9865 [1850] fixes Western Land Grant closing, and typos
  lib/engine/game/g_1850/entities.rb
  lib/engine/game/g_1850/game.rb
  lib/engine/game/g_1850/step/track.rb
Labels: pins, 1850

#9883 [1888] Fix tile manifest in 1888
  lib/engine/game/g_1888/game.rb
  lib/engine/game/g_1888/map.rb
Labels: pins

#9918 [1844] Fixes payout on sales of unoperated corps
  lib/engine/game/g_1844/game.rb
Labels: pins

#9887 [1880] skip P5 assignment if corp already has D
  lib/engine/game/g_1880/step/assign.rb
Labels: pins, 1880

#9903 18 tokaido fix sort key issue
  lib/engine/game/g_18_tokaido/game.rb
Labels: bug, 18Tokaido

#9925 [1849] autopass tweak
  lib/engine/game/g_1849/step/buy_sell_par_shares.rb
Labels: pins

#9942 18zoo - Implements fixes asked inside https://github.com/tobymao/18xx/issues/9848
  lib/engine/game/g_18_zoo/entities.rb
  lib/engine/game/g_18_zoo/game.rb
  lib/engine/game/g_18_zoo/map.rb
  lib/engine/game/g_18_zoo/step/buy_sell_par_shares.rb
  public/fixtures/18ZOO - Map A/README.md
  public/fixtures/18ZOO - Map A/or_power.work_in_progress.can_be_ignored_by_wings_if_not_unique.json
  public/fixtures/18ZOO - Map A/sell_ticket_zoo_in_any_phase.json
  public/fixtures/18ZOO - Map C/5774.json
  public/fixtures/18ZOO - Map C/81965.json
  public/fixtures/18ZOO - Map D/README.md
  public/fixtures/18ZOO - Map D/not_president_selling_reduce_just_once.json
  public/fixtures/18ZOO - Map F/47334.json
  public/fixtures/18ZOO - Map F/6535.json
Labels: pins
