Repository tobymao/18xx, pull requests merged in 2023-04, with the labels that each got.

#8967 [1858] Private closure round implementation
  lib/engine/game/g_1858/game.rb
  lib/engine/game/g_1858/round/closure.rb
  lib/engine/game/g_1858/step/home_token.rb
  lib/engine/game/g_1858/step/private_closure.rb
  lib/engine/game/g_1858/step/private_exchange.rb
Labels: 1858

#9100 [18NY] Reworked rules for immediate capitalization round.
  lib/engine/game/g_18_ny/game.rb
  lib/engine/game/g_18_ny/step/special_capitalization.rb
Labels: pins, 18NY

#9096 [1858] Remove graph call from Step::Track.actions
  lib/engine/game/g_1858/step/track.rb
Labels: 1858

#9102 [1858] 5-share to 10-share corporation conversion
  lib/engine/game/g_1858/entities.rb
  lib/engine/game/g_1858/game.rb
  lib/engine/game/g_1858/step/buy_sell_par_shares.rb
  lib/engine/game/g_1858/trains.rb
Labels: 1858

#9107 "Starting Map" view: clone full game instead of calling `init_hexes`
  assets/app/view/game/map.rb
  lib/engine/game/g_1822/game.rb
  lib/engine/game/g_1850/game.rb
  lib/engine/game/g_1861/game.rb
  lib/engine/game/g_1867/game.rb
  lib/engine/game/g_1870/game.rb
  lib/engine/game/g_1894/game.rb
  lib/engine/game/g_18_fl/game.rb
  lib/engine/game/g_18_jpt/game.rb
  lib/engine/game/g_18_los_angeles/game.rb
Labels: Core

#9104 Raise an error if the tile being laid (or its opposite) is already on the board
  lib/engine/game/base.rb
  lib/engine/game/double_sided_tiles.rb
Labels: Core

#9114 Fix displayed stock price movement at end of market
  assets/app/view/game/dividend.rb
Labels: Core

#9115 [1822 family] fix acquiring special trains, clean up train discarding
  lib/engine/game/g_1822/game.rb
  lib/engine/game/g_1822/step/discard_train.rb
  lib/engine/game/g_1822_mx/game.rb
  lib/engine/game/g_1822_mx/step/discard_train.rb
Labels: pins

#9108 [1867] don't allow a Major with no valid home to start; fix Toronto/Montreal starts
  lib/engine/game/g_1867/game.rb
  lib/engine/game/g_1867/step/buy_sell_par_shares.rb
Labels: pins

#9118 [1822 family] Fix MUST_SELL_IN_BLOCKS for 1D market games
  lib/engine/game/g_1822_ca/game.rb
  lib/engine/game/g_1822_mx/game.rb
  lib/engine/game/g_1822_pnw/game.rb
Labels: pins

#9121 [1822MX] don't allow bidding on NdeM token for a Major with token on same hex
  lib/engine/game/g_1822_mx/step/auction_ndem_tokens.rb
Labels: pins

#9124 [1846] Fix Steamboat Company timing, let abilities do `when: route`
  lib/engine/ability/README.md
  lib/engine/game/base.rb
  lib/engine/game/g_1846/entities.rb
  migrate_game.rb
  spec/fixtures/1846/19962.json
  spec/fixtures/1846/hs_gcumggit_1595777670.json
  spec/game_state_spec.rb
Labels: pins, Core

#9136 [18NY] Change Text for Forced Salvage of Trains Over Limit on Phase Change
  assets/app/view/game/discard_trains.rb
  lib/engine/game/g_18_ny/game.rb
  lib/engine/game/g_18_ny/step/discard_train.rb
Labels: Core

#9123 [1858] Alternate view for minors
  assets/app/view/game/alternate_corporations.rb
  lib/engine/game/g_1858/game.rb
Labels: 1858, Core

#9148 Fix issue 8862
  lib/engine/game/g_1867/game.rb
Labels: 1867, 1861

#9146 Call City.remove_reservation from Ability::Reservation.teardown
  lib/engine/ability/reservation.rb
  spec/lib/engine/round/operating_spec.rb
Labels: 1858, Core

#9150 [1848] Shouldn't be able to buy a train from supply after buying from corporation
  lib/engine/game/g_1848/step/buy_train.rb
Labels: pins, 1848
