Repository tobymao/18xx, pull requests merged in 2024-06, with the labels that each got.

#10752 [18Norway] Adding harbor
  lib/engine/game/base.rb
  lib/engine/game/g_18_norway/corporations.rb
  lib/engine/game/g_18_norway/game.rb
  lib/engine/game/g_18_norway/map.rb
  lib/engine/game/g_18_norway/steps/route.rb
  lib/engine/game/g_18_norway/steps/token.rb
  lib/engine/graph.rb
Labels: new games, 18Norway

#10830 [1832][prealpha] mask unstarted systems during stock rounds
  lib/engine/game/g_1832/entities.rb
  lib/engine/game/g_1832/game.rb
  lib/engine/game/g_1832/step/buy_sell_par_shares.rb
Labels: new games, 1832

#10833 [18Mag] changes CIWL bonus from subsidy to revenue
  lib/engine/game/g_18_mag/game.rb
Labels: pins, 18Mag

#10839 [1866] Palace Car shouldn't work with E-trains
  lib/engine/game/g_1866/game.rb
Labels: pins, 1866

#10843 [1894] Fix teleport bug
  lib/engine/game/g_1894/entities.rb
Labels: pins, 1894

#10844 [1822PNW] prevent brown town tiles from upgrading to the Boom Town tile
  lib/engine/game/g_1822_pnw/game.rb
Labels: pins

#10859 [1822PNW] create placeholder company to occupy empty bid boxes
  lib/engine/game/g_1822_pnw/game.rb
  lib/engine/game/g_1822_pnw/round/stock.rb
Labels: pins

#10860 [18RoyalGorge] mark gold icons as not preprinted
  lib/engine/game/g_18_royal_gorge/game.rb
Labels: pins

#10861 [1822PNW] stock market endgame takes precedence over bank breaking
  lib/engine/game/g_1822_pnw/game.rb
Labels: pins

#10866 [1822PNW] P20 - update home/dest on major's card, fix dest changing cases
  lib/engine/game/g_1822_pnw/game.rb
  lib/engine/game/g_1822_pnw/step/acquire_company.rb
  lib/engine/operator.rb
Labels: pins

#10840 [18RoyalGorge] bug fixes for DEBT and US Mint Worker (B6)
  assets/app/view/game/button/buy_share.rb
  lib/engine/game/g_18_royal_gorge/game.rb
  lib/engine/game/g_18_royal_gorge/step/buy_sell_par_shares.rb
Labels: archive_alpha_games

#10841 [core] fix being stuck on entity without valid actions after closing corporations
  lib/engine/game/base.rb
  lib/engine/round/base.rb
  public/fixtures/1846/README.md
  public/fixtures/1846/hs_wwhjwjvo_1716866882.json
Labels: Core

#10871 [1841] color-coding the concessions
  lib/engine/game/g_1841/entities.rb
Labels: enhancement, game UI, 1841

#10885 [18RoyalGorge] Fix B2 Sulphur Springs's revenue increasing before brown
  lib/engine/game/g_18_royal_gorge/game.rb
Labels: pins

#10869 [Core] Minor's abilities can be used in stock round
  lib/engine/game/base.rb
Labels: Core

#10893 [1822 family] show winning bids in the player card's cert count; fix 1822CA tax haven
  assets/app/view/game/player.rb
  lib/engine/game/g_1822/game.rb
  lib/engine/game/g_1822/step/buy_sell_par_shares.rb
  lib/engine/game/g_1822_ca/game.rb
Labels: pins

#10883 [1870] implements Station Wars rulebook variant
  lib/engine/game/g_1870/game.rb
  lib/engine/game/g_1870/meta.rb
  lib/engine/game/g_1870/step/connection_token.rb
Labels: 1870

#10889 Enforce a train's availability when buying it
  lib/engine/step/train.rb
  public/fixtures/1880/1.json
  public/fixtures/18EU/74045.json
  public/fixtures/18Ireland/161830.json
  public/fixtures/18Ireland/39547.json
  public/fixtures/18Ireland/hs_ljvktyhv_38235.json
  public/fixtures/18Ireland/larger_bank_optional_rule.json
  spec/lib/engine/round/operating_spec.rb
Labels: pins, Core

#10907 [1822MX] include NdeM shares in liquidity calculation
  lib/engine/game/base.rb
  lib/engine/game/g_1822_mx/step/buy_sell_par_shares.rb
  lib/engine/game/g_1841/game.rb
  spec/assets_spec.rb
Labels: 1841, 1822MX, Core

#10924 [18RoyalGorge] fix endgame, add some small enhancements
  lib/engine/game/g_18_royal_gorge/entities.rb
  lib/engine/game/g_18_royal_gorge/game.rb
  lib/engine/game/g_18_royal_gorge/trains.rb
  public/fixtures/18RoyalGorge/post_boston.json
Labels: archive_alpha_games

#10911 [1822 family] Allow auto-routing to run L-trains in different cities
  lib/engine/auto_router.rb
  lib/engine/game/g_1822/game.rb
Labels: autorouting

#10936 [Core/1822MX] Simplify base implementation of Game.can_dump?
  lib/engine/game/base.rb
  lib/engine/game/g_1822_mx/game.rb
Labels: 1822MX, Core

#10929 [Autorouting] create groups of different trains for autorouting
  lib/engine/auto_router.rb
  lib/engine/game/base.rb
  lib/engine/game/g_1822/game.rb
  lib/engine/game/g_18_los_angeles/game.rb
Labels: 18 Los Angeles, 1822, autorouting

#10927 [1822PNW] prevent other tile lays from being made after portage
  lib/engine/game/g_1822_pnw/step/special_track.rb
Labels: pins

#10925 [1822MX] pass `same_hex_allowed: true` for the home token
  lib/engine/game/base.rb
  lib/engine/game/g_1822_mx/game.rb
  public/fixtures/1822MX/home_and_ndem_auctioned_token_in_mexico_city.json
Labels: pins

#10942 [1822Africa] fix step and tiles for P12
  lib/engine/game/g_1822_africa/entities.rb
Labels: pins

#10986 [1822PNW Short] fix floating the paired minor in bidbox 1
  lib/engine/game/g_1822_pnw_short/game.rb
  lib/engine/game/g_1822_pnw_short/meta.rb
  lib/engine/game/g_1822_pnw_short/round/stock.rb
  lib/engine/game/g_1822_pnw_srs/meta.rb
Labels: archive_alpha_games

#10984 [1847 AE] Fix the train limit in yellow phase
  lib/engine/game/g_1847_ae/game.rb
Labels: pins

#10962 1841: deal with discard in bank on forced purchase
  lib/engine/game/g_1841/step/buy_train.rb
Labels: pins

#10979 [Core] Rotate stripes on tiles for games with a :flat layout
  assets/app/view/game/hex.rb
Labels: tile rendering, Core

#10982 [1850] must buy from depot if pres contributes
  lib/engine/game/g_1850/game.rb
Labels: archive_alpha_games, 1850
