Repository tobymao/18xx, pull requests merged in 2024-07, with the labels that each got.

#11000 [1822PNW scenarios] fix M21 in SRS, fix P+ trains
  lib/engine/game/g_1822_pnw_short/game.rb
  lib/engine/game/g_1822_pnw_short/trains.rb
  lib/engine/game/g_1822_pnw_srs/game.rb
  lib/engine/game/g_1822_pnw_srs/trains.rb
Labels: archive_alpha_games

#11002 [1826] entities tweaks
  lib/engine/game/g_1826/entities.rb
  lib/engine/game/g_1826/game.rb
  lib/engine/game/g_1826/step/buy_train.rb
Labels: new games, 1826

#11008 S18: UK map updates
  assets/app/view/game/part/city_slot.rb
  lib/engine/game/g_system18/game.rb
  lib/engine/game/g_system18/map_uk_limited_customization.rb
  lib/engine/game/g_system18/uk_depot.rb
  lib/engine/part/city.rb
  lib/engine/tile.rb
Labels: archive_alpha_games

#11009 [1822CA/core] add `same_hex_allowed` to token abilities, use for P10
  lib/engine/ability/README.md
  lib/engine/ability/token.rb
  lib/engine/game/base.rb
  lib/engine/game/g_1822_ca/entities.rb
  lib/engine/game/g_1822_ca/step/special_token.rb
Labels: pins

#11019 [18Ardennes] Various fixes
  lib/engine/game/g_18_ardennes/entities.rb
  lib/engine/game/g_18_ardennes/game.rb
  lib/engine/game/g_18_ardennes/step/buy_sell_par_shares_companies.rb
  lib/engine/game/g_18_ardennes/step/buy_train.rb
  lib/engine/game/g_18_ardennes/step/minor_exchange.rb
  lib/engine/game/g_18_ardennes/step/post_conversion_shares.rb
  lib/engine/game/g_18_ardennes/step/track.rb
Labels: 18Ardennes

#11029 [1830] implements private company cross-buys
  lib/engine/game/g_1830/game.rb
  lib/engine/game/g_1830/step/buy_sell_par_shares.rb
Labels: pins

#11033 show number of titles matching keyword search on create game page
  assets/app/view/create_game.rb
Labels: front page

#10941 [1888-E] Added map
  lib/engine/game/g_1888/entities.rb
  lib/engine/game/g_1888/game.rb
  lib/engine/game/g_1888/map.rb
  lib/engine/game/g_1888/meta.rb
  public/icons/1888/HEN_dest.svg
  public/icons/1888/HHR_dest.svg
  public/icons/1888/HUN_dest.svg
  public/icons/1888/LHR_dest.svg
  public/icons/1888/WJR_dest.svg
  public/icons/1888/XGY_dest.svg
  public/icons/1888/XYR_dest.svg
  public/icons/1888/YTR_dest.svg
  public/logos/1888/HEN.alt.svg
  public/logos/1888/HEN.svg
  public/logos/1888/HHR.alt.svg
  public/logos/1888/HHR.svg
  public/logos/1888/HUN.alt.svg
  public/logos/1888/HUN.svg
  public/logos/1888/LHR.alt.svg
  public/logos/1888/LHR.svg
  public/logos/1888/WJR.alt.svg
  public/logos/1888/WJR.svg
  public/logos/1888/XGY.alt.svg
  public/logos/1888/XGY.svg
  public/logos/1888/XYR.alt.svg
  public/logos/1888/XYR.svg
  public/logos/1888/YTR.alt.svg
  public/logos/1888/YTR.svg
Labels: 1888

#11035 [18 India] Bug Fixes and Prepare for Alpha
  assets/app/view/game/hidden_hand.rb
  assets/app/view/game/ipo_rows.rb
  assets/app/view/game/round/stock.rb
  lib/engine/game/g_18_india/game.rb
  lib/engine/game/g_18_india/meta.rb
  lib/engine/game/g_18_india/player.rb
  lib/engine/game/g_18_india/step/corporate_buy_shares_company.rb
  lib/engine/game/g_18_india/step/draft.rb
  lib/engine/game/g_18_india/step/route.rb
  public/fixtures/18India/india-hs-fullgame.json
Labels: new games, Core, 18India

#11016 1870 original rules (as optional rules)
  lib/engine/game/g_1870/game.rb
  lib/engine/game/g_1870/meta.rb
  lib/engine/game/g_1870/step/buy_sell_par_shares.rb
  lib/engine/game/g_1870/step/price_protection.rb
Labels: 1870, optional rules
