Repository tobymao/18xx, pull requests merged in 2024-08, with the labels that each got.

#11086 [18GB] Add blocked hexes to private descriptions
  lib/engine/game/g_18_gb/entities.rb
Labels: 18GB

#11090 [18 India] Fix Gauge Change with Mumbai/Nepal bug and Director's Share Price Paid bug
  lib/engine/game/g_18_india/corporation.rb
  lib/engine/game/g_18_india/game.rb
  lib/engine/game/g_18_india/map.rb
  lib/engine/game/g_18_india/step/home_track.rb
  public/fixtures/18India/india-hs-fullgame.json
Labels: archive_alpha_games, 18India

#11085 [18 India] Fix OO reservation relocate bug
  lib/engine/game/g_18_india/step/home_track.rb
Labels: 18India

#11084 [18SJ] Set in production
  assets/app/view/welcome.rb
  lib/engine/game/g_18_sj/meta.rb
  public/fixtures/18SJ/166116.json
  public/fixtures/18SJ/167041.json
Labels: 18SJ

#11059 [18India] add wiki link
  lib/engine/game/g_18_india/meta.rb
Labels: 18India

#11070 [1846] optional rules are XOR
  lib/engine/game/g_1846/meta.rb
Labels: 1846

#11061 [18 Hiawatha] adds fixture files
  public/fixtures/18 Hiawatha/164543.json
  public/fixtures/18 Hiawatha/164606.json
Labels: 18Hiawatha

#11052 [22Mars] Add entities and basic game rules
  lib/engine/game/g_22_mars/company.rb
  lib/engine/game/g_22_mars/entities.rb
  lib/engine/game/g_22_mars/game.rb
  lib/engine/game/g_22_mars/map.rb
  lib/engine/game/g_22_mars/step/dividend.rb
  public/logos/22Mars/IG.svg
  public/logos/22Mars/MS.svg
  public/logos/22Mars/NWC.svg
  public/logos/22Mars/PL.svg
  public/logos/22Mars/REX.svg
  public/logos/22Mars/SMC.svg
  public/logos/22Mars/SRC.svg
  public/logos/22Mars/TRE.svg
Labels: new games, 22Mars

#11069 Fix issue checking playercount
  assets/app/view/create_game.rb
Labels: front page

#11075 [18Ardennes] Bankruptcy
  lib/engine/game/g_18_ardennes/entities.rb
  lib/engine/game/g_18_ardennes/game.rb
  lib/engine/game/g_18_ardennes/step/bankrupt.rb
  lib/engine/game/g_18_ardennes/step/buy_sell_par_shares_companies.rb
  lib/engine/game/g_18_ardennes/step/buy_train.rb
  lib/engine/game/g_18_ardennes/step/convert.rb
  lib/engine/game/g_18_ardennes/step/dividend.rb
  lib/engine/game/g_18_ardennes/step/route.rb
  lib/engine/game/g_18_ardennes/step/token.rb
  lib/engine/game/g_18_ardennes/step/track.rb
Labels: new games, 18Ardennes

#10737 [1849] Implements the official variants from the rulebook
  assets/app/view/game/corporation.rb
  assets/app/view/game/loans.rb
  lib/engine/game/base.rb
  lib/engine/game/g_1849/depot.rb
  lib/engine/game/g_1849/game.rb
  lib/engine/game/g_1849/meta.rb
  lib/engine/game/g_1849/step/bond.rb
  lib/engine/game/g_1849/step/bond_interest_payment.rb
  lib/engine/game/g_1849/step/buy_e_token.rb
  lib/engine/game/g_1849/step/buy_token.rb
  lib/engine/game/g_1849/step/buy_train.rb
  lib/engine/game/g_1849/step/emergency_money_raising.rb
  lib/engine/game/g_1849_boot/game.rb
Labels: 1849

#11065 [SteamOverHolland] final fixes - EMR, share issuing. Move to Alpha.
  assets/app/view/game/buy_trains.rb
  assets/app/view/game/player.rb
  assets/app/view/welcome.rb
  lib/engine/game/base.rb
  lib/engine/game/g_steam_over_holland/entities.rb
  lib/engine/game/g_steam_over_holland/game.rb
  lib/engine/game/g_steam_over_holland/map.rb
  lib/engine/game/g_steam_over_holland/meta.rb
  lib/engine/game/g_steam_over_holland/round/operating.rb
  lib/engine/game/g_steam_over_holland/step/buy_sell_par_shares.rb
  lib/engine/game/g_steam_over_holland/step/buy_train.rb
  lib/engine/game/g_steam_over_holland/step/issue_shares.rb
  lib/engine/game/g_steam_over_holland/step/selection_auction.rb
  lib/engine/game/g_steam_over_holland/step/track.rb
  public/fixtures/Steam Over Holland/steam_over_holland_fixture_1.json
Labels: new games, Core, Steam Over Holland

#11120 [1849] Forces games with Electric Dreams variant to also use Bonds and Acquiring Tokens
  lib/engine/game/g_1849/meta.rb
  lib/engine/game/g_1849/step/bond.rb
  lib/engine/game/g_1849/step/buy_token.rb
Labels: 1849, pins

#11167 [System18] corrects price change when emr issuing
  lib/engine/game/g_system18/step/buy_train.rb
Labels: archive_alpha_games

#11177 [1861] Move Perm location name to the correct hex
  lib/engine/game/g_1861/map.rb
Labels: 1861

#11106 [1826] sets capitalization, train buy rules, tile lays, quantity of tokens
  lib/engine/game/g_1826/entities.rb
  lib/engine/game/g_1826/game.rb
Labels: new games, 1826

#11134 [18 India] Add Commodity Destination Table Below Map
  assets/app/view/game/part/large_icons.rb
  lib/engine/game/g_18_india/game.rb
  lib/engine/game/g_18_india/map.rb
  public/icons/18_india/cotton-40.svg
  public/icons/18_india/gold-50.svg
  public/icons/18_india/oil-30.svg
  public/icons/18_india/opium-100.svg
  public/icons/18_india/ore-50.svg
  public/icons/18_india/rice-30.svg
  public/icons/18_india/spices-30.svg
  public/icons/18_india/spices-40.svg
  public/icons/18_india/spices-50.svg
  public/icons/18_india/spices-70.svg
  public/icons/18_india/tea-70.svg
Labels: tile rendering, Core, 18India

#11119 [1858Switzerland] Add entities, map, tiles, icons and logos
  lib/engine/game/g_1858_switzerland.rb
  lib/engine/game/g_1858_switzerland/entities.rb
  lib/engine/game/g_1858_switzerland/game.rb
  lib/engine/game/g_1858_switzerland/map.rb
  lib/engine/game/g_1858_switzerland/meta.rb
  lib/engine/game/g_1858_switzerland/tiles.rb
  public/icons/1858_switzerland/AFAI.svg
  public/icons/1858_switzerland/BB.svg
  public/icons/1858_switzerland/BLB.svg
  public/icons/1858_switzerland/BSB.svg
  public/icons/1858_switzerland/ChA.svg
  public/icons/1858_switzerland/EB.svg
  public/icons/1858_switzerland/FOB.svg
  public/icons/1858_switzerland/GB.svg
  public/icons/1858_switzerland/JN.svg
  public/icons/1858_switzerland/L.svg
  public/icons/1858_switzerland/LFB.svg
  public/icons/1858_switzerland/NB.svg
  public/icons/1858_switzerland/NOB.svg
  public/icons/1858_switzerland/OS.svg
  public/icons/1858_switzerland/S.svg
  public/icons/1858_switzerland/SCB.svg
  public/icons/1858_switzerland/VSB.svg
  public/icons/1858_switzerland/VZ.svg
  public/icons/1858_switzerland/east.svg
  public/icons/1858_switzerland/mountain.svg
  public/icons/1858_switzerland/north.svg
  public/icons/1858_switzerland/south.svg
  public/icons/1858_switzerland/west.svg
  public/logos/1858_switzerland/AB.svg
  public/logos/1858_switzerland/AFAI.svg
  public/logos/1858_switzerland/BB.svg
  public/logos/1858_switzerland/BLB.svg
  public/logos/1858_switzerland/BLS.svg
  public/logos/1858_switzerland/BSB.svg
  public/logos/1858_switzerland/ChA.svg
  public/logos/1858_switzerland/EB.svg
  public/logos/1858_switzerland/FOB.svg
  public/logos/1858_switzerland/GB.svg
  public/logos/1858_switzerland/JN.svg
  public/logos/1858_switzerland/L.svg
  public/logos/1858_switzerland/LFB.svg
  public/logos/1858_switzerland/MOB.svg
  public/logos/1858_switzerland/NB.svg
  public/logos/1858_switzerland/NOB.svg
  public/logos/1858_switzerland/OS.svg
  public/logos/1858_switzerland/RhB.svg
  public/logos/1858_switzerland/S.svg
  public/logos/1858_switzerland/SCB.svg
  public/logos/1858_switzerland/STB.svg
  public/logos/1858_switzerland/VSB.svg
  public/logos/1858_switzerland/VZ.svg
Labels: new games, 1858Switzerland

#11142 [18Ardennes] Last corner case rules
  lib/engine/game/g_18_ardennes/step/buy_sell_par_shares_companies.rb
  lib/engine/game/g_18_ardennes/step/dividend.rb
  lib/engine/game/g_18_ardennes/step/exchange.rb
Labels: new games, 18Ardennes

#11143 [18Ardennes] Move to alpha release status
  assets/app/view/welcome.rb
  lib/engine/game/g_18_ardennes/meta.rb
Labels: new games, 18Ardennes

#11112 [18uruguay] various fixes
  lib/engine/game/g_18_uruguay/companies.rb
  lib/engine/game/g_18_uruguay/corporations.rb
  lib/engine/game/g_18_uruguay/game.rb
  lib/engine/game/g_18_uruguay/trains.rb
Labels: archive_alpha_games, 18Uruguay
