Repository tobymao/18xx, pull requests merged in 2024-02, with the labels that each got.

#10220 21Moon: must sell in blocks; fix terminal bonus
  lib/engine/game/g_21_moon/game.rb
Labels: pins

#10231 [21Moon] fixes E-W bonus
  lib/engine/game/g_21_moon/game.rb
Labels: pins, 21Moon

#10219 [18MS] fix Mobile & Ohio's train discount ability
  lib/engine/game/g_18_ms/entities.rb
Labels: pins

#10228 [1856] Move stock marker up if sold out in SR1
  lib/engine/game/g_1856/round/stock.rb
  public/fixtures/1856/README.md
  public/fixtures/1856/hotseat001.json
  public/fixtures/1856/hotseat004.json
  public/fixtures/1856/move_up_price_sr1.json
Labels: pins, 1856

#10254 21Moon: rules updates
  lib/engine/game/g_21_moon/entities.rb
  lib/engine/game/g_21_moon/game.rb
  lib/engine/game/g_21_moon/map.rb
  lib/engine/game/g_21_moon/step/ols_track.rb
  lib/engine/game/g_21_moon/step/track.rb
  public/fixtures/21Moon/148096.json
Labels: pins

#10278 [1858] madrid can't be used twice in same route
  lib/engine/game/g_1858/map.rb
Labels: pins

#10279 [All][18EU] Check whether over limit holdings can actually be sold in `must_sell?`
  lib/engine/game/g_18_eu/corporation.rb
  lib/engine/game/g_18_eu/game.rb
  lib/engine/step/buy_sell_par_shares.rb
  public/fixtures/18EU/prohibit_buy_over_60.json
  spec/lib/engine/games/g_18eu_spec.rb
Labels: 18EU, pins

#10288 [1894] Change 5T and the market
  lib/engine/game/g_1894/game.rb
  lib/engine/game/g_1894/map.rb
Labels: pins

#10308 [1868WY] fix Big Boy token interactions with double-heading trains
  lib/engine/game/g_1868_wy/game.rb
  lib/engine/game/g_1868_wy/step/choose_big_boy.rb
  lib/engine/game/g_1868_wy/step/dividend.rb
  lib/engine/game/g_1868_wy/step/double_head_trains.rb
  lib/engine/game/g_1868_wy/step/stock_round_action.rb
  public/fixtures/1868 Wyoming/144719.json
  public/fixtures/1868 Wyoming/1868WY_5.json
  spec/assets_spec.rb
  spec/game_state_spec.rb
Labels: pins

#10328 [1822CA] disallow sawmill in Y-cities, fix currency symbol on info page
  lib/engine/game/g_1822_ca/entities.rb
  lib/engine/game/g_1822_ca/game.rb
Labels: archive_alpha_games

#10332 [18SJ] Fixes bank pool dividends in Oscarian Era variant
  lib/engine/game/g_18_sj/step/dividend.rb
Labels: pins

#10330 Add in region weight debugging information when 'grid' URL parameter is used
  assets/app/view/game/part/debug_region_weights.rb
  assets/app/view/game/part/region_coordinates.rb
  assets/app/view/game/tile.rb
Labels: tile rendering

#10337 [1836Jr56] Fix wrong number of arguments into hexes_connected?
  lib/engine/game/g_1836_jr56/game.rb
  spec/lib/engine/games/g_1836jr56_spec.rb
Labels: 1836jr56

#10354 [1893] Fix exclusion of merge voter for share-only owner
  lib/engine/game/g_1893/step/merger.rb
Labels: 1893

#10355 [18SJ] Fix issue with Adelswärd selection of corporation
  lib/engine/game/g_18_sj/game.rb
Labels: 18SJ

#10348 [1873] Make colors controlled by settings for mine displays
  assets/app/view/game/alternate_corporations.rb
Labels: Harzbahn 1873, game UI

#10361 [1824] Corrections for train handling
  lib/engine/game/g_1824/game.rb
  lib/engine/game/g_1824/trains.rb
Labels: 1824

#10376 [1822CA] fix P21 (3 Tile Grant) being able to lay green tiles
  lib/engine/game/g_1822_ca/entities.rb
  public/fixtures/1822CA/3.json
Labels: archive_alpha_games

#10386 System18: NEUS map and playtest fixes; Franch map tile renumbering
  lib/engine/game/g_system18/map_france_customization.rb
  lib/engine/game/g_system18/map_neus_customization.rb
Labels: archive_alpha_games

#10391 [18SJ] fix P7 (Nydqvist och Holm AB) power
  lib/engine/game/g_18_sj/entities.rb
Labels: 18SJ

#10393 [1854] Add map and tiles
  .github/CODEOWNERS
  lib/engine/game/g_1854/map.rb
  lib/engine/game/g_1854/tiles.rb
Labels: 1854

#10408 [1854] Add in all icons and logos
  public/icons/1854/1.svg
  public/icons/1854/2.svg
  public/icons/1854/3.svg
  public/icons/1854/4.svg
  public/icons/1854/5.svg
  public/icons/1854/6.svg
  public/icons/1854/B1.svg
  public/icons/1854/B2.svg
  public/icons/1854/B3.svg
  public/icons/1854/B4.svg
  public/icons/1854/B5.svg
  public/icons/1854/T1.svg
  public/icons/1854/T2.svg
  public/icons/1854/T3.svg
  public/icons/1854/T4.svg
  public/icons/1854/T5.svg
  public/icons/1854/bonus_30.svg
  public/icons/1854/bonus_40.svg
  public/icons/1854/bonus_50.svg
  public/icons/1854/bonus_90.svg
  public/icons/1854/mine.svg
  public/icons/1854/minus_ten.svg
  public/logos/1854/1.svg
  public/logos/1854/2.svg
  public/logos/1854/3.svg
  public/logos/1854/4.svg
  public/logos/1854/5.svg
  public/logos/1854/6.svg
  public/logos/1854/A.svg
  public/logos/1854/B.svg
  public/logos/1854/C.svg
  public/logos/1854/FJ.svg
  public/logos/1854/KB.svg
  public/logos/1854/KE.svg
  public/logos/1854/KR.svg
  public/logos/1854/KT.svg
  public/logos/1854/NT.svg
  public/logos/1854/SB.svg
  public/logos/1854/SD.svg
  public/logos/1854/VB.svg
Labels: 1854
