Repository tobymao/18xx, pull requests merged in 2024-04, with the labels that each got.

#10594 [18NL] code cleanup (replaces 'magic string' with constant) & pushes game to Production
  lib/engine/game/g_18_nl/game.rb
  lib/engine/game/g_18_nl/meta.rb
  lib/engine/game/g_18_nl/step/track.rb
Labels: 18NL

#10577 [18Neb] t'aint no train discounts
  lib/engine/game/g_18_neb/game.rb
Labels: 18Neb

#10569 Prevent spurious exchange buttons appearing in stock round
  assets/app/view/game/buy_sell_shares.rb
  lib/engine/game/base.rb
  lib/engine/game/g_18_ardennes/entities.rb
Labels: 1871, 1858, Core, 18Ardennes

#10575 [18Uruguay] Only auto withhold when nationalized
  lib/engine/game/g_18_uruguay/step/dividend.rb
Labels: new games, 18Uruguay

#10574 [18Uruguay] Adding new graphics
  lib/engine/game/g_18_uruguay/game.rb
  lib/engine/game/g_18_uruguay/map.rb
  public/icons/18_uruguay/corn.svg
  public/icons/18_uruguay/cow.svg
  public/icons/18_uruguay/sheep.svg
Labels: new games, 18Uruguay

#10538 [1822PNW] Fix typo in tile name
  lib/engine/game/g_1822_pnw/map.rb
Labels: 1822PNW

#10530 [18Ardennes] Converting five-share corporations to ten-share corporations
  lib/engine/game/g_18_ardennes/entities.rb
  lib/engine/game/g_18_ardennes/game.rb
  lib/engine/game/g_18_ardennes/market.rb
  lib/engine/game/g_18_ardennes/step/buy_sell_par_shares_companies.rb
  lib/engine/game/g_18_ardennes/step/convert.rb
  lib/engine/game/g_18_ardennes/step/decline_trains.rb
  lib/engine/game/g_18_ardennes/step/exchange.rb
  lib/engine/game/g_18_ardennes/step/major_auction.rb
  lib/engine/game/g_18_ardennes/step/minor_exchange.rb
  lib/engine/game/g_18_ardennes/step/post_conversion_shares.rb
Labels: new games, 18Ardennes

#10532 [18 India] Implement Private Company Abilities
  lib/engine/game/base.rb
  lib/engine/game/g_18_india/entities.rb
  lib/engine/game/g_18_india/game.rb
  lib/engine/game/g_18_india/step/assign.rb
  lib/engine/game/g_18_india/step/sell_once_then_buy_certs.rb
  lib/engine/game/g_18_india/step/special_choose.rb
  lib/engine/game/g_18_india/step/special_track.rb
  lib/engine/game/g_18_india/step/token.rb
  lib/engine/game/g_18_india/step/track.rb
  lib/engine/step/assign.rb
  lib/engine/step/special_buy_train.rb
  lib/engine/step/special_token.rb
  lib/engine/step/special_track.rb
Labels: new games, 18India

#10589 [18Ardennes] 4D trains
  lib/engine/game/g_18_ardennes/trains.rb
Labels: new games, 18Ardennes

#10605 [1848] fix train export on 2nd/5th receivership
  lib/engine/game/g_1848/depot.rb
  lib/engine/game/g_1848/game.rb
  public/fixtures/1848/101.json
  spec/game_state_spec.rb
Labels: pins, 1848

#10625 [18Neb] Bug fixes
  lib/engine/game/g_18_neb/depot.rb
  lib/engine/game/g_18_neb/game.rb
  lib/engine/game/g_18_neb/step/buy_sell_par_shares.rb
  lib/engine/game/g_18_neb/step/exchange.rb
  lib/engine/game/g_18_neb/step/legal_tile_rotation_checker.rb
  lib/engine/game/g_18_neb/step/special_track.rb
  lib/engine/game/g_18_neb/step/track.rb
Labels: archive_alpha_games, 18Neb

#10587 [18esp] more 18esp fixes
  lib/engine/game/g_18_esp/entities.rb
  lib/engine/game/g_18_esp/game.rb
  lib/engine/game/g_18_esp/map.rb
  lib/engine/game/g_18_esp/step/acquire.rb
  lib/engine/game/g_18_esp/step/buy_train.rb
  public/icons/18_esp/TBF.svg
Labels: 18ESP

#10647 [SteamOverHolland] bundle buy shares when parring
  lib/engine/game/g_steam_over_holland/game.rb
  lib/engine/game/g_steam_over_holland/step/buy_sell_par_shares.rb
Labels: new games, Steam Over Holland

#10553 [21Moon] allow Terminal to optionally place token
  lib/engine/game/g_21_moon/game.rb
  lib/engine/game/g_21_moon/step/special_token.rb
  lib/engine/game/g_21_moon/step/special_track.rb
Labels: pins, 21Moon, hold-merge

#10561 [21Moon] Terminal private revenue s.b. 15 space bucks
  lib/engine/game/g_21_moon/entities.rb
Labels: pins, 21Moon, hold-merge

#10562 [21Moon] fix terminal hex placement
  lib/engine/game/g_21_moon/entities.rb
  lib/engine/game/g_21_moon/game.rb
Labels: pins, 21Moon, hold-merge

#10585 21Moon: fix space port upgrade broken by tile renumbering
  lib/engine/game/g_21_moon/game.rb
Labels: 21Moon

#10656 [Steam Over Holland] cannot lay a token in corps first operating turn
  lib/engine/game/g_steam_over_holland/game.rb
  lib/engine/game/g_steam_over_holland/step/token.rb
Labels: new games, Steam Over Holland

#10658 [18 Hiawatha] apparently this title has a space in its name
  lib/engine/game/g_18_hiawatha/meta.rb
Labels: 18 hiawatha

#10661 [18 Hiawatha] change the description of a couple of market spaces
  lib/engine/game/g_18_hiawatha/game.rb
Labels: 18Hiawatha

#10580 [18Uruguay] No RLPTA stock before phase 3
  lib/engine/game/g_18_uruguay/game.rb
  lib/engine/game/g_18_uruguay/phases.rb
  lib/engine/game/g_18_uruguay/step/buy_sell_par_shares.rb
Labels: new games, 18Uruguay

#10682 [Core] Fix lane connections with 4 lanes per hex edge
  assets/app/view/game/part/track_node_path.rb
  lib/engine/part/path.rb
Labels: Core

#10591 [18Norway] Base entities
  lib/engine/game/g_18_norway.rb
  lib/engine/game/g_18_norway/companies.rb
  lib/engine/game/g_18_norway/corporations.rb
  lib/engine/game/g_18_norway/game.rb
  lib/engine/game/g_18_norway/map.rb
  lib/engine/game/g_18_norway/meta.rb
  lib/engine/game/g_18_norway/phases.rb
  lib/engine/game/g_18_norway/trains.rb
  lib/engine/share_price.rb
  public/logos/18_norway/BB.alt.svg
  public/logos/18_norway/BB.svg
  public/logos/18_norway/DB.alt.svg
  public/logos/18_norway/DB.svg
  public/logos/18_norway/HB.alt.svg
  public/logos/18_norway/HB.svg
  public/logos/18_norway/JB.alt.svg
  public/logos/18_norway/JB.svg
  public/logos/18_norway/OB.alt.svg
  public/logos/18_norway/OB.svg
  public/logos/18_norway/RB.alt.svg
  public/logos/18_norway/RB.svg
  public/logos/18_norway/SB.alt.svg
  public/logos/18_norway/SB.svg
  public/logos/18_norway/VB.alt.svg
  public/logos/18_norway/VB.svg
Labels: new games, 18Norway

#10613 [1847 AE] Fix share count bug
  lib/engine/game/g_1847_ae/share_pool.rb
Labels: pins, 1847AE

#10618 [1894] Update the brown B tile
  lib/engine/game/g_1894/map.rb
Labels: pins, 1894

#10646 1849 usability improvements (Timeline, AFG start spaces)
  lib/engine/game/g_1849/entities.rb
  lib/engine/game/g_1849/game.rb
Labels: enhancement, 1849

#10648 [18ESP] update face value of P1 and P2
  lib/engine/game/g_18_esp/entities.rb
Labels: archive_alpha_games, 18ESP

#10690 [18RoyalGorge] fix starting DEBT value
  lib/engine/game/g_18_royal_gorge/game.rb
Labels: pins
