Repository tobymao/18xx, pull requests merged in 2024-05, with the labels that each got.

#10699 [1846] Correct Ohio & Indiana description in 1846
  lib/engine/game/g_1846/entities.rb
Labels: 1846, entity display

#10688 [18 Hiawatha] signal_end_game text and fixes Liquidation section of the market
  lib/engine/game/g_18_hiawatha/game.rb
  lib/engine/game/g_18_hiawatha/step/loan.rb
Labels: archive_alpha_games, 18Hiawatha

#10711 [18Uruguay] Updated the president share to 30% for RPTLA
  lib/engine/game/g_18_uruguay/companies.rb
  lib/engine/game/g_18_uruguay/corporations.rb
Labels: new games, 18Uruguay

#10702 [18NL] fixes P6 company description
  lib/engine/game/g_18_nl/entities.rb
Labels: 18NL

#10694 [Core] Log backtrace on caught exception
  lib/engine/game/base.rb
Labels: Core

#10722 [18RG] fix ability keyword
  lib/engine/game/g_18_royal_gorge/game.rb
  public/fixtures/18RoyalGorge/post_boston.json
Labels: 18RoyalGorge

#10732 [18 India] Add Corporation Logos
  lib/engine/game/g_18_india/entities.rb
  public/logos/18_india/BNR-Back.svg
  public/logos/18_india/BNR.alt.svg
  public/logos/18_india/BNR.svg
  public/logos/18_india/BR-Back.svg
  public/logos/18_india/BR.alt.svg
  public/logos/18_india/BR.svg
  public/logos/18_india/CGR-Back.svg
  public/logos/18_india/CGR.alt.svg
  public/logos/18_india/CGR.svg
  public/logos/18_india/DHR-Back.svg
  public/logos/18_india/DHR.alt.svg
  public/logos/18_india/DHR.svg
  public/logos/18_india/EBR-Back.svg
  public/logos/18_india/EBR.alt.svg
  public/logos/18_india/EBR.svg
  public/logos/18_india/EIR-Back.svg
  public/logos/18_india/EIR.alt.svg
  public/logos/18_india/EIR.svg
  public/logos/18_india/GIPR-Back.svg
  public/logos/18_india/GIPR-Exchange.svg
  public/logos/18_india/GIPR.alt.svg
  public/logos/18_india/GIPR.svg
  public/logos/18_india/KGF-Back.svg
  public/logos/18_india/KGF.alt.svg
  public/logos/18_india/KGF.svg
  public/logos/18_india/MR-Back.svg
  public/logos/18_india/MR.alt.svg
  public/logos/18_india/MR.svg
  public/logos/18_india/NCR-Back.svg
  public/logos/18_india/NCR.alt.svg
  public/logos/18_india/NCR.svg
  public/logos/18_india/NSR-Back.svg
  public/logos/18_india/NSR.alt.svg
  public/logos/18_india/NSR.svg
  public/logos/18_india/NWR-Back.svg
  public/logos/18_india/NWR.alt.svg
  public/logos/18_india/NWR.svg
  public/logos/18_india/PNS-Back.svg
  public/logos/18_india/PNS.alt.svg
  public/logos/18_india/PNS.svg
  public/logos/18_india/SIR-Back.svg
  public/logos/18_india/SIR.alt.svg
  public/logos/18_india/SIR.svg
  public/logos/18_india/SPD-Back.svg
  public/logos/18_india/SPD.alt.svg
  public/logos/18_india/SPD.svg
  public/logos/18_india/TR-Back.svg
  public/logos/18_india/TR.alt.svg
  public/logos/18_india/TR.svg
  public/logos/18_india/WIP-Back.svg
  public/logos/18_india/WIP.alt.svg
  public/logos/18_india/WIP.svg
  public/logos/18_india/WR-Back.svg
  public/logos/18_india/WR.alt.svg
  public/logos/18_india/WR.svg
Labels: new games, 18India

#10713 [18SJ] fix bot corp choice after fullcap hits
  lib/engine/game/g_18_sj/game.rb
  lib/engine/game/g_18_sj/step/requisition.rb
  public/fixtures/18SJ/bot_chooses_fullcap.json
Labels: 18SJ

#10708 [18Norway] Nationalization
  lib/engine/game/g_18_norway/corporations.rb
  lib/engine/game/g_18_norway/game.rb
  lib/engine/game/g_18_norway/round/nationalization.rb
  lib/engine/game/g_18_norway/steps/nationalize_corporation.rb
  public/logos/18_norway/NSB.alt.svg
  public/logos/18_norway/NSB.svg
  public/logos/18_norway/port.svg
Labels: new games, 18Norway

#10707 [18Norway] Adding link to rules
  lib/engine/game/g_18_norway/meta.rb
Labels: new games, 18Norway

#10705 [18Norway] Update dividend rules
  lib/engine/game/g_18_norway/game.rb
  lib/engine/game/g_18_norway/steps/dividend.rb
Labels: new games, 18Norway

#10704 [18Norway] Adding support for tunnel building
  lib/engine/game/g_18_norway/game.rb
  lib/engine/game/g_18_norway/steps/build_tunnel.rb
  lib/engine/game/g_18_norway/steps/track.rb
Labels: new games, 18Norway

#10706 [18Norway] Adding buy train
  lib/engine/game/g_18_norway/game.rb
  lib/engine/game/g_18_norway/steps/buy_train.rb
Labels: new games, 18Norway

#10740 [1822CA] adds the city name and hex coordinates to P18 description
  lib/engine/game/g_1822_ca/entities.rb
Labels: 1822CA

#10642 [18Ardennes] Improvements to auction round and bug fixes
  lib/engine/game/g_18_ardennes/entities.rb
  lib/engine/game/g_18_ardennes/game.rb
  lib/engine/game/g_18_ardennes/step/buy_train.rb
  lib/engine/game/g_18_ardennes/step/major_auction.rb
Labels: new games, 18Ardennes

#10693 [18Ardennes] Display improvements
  lib/engine/game/g_18_ardennes/entities.rb
  lib/engine/game/g_18_ardennes/game.rb
  lib/engine/game/g_18_ardennes/round/auction.rb
  lib/engine/game/g_18_ardennes/round/stock.rb
  lib/engine/game/g_18_ardennes/step/buy_sell_par_shares_companies.rb
  lib/engine/game/g_18_ardennes/step/decline_trains.rb
  lib/engine/game/g_18_ardennes/step/exchange.rb
Labels: new games, 18Ardennes

#10692 [18Ardennes] Bug fixes
  lib/engine/game/g_18_ardennes/step/buy_sell_par_shares_companies.rb
  lib/engine/game/g_18_ardennes/step/decline_forts.rb
  lib/engine/game/g_18_ardennes/step/decline_trains.rb
  lib/engine/game/g_18_ardennes/step/minor_auction.rb
  lib/engine/game/g_18_ardennes/trains.rb
Labels: new games, 18Ardennes

#10691 [18Ardennes] Exchange approvals
  assets/app/view/game/buy_sell_shares.rb
  lib/engine/game/g_18_ardennes/game.rb
  lib/engine/game/g_18_ardennes/step/buy_sell_par_shares_companies.rb
  lib/engine/game/g_18_ardennes/step/exchange.rb
  lib/engine/game/g_18_ardennes/step/exchange_approval.rb
  lib/engine/game/g_18_ardennes/step/minor_exchange.rb
Labels: new games, Core, 18Ardennes

#10742 System18 Fix 2d stock market
  lib/engine/game/g_system18/game.rb
Labels: System18

#10717 [18 India] [Core] Create Multiple Selection Action and Refactor Certificate Selection
  assets/app/view/game/company.rb
  assets/app/view/game/round/auction.rb
  lib/engine/action/select_multiple_companies.rb
  lib/engine/game/g_18_india/game.rb
  lib/engine/game/g_18_india/step/certificate_selection.rb
Labels: new games, Core, 18India

#10697 [18 India] Implement Multiple Yellow Track Laying Rule
  lib/engine/game/g_18_india/step/railhead_tracker.rb
  lib/engine/game/g_18_india/step/special_track.rb
  lib/engine/game/g_18_india/step/track.rb
Labels: new games, 18India

#10751 18RoyalGorge fixes
  lib/engine/game/g_18_royal_gorge/game.rb
  lib/engine/game/g_18_royal_gorge/step/buy_sell_par_shares.rb
  lib/engine/game/g_18_royal_gorge/step/route.rb
  lib/engine/game/g_18_royal_gorge/step/single_item_auction.rb
  lib/engine/game/g_18_royal_gorge/step/special_choose.rb
Labels: archive_alpha_games

#10755 [18RoyalGorge] more fixes
  lib/engine/game/g_18_royal_gorge/entities.rb
  lib/engine/game/g_18_royal_gorge/game.rb
  lib/engine/game/g_18_royal_gorge/step/buy_sell_par_shares.rb
  lib/engine/game/g_18_royal_gorge/step/buy_train.rb
  lib/engine/game/g_18_royal_gorge/trains.rb
Labels: archive_alpha_games

#10753 [18Norway] D has 10% train discount
  lib/engine/game/g_18_norway/corporations.rb
Labels: new games, 18Norway

#10747 [1817] fix check for exporting trains (relevant when other games inherit)
  lib/engine/game/g_1817/game.rb
Labels: 1817, 18Hiawatha

#10785 [18Hiawatha] fixes typo in loan log message
  lib/engine/game/g_18_hiawatha/step/loan.rb
Labels: 18Hiawatha

#10766 [1894] Fix P1 power
  lib/engine/game/g_1894/entities.rb
Labels: pins

#10792 [18RoyalGorge] bug fixes
  lib/engine/game/base.rb
  lib/engine/game/g_18_royal_gorge/game.rb
  lib/engine/game/g_18_royal_gorge/step/single_item_auction.rb
  lib/engine/game/g_18_royal_gorge/step/special_choose.rb
Labels: archive_alpha_games, Core

#10779 [1844, Core] Fix private ability timings
  lib/engine/game/base.rb
  lib/engine/game/g_1844/entities.rb
  lib/engine/game/g_1844/game.rb
  lib/engine/game/g_1868_wy/entities.rb
  public/fixtures/1868 Wyoming/144719.json
Labels: pins, 1868WY

#10671 [18 India] Create and Remove Gauge Change Markers
  assets/app/view/game/part/borders.rb
  lib/engine/action/remove_border.rb
  lib/engine/game/g_18_india/game.rb
  lib/engine/game/g_18_india/step/gauge_change_border.rb
  lib/engine/game/g_18_india/step/route.rb
  lib/engine/game/g_18_india/step/special_track.rb
  lib/engine/game/g_18_india/step/track.rb
  lib/engine/part/border.rb
Labels: new games, Core, 18India

#10796 [TOP1871] fixes liquidity calculation
  lib/engine/game/g_1871/game.rb
Labels: 1871

#10801 [1880] Corp chooses FI token replacement and factor communism into player value
  lib/engine/game/g_1880/game.rb
  lib/engine/game/g_1880/step/check_fi_connection.rb
  public/fixtures/1880/1.json
  scripts/migrate_1880.rb
Labels: migration, 1880

#10798 [18USA] Do not auto pass train buying step if in the middle of a rusting event
  lib/engine/game/g_18_usa/step/buy_train.rb
Labels: pins, 18USA
