Repository tobymao/18xx, pull requests merged in 2024-10, with the labels that each got.

#11123 [22Mars] Initial Permit distribution round
  lib/engine/game/g_22_mars/game.rb
  lib/engine/game/g_22_mars/round/permit_purchase.rb
  lib/engine/game/g_22_mars/step/select_or_discard.rb
Labels: 22Mars

#11256 Fix spelling of Yaroslavl in 1861.
  lib/engine/game/g_1861/map.rb
Labels: minor bug, 1861

#11204 [18Ardennes] Fix error on bankruptcy
  lib/engine/game/g_18_ardennes/game.rb
  lib/engine/game/g_18_ardennes/step/bankrupt.rb
  lib/engine/game/g_18_ardennes/step/buy_sell_par_shares_companies.rb
Labels: 18Ardennes

#11208 [18Uruguay] Company should get full cap after nationalization and no destination bonus
  lib/engine/game/g_18_uruguay/game.rb
Labels: archive_alpha_games, 18Uruguay

#11200 [1847 AE] Fix one private bug and improve the description of another private
  lib/engine/game/g_1847_ae/entities.rb
  lib/engine/game/g_1847_ae/step/buy_single_train_of_type.rb
Labels: pins, 1847AE

#11213 [18Uruguay] Attempt to solve the dividend_types bug
  lib/engine/game/g_18_uruguay/step/dividend.rb
Labels: 18Uruguay

#11219 [18Hiawatha] Fix rules link
  lib/engine/game/g_18_hiawatha/meta.rb
Labels: 18Hiawatha

#11224 [1822nrs] fixes spelling of shrewsbury
  lib/engine/game/g_1822_nrs/map.rb
Labels: 1822nrs

#10990 [18Norway] Updated harbor
  lib/engine/game/g_18_norway/game.rb
  lib/engine/game/g_18_norway/steps/token.rb
Labels: new games, 18Norway

#11042 assets: Emit source maps
  Makefile
  api.rb
  lib/assets.rb
  queue.rb
Labels: Core

#11186 [1858Switzerland] Add game code for 1858 Switzerland variant
  lib/engine/game/g_1858_switzerland/game.rb
  lib/engine/game/g_1858_switzerland/graph.rb
  lib/engine/game/g_1858_switzerland/round/closure.rb
Labels: new games, 1858Switzerland

#11210 [18Uruguay] Do not ship more than ship capacity for rptla
  lib/engine/game/g_18_uruguay/game.rb
  lib/engine/game/g_18_uruguay/nationalization.rb
  lib/engine/game/g_18_uruguay/step/route_rptla.rb
Labels: archive_alpha_games, 18Uruguay

#11212 [18Uruguay] Allow more than 60% to cover for loans
  lib/engine/game/g_18_uruguay/step/buy_sell_par_shares.rb
Labels: archive_alpha_games, 18Uruguay

#11214 [18Uruguay] Company shall only retreive destination_bonus in their own turn
  lib/engine/game/g_18_uruguay/game.rb
  lib/engine/game/g_18_uruguay/step/destination_bonus.rb
Labels: archive_alpha_games, 18Uruguay

#11250 [1850jr] move to beta
  lib/engine/game/g_1850_jr/meta.rb
Labels: 1850jr

#11263 S18: add super to game overriding methods
  lib/engine/game/g_system18/game.rb
Labels: System18

#11285 [Core] Add support for one train rusting multiple train types
  assets/app/view/game/game_info.rb
  assets/app/view/game/route_selector.rb
  assets/app/view/game/train_schedule.rb
  lib/engine/depot.rb
  lib/engine/game/base.rb
  lib/engine/step/train.rb
  lib/engine/train.rb
  public/fixtures/1844/160062.json
  public/fixtures/1844/164302.json
Labels: pins, 1844

#11205 [18SJ] Corrects edge case nationalization calculation
  lib/engine/game/g_18_sj/game.rb
Labels: pins, 18SJ

#11282 [18esp] fix minor bugs
  lib/engine/game/g_18_esp/entities.rb
  lib/engine/game/g_18_esp/game.rb
Labels: 18ESP

#11291 S18 full Britain map fixes; add S18 fixture
  lib/engine/game/g_system18/map_britain_customization.rb
  public/fixtures/System18/182070.json
Labels: archive_alpha_games, System18

#11293 18Carolinas: fix power on corp restart
  lib/engine/game/g_18_carolinas/game.rb
Labels: 18Carolinas, pins

#11302 [System18] Remove broken fixture file
  public/fixtures/System18/182070.json
Labels: System18

#11207 [18GA] Implements Cotton Port variant
  lib/engine/game/g_18_ga/entities.rb
  lib/engine/game/g_18_ga/game.rb
  lib/engine/game/g_18_ga/map.rb
  lib/engine/game/g_18_ga/meta.rb
Labels: 18GA
