Repository tobymao/18xx, pull requests merged in 2024-03, with the labels that each got.

#10423 [18RoyalGorge] implement private Y2 Ghost Town Tours
  lib/engine/game/g_18_royal_gorge/entities.rb
  lib/engine/game/g_18_royal_gorge/game.rb
  lib/engine/game/g_18_royal_gorge/step/dividend.rb
Labels: new games

#10443 [1858] Delete private company reservation when token is placed
  lib/engine/game/g_1858/step/home_token.rb
Labels: pins, 1858

#10441 1841: Fix tiebreaker for Tuscan Merge decider
  lib/engine/game/g_1841/game.rb
Labels: pins

#10431 [1850] Add in corporation icons
  lib/engine/game/g_1850/entities.rb
  public/logos/1850/CBQ.alt.svg
  public/logos/1850/CBQ.svg
  public/logos/1850/GN.alt.svg
  public/logos/1850/GN.svg
  public/logos/1850/KATY.alt.svg
  public/logos/1850/KATY.svg
  public/logos/1850/MILW.alt.svg
  public/logos/1850/MILW.svg
  public/logos/1850/MP.alt.svg
  public/logos/1850/MP.svg
  public/logos/1850/NP.alt.svg
  public/logos/1850/NP.svg
  public/logos/1850/RI.alt.svg
  public/logos/1850/RI.svg
  public/logos/1850/SOO.alt.svg
  public/logos/1850/SOO.svg
  public/logos/1850/UP.alt.svg
  public/logos/1850/UP.svg
Labels: 1850

#10415 [18Ardennes] Exchanging minors for shares
  assets/app/view/game/buy_sell_shares.rb
  lib/engine/game/g_18_ardennes/entities.rb
  lib/engine/game/g_18_ardennes/game.rb
  lib/engine/game/g_18_ardennes/map.rb
  lib/engine/game/g_18_ardennes/step/buy_sell_par_shares_companies.rb
  lib/engine/game/g_18_ardennes/step/decline_forts.rb
  lib/engine/game/g_18_ardennes/step/decline_tokens.rb
  lib/engine/game/g_18_ardennes/step/decline_trains.rb
  lib/engine/game/g_18_ardennes/step/exchange.rb
  lib/engine/game/g_18_ardennes/step/major_auction.rb
  lib/engine/game/g_18_ardennes/step/minor_exchange.rb
Labels: new games, Core, 18Ardennes

#10472 [1848] Makes terminal paths always terminal
  lib/engine/game/g_1848/map.rb
Labels: pins

#10420 [1854] Adding first half of current step overrides
  lib/engine/depot.rb
  lib/engine/game/g_1854/depot.rb
  lib/engine/game/g_1854/step/buy_mail_contract.rb
  lib/engine/game/g_1854/step/buy_sell_par_shares.rb
  lib/engine/game/g_1854/step/buy_train.rb
  lib/engine/game/g_1854/step/dividend.rb
  lib/engine/game/g_1854/step/waterfall_auction.rb
Labels: new games, Core, 1854

#10421 [1854] Adding second half of step overrides
  lib/engine/game/g_1854/step/merge_minors.rb
  lib/engine/game/g_1854/step/track.rb
  lib/engine/game/g_1854/step/track_and_token.rb
Labels: new games, 1854

#10435 [core] allow trains to have variants dynamically added
  lib/engine/train.rb
Labels: Core

#10436 [core] abilities can increase in count, and stay open when count hits 0
  lib/engine/ability/base.rb
Labels: Core

#10445 [18RoyalGorge] show table for gold market; [core] allow multiple "map legends"
  assets/app/view/game/map_legend.rb
  lib/engine/game/base.rb
  lib/engine/game/g_18_royal_gorge/entities.rb
  lib/engine/game/g_18_royal_gorge/game.rb
  lib/engine/game/g_18_royal_gorge/step/dividend.rb
  lib/engine/game/g_21_moon/game.rb
Labels: Core

#10447 [18RoyalGorge, core] allow president sales to market for only specified corporations
  lib/engine/game/base.rb
  lib/engine/game/g_18_royal_gorge/game.rb
  lib/engine/game/g_18_royal_gorge/step/buy_sell_par_shares.rb
  lib/engine/share_pool.rb
Labels: Core

#10448 [core] Allow companies to provide a discount when buying shares
  assets/app/view/game/button/buy_share.rb
  assets/app/view/game/buy_sell_shares.rb
  lib/engine/action/buy_shares.rb
  lib/engine/game/g_18_new_england/step/buy_sell_par_shares.rb
  lib/engine/game/g_18_va/step/buy_sell_par_shares.rb
  lib/engine/game/g_21_moon/step/buy_sell_par_shares.rb
  lib/engine/game/g_21_moon/step/corporate_buy_sell_shares.rb
  lib/engine/game/g_rolling_stock/step/buy_sell_shares_bid_companies.rb
  lib/engine/share_pool.rb
  lib/engine/step/buy_sell_par_shares.rb
  lib/engine/step/share_buying.rb
Labels: Core

#10465 [18Ardennes] Various small changes and fixes
  lib/engine/game/g_18_ardennes/game.rb
  lib/engine/game/g_18_ardennes/map.rb
  lib/engine/game/g_18_ardennes/market.rb
  lib/engine/game/g_18_ardennes/step/decline_tokens.rb
  lib/engine/game/g_18_ardennes/step/track.rb
  lib/engine/game/g_18_ardennes/trains.rb
Labels: new games, 18Ardennes

#10471 [18NY] makes terminal offboards actually terminal
  lib/engine/game/g_18_ny/map.rb
  lib/engine/game/g_18_ny_1e/map.rb
Labels: pins, 18NY

#10474 [1817] fixes edge case bug with Train Station private
  lib/engine/game/g_1817/game.rb
  lib/engine/game/g_1817/step/buy_sell_par_shares.rb
Labels: 1817, pins

#10475 [1894] Chenge some privates revenues, add one station
  assets/app/view/welcome.rb
  lib/engine/game/g_1894/entities.rb
Labels: pins, 1894

#10482 [1854] Final Set of Alpha Files
  lib/engine/game/g_1854.rb
  lib/engine/game/g_1854/ability/assign_minor.rb
  lib/engine/game/g_1854/game.rb
  lib/engine/game/g_1854/mail_contract.rb
  lib/engine/game/g_1854/meta.rb
  lib/engine/game/g_1854/phases.rb
  lib/engine/game/g_1854/round/stock.rb
  public/fixtures/1854/1.json
  public/fixtures/1854/2.json
Labels: 1854

#10506 Revert "[18RoyalGorge, core] allow president sales to market for only…
  lib/engine/game/base.rb
  lib/engine/game/g_18_royal_gorge/game.rb
  lib/engine/game/g_18_royal_gorge/step/buy_sell_par_shares.rb
  lib/engine/share_pool.rb
Labels: Core

#10527 21Moon: update gray tiles to match physical game
  lib/engine/game/g_21_moon/map.rb
  public/fixtures/21Moon/151934.json
Labels: pins

#10534 [Core] Add comment about suppressing backtick warning
  assets/app/mail/turn.rb
Labels: email, Core

#10548 [21Moon] fix terminal tile placement
  lib/engine/game/g_21_moon/entities.rb
  lib/engine/game/g_21_moon/game.rb
Labels: pins, 21Moon

#10549 [21Moon] Terminal private revenue s.b. 15 space bucks
  lib/engine/game/g_21_moon/entities.rb
Labels: pins, 21Moon
