Repository tobymao/18xx, pull requests merged in 2024-01, with the labels that each got.

#10101 [18EU] Leading bidder is removed from auction early
  lib/engine/game/g_18_eu/step/modified_dutch_auction.rb
  public/fixtures/18EU/can_pass_when_bid_equals_cash.json
Labels: 18EU

#10089 18GB: Prevent special token powers being used illegally
  lib/engine/game/g_18_gb/step/special_token.rb
Labels: pins

#10134 [1850] corrects color of one stock market space
  lib/engine/game/g_1850/game.rb
Labels: pins

#10143 [18AL] Fix ability timing for train_discount.
  lib/engine/game/g_18_al/entities.rb
  public/fixtures/18AL/hs_pzujrnou_144868.json
Labels: 18AL

#10128 [18EU] Properly restrict stock exchange to match rules
  lib/engine/game/g_18_eu/step/final_exchange.rb
  lib/engine/game/g_18_eu/step/minor_exchange.rb
  public/fixtures/18EU/74045.json
  public/fixtures/18EU/auto_pass_already_tokened.json
Labels: 18EU, pins

#10153 [1822CA] fix a few small bugs
  lib/engine/game/g_1822/step/minor_acquisition.rb
  lib/engine/game/g_1822_ca/game.rb
  lib/engine/game/g_1822_ca/round/stock.rb
  lib/engine/game/g_1822_ca/step/minor_acquisition.rb
  lib/engine/game/g_1822_ca/step/special_track.rb
Labels: pins

#10127 [18EU][18MT] Change default Pass optional to conditional in programmed auction bid, was causing infinite loops
  lib/engine/step/programmer_auction_bid.rb
  spec/lib/engine/games/g_18eu_spec.rb
  spec/lib/engine/games/g_18mt_spec.rb
Labels: 18EU, 18MT

#10104 [18Ardennes] Starting major corporations
  assets/app/view/game/round/auction.rb
  assets/app/view/game/round/stock.rb
  lib/engine/game/g_18_ardennes/entities.rb
  lib/engine/game/g_18_ardennes/game.rb
  lib/engine/game/g_18_ardennes/map.rb
  lib/engine/game/g_18_ardennes/step/buy_sell_par_shares_companies.rb
  lib/engine/game/g_18_ardennes/step/major_auction.rb
  lib/engine/game/g_18_ardennes/step/minor_auction.rb
  lib/engine/game/g_18_ardennes/step/minor_exchange.rb
Labels: new games, Core, 18Ardennes

#10188 [1888] Change bonus icon to be circular to hide circle below.
  public/icons/1888/mine.svg
Labels: tile rendering, 1888

#10192 [1822CA] various token fixes
  assets/app/view/game/part/city.rb
  assets/app/view/game/part/city_slot.rb
  lib/engine/game/g_1822/game.rb
  lib/engine/game/g_1822_ca/entities.rb
  lib/engine/game/g_1822_ca/game.rb
  lib/engine/game/g_1822_ca/map.rb
  lib/engine/game/g_1822_ca/step/destination_token.rb
  lib/engine/part/city.rb
  lib/engine/part/icon.rb
  lib/engine/token.rb
  public/fixtures/1822CA/1.json
  public/fixtures/1822CA/2.json
  public/fixtures/1822CA/README.md
  spec/assets_spec.rb
  spec/game_state_spec.rb
Labels: archive_alpha_games

#10205 [1822CA] fix constructing city map before picking up cheater destination tokens
  lib/engine/game/g_1822_ca/game.rb
  public/fixtures/1822CA/3.json
  spec/game_state_spec.rb
Labels: pins

#10206 [18SJ] fix setup randomization: shuffle each collection
  lib/engine/game/g_18_sj/game.rb
Labels: pins
