Repository tobymao/18xx, pull requests merged in 2025-06, with the labels that each got.

#11781 [18India] updates rulebook link
  lib/engine/game/g_18_india/meta.rb
Labels: 18India

#11770 [18India] removes leftover debug code
  lib/engine/game/g_18_india/game.rb
  lib/engine/game/g_18_india/step/certificate_selection.rb
  lib/engine/game/g_18_india/step/corporate_buy_shares_company.rb
  lib/engine/game/g_18_india/step/dividend.rb
  lib/engine/game/g_18_india/step/exchange_token.rb
  lib/engine/game/g_18_india/step/gauge_change_border.rb
  lib/engine/game/g_18_india/step/home_track.rb
  lib/engine/game/g_18_india/step/railhead_tracker.rb
  lib/engine/game/g_18_india/step/sell_once_then_buy_certs.rb
  lib/engine/game/g_18_india/step/track.rb
Labels: 18India

#11743 [1847AE] should LFK only pay on on first new train
  lib/engine/game/g_1847_ae/step/buy_single_train_of_type.rb
Labels: pins, 1847AE

#11752 [1861/1867] Don't transfer zero-cost tokens from minors to majors
  lib/engine/game/g_1867/game.rb
  lib/engine/game/g_1867/step/merge.rb
  lib/engine/game/g_1867/step/reduce_tokens.rb
Labels: pins, 1867, 1861

#11736 [1858 India] Locomotive works privates
  lib/engine/game/g_1858_india/entities.rb
  lib/engine/game/g_1858_india/game.rb
  lib/engine/game/g_1858_india/step/buy_train.rb
Labels: new games, 1858India

#11788 Some minor autorouter bugfixes
  assets/app/view/game/route_selector.rb
  lib/engine/auto_router.rb
  lib/engine/game/g_1822/game.rb
Labels: autorouting

#11769 [1848] must sell in blocks -> confirmed by designer
  lib/engine/game/g_1848/game.rb
Labels: pins, 1848

#11804 autorouter: Fix invalid array check
  lib/engine/auto_router.rb
Labels: autorouting

#11801 [1858 family] Enforce correct track types in route selector
  lib/engine/game/g_1858/game.rb
Labels: 1858, 1858Switzerland, 1858India

#11718 [18PA] pre-alpha updates (tiles, tokens, bonus markers)
  lib/engine/game/g_18_pa/entities.rb
  lib/engine/game/g_18_pa/game.rb
  lib/engine/game/g_18_pa/map.rb
  lib/engine/game/g_18_pa/step/dividend.rb
  lib/engine/game/g_18_pa/step/track.rb
  public/logos/18_pa/b&a.svg
  public/logos/18_pa/b&o.svg
  public/logos/18_pa/cnj.svg
  public/logos/18_pa/erie.svg
  public/logos/18_pa/nyc.svg
  public/logos/18_pa/nynh.svg
  public/logos/18_pa/prr.svg
Labels: new games, 18PA

#11627 [core] notify game owner when game is full
  routes/game.rb
Labels: front page

#11758 [18Norway] Don't allow selling president's share to NSB
  lib/engine/game/g_18_norway/game.rb
  lib/engine/game/g_18_norway/steps/buy_sell_par_shares.rb
  spec/lib/engine/games/g_18_norway/g_18_norway_share_selling_spec.rb
Labels: archive_alpha_games, hold-merge, 18Norway

#11759 [18Norway] Nationalization rounds should not pay out companies
  lib/engine/game/g_18_norway/game.rb
  lib/engine/game/g_18_norway/round/nationalization.rb
  lib/engine/game/g_18_norway/steps/nationalize_corporation.rb
  public/fixtures/18Norway/18_norway_buy_ship.json
Labels: archive_alpha_games, hold-merge, 18Norway

#11760 [18Norway] Stock movement should be left block if in bank pool and right block if sold out
  lib/engine/game/g_18_norway/game.rb
Labels: archive_alpha_games, hold-merge, 18Norway

#11808 [18Norway] Fix typo in Jotunheimen
  lib/engine/game/g_18_norway/map.rb
Labels: 18Norway

#11809 [18Norway] Include discount when calculating cheapest train price
  lib/engine/game/g_18_norway/game.rb
  lib/engine/game/g_18_norway/steps/buy_train.rb
Labels: archive_alpha_games, hold-merge, 18Norway

#11797 [18Norway] Updated autoroute
  lib/engine/game/g_18_norway/game.rb
Labels: 18Norway

#11386 [18RoyalGorge] Require graph connection for cross-buying trains
  lib/engine/game/g_18_royal_gorge/step/buy_train.rb
Labels: pins, 18RoyalGorge

#11802 [1858 India] Mine, oil and port tokens
  lib/engine/game/g_1858_india/game.rb
  lib/engine/game/g_1858_india/map.rb
  lib/engine/game/g_1858_india/step/collect_tokens.rb
  lib/engine/game/g_1858_india/step/route.rb
  lib/engine/game/g_1858_india/tiles.rb
  public/icons/1858_india/oil.svg
  public/logos/1858_india/mine.svg
  public/logos/1858_india/oil.svg
  public/logos/1858_india/port.svg
Labels: new games, 1858India

#11813 Route selector improvements
  lib/engine/route.rb
Labels: routes, Core
