Repository tobymao/18xx, pull requests merged in 2025-03, with the labels that each got.

#11585 [18Uruguay] Corrected aquire fce share sequence
  lib/engine/game/g_18_uruguay/nationalization.rb
Labels: pins, 18Uruguay

#11587 [Core] Allow corporations in receivership to use the buy train step
  lib/engine/share_pool.rb
Labels: Core

#11586 [Core] Move marking trains as not operated to start of operating round
  lib/engine/game/g_1817/round/operating.rb
  lib/engine/game/g_1841/round/operating.rb
  lib/engine/round/operating.rb
  public/fixtures/18NL/135853.json
  public/fixtures/18NL/167050.json
Labels: Core

#11588 [18Uruguay] Updated closed corporations after nationalization
  lib/engine/game/g_18_uruguay/game.rb
Labels: 18Uruguay

#11589 [18Norway] Corrected turn calculation
  lib/engine/game/g_18_norway/game.rb
  lib/engine/game/g_18_norway/round/nationalization.rb
Labels: 18Norway

#11590 [Core] Enhance selection auction automatic passes
  lib/engine/step/selection_auction.rb
Labels: migrate_game, 1837

#11575 [18ES] fix minor 18esp errors
  lib/engine/game/g_18_esp/game.rb
  lib/engine/game/g_18_esp/step/acquire.rb
  lib/engine/game/g_18_esp/step/buy_train.rb
  lib/engine/game/g_18_esp/step/choose.rb
Labels: 18ESP

#11592 [18Norway] Corrected the minimum price reqiured for privates
  lib/engine/game/g_18_norway/game.rb
Labels: 18Norway

#11593 [18Norway] Companies that are floated after end game is automatically nationalized
  lib/engine/game/g_18_norway/game.rb
  lib/engine/game/g_18_norway/steps/nationalize_corporation.rb
Labels: 18Norway

#11596 [18Norway] Updated map
  lib/engine/game/g_18_norway/corporations.rb
  lib/engine/game/g_18_norway/game.rb
  lib/engine/game/g_18_norway/map.rb
Labels: 18Norway

#11599 [Core] Don't assume all operating entities have trains
  lib/engine/round/operating.rb
Labels: Core

#11601 [18ESP] Fix more minor 18esp issues
  lib/engine/game/g_18_esp/game.rb
Labels: 18ESP

#11576 [1867] Fix active entity for home token step
  lib/engine/game/g_1867/game.rb
  lib/engine/game/g_1867/step/home_token.rb
Labels: 1867

#11605 [18ESP] minor 18esp rand fix and move to beta
  assets/app/view/welcome.rb
  lib/engine/game/g_18_esp/game.rb
  lib/engine/game/g_18_esp/map.rb
  lib/engine/game/g_18_esp/meta.rb
Labels: 18ESP

#11541 [1867] Remove "medium" from corp sizes
  lib/engine/game/g_1867/game.rb
Labels: 1867, 1861

#11595 [18Norway] You are only allowed to buy the cheapest train during emergency
  lib/engine/game/g_18_norway/depot.rb
  lib/engine/game/g_18_norway/game.rb
  lib/engine/game/g_18_norway/steps/buy_train.rb
Labels: 18Norway

#11607 [Steam Over Holland] fixes EMR bug
  lib/engine/game/g_steam_over_holland/game.rb
  lib/engine/game/g_steam_over_holland/step/buy_train.rb
  lib/engine/game/g_steam_over_holland/step/issue_shares.rb
  public/fixtures/Steam Over Holland/steam_over_holland_fixture_1.json
Labels: archive_alpha_games, Steam Over Holland

#11611 [18Norway] Adding missing extra_slot attribute
  lib/engine/game/g_18_norway/steps/token.rb
Labels: 18Norway

#11619 [1858] Clear pass flag when bidding for a private
  lib/engine/game/g_1858/step/buy_sell_par_shares.rb
Labels: pins, 1858, 1858Switzerland

#11621 [1858] Disable autopass on private railway company bids
  lib/engine/game/g_1858/step/buy_sell_par_shares.rb
Labels: 1858, 1858Switzerland

#11540 [1812] multiple pre-alpha updates
  lib/engine/game/g_1812/entities.rb
  lib/engine/game/g_1812/game.rb
  lib/engine/game/g_1812/map.rb
  lib/engine/game/g_1812/meta.rb
  lib/engine/game/g_1812/phases.rb
  lib/engine/game/g_1812/step/buy_sell_par_shares.rb
  lib/engine/game/g_1812/step/buy_train.rb
  lib/engine/game/g_1812/step/loan_operations.rb
  lib/engine/game/g_1812/trains.rb
  lib/engine/game/g_1867/step/loan_operations.rb
Labels: new games, 1812

#11602 [1837] Use backtracking graph in the token step
  lib/engine/game/g_1837/step/token.rb
Labels: 1837

#11644 [1837] Fix error in token step.
  lib/engine/game/g_1837/step/token.rb
Labels: 1837
