Repository tobymao/18xx, pull requests merged in 2025-07, with the labels that each got.

#11820 [1858 India/Core] Add option to show private companies on the left in the buy trains step
  assets/app/view/game/round/operating.rb
  lib/engine/game/g_1858_india/game.rb
  lib/engine/game/g_1858_india/step/buy_train.rb
  lib/engine/game/g_1858_india/step/discard_train.rb
  lib/engine/game/g_1858_india/step/route.rb
Labels: new games, Core, 1858India

#11826 [18Norway] fix price change after SR
  lib/engine/game/g_18_norway/game.rb
  lib/engine/game/g_18_norway/round/stock.rb
Labels: archive_alpha_games, 18Norway

#11827 [base] - updates log to include player name when corp takes SR action
  lib/engine/share_pool.rb
Labels: game log, Core

#11829 [1822NRS] adds London stub for LNWR
  lib/engine/game/g_1822_nrs/map.rb
Labels: pins, 1822nrs

#11851 Autorouter: Allow overlapping routes with pre-filled trains and don't search for routes for pre-filled trains
  lib/engine/auto_router.rb
Labels: autorouting

#11850 [18 India] fixed sr1 buy issues and cleaned up ferry tile fix #11487and #11810
  lib/engine/game/g_18_india/step/sell_once_then_buy_certs.rb
  lib/engine/game/g_18_india/step/track.rb
Labels: archive_alpha_games, 18India

#11852 [18MEX] Correct bug for upgrading F5 for non-470 tile #11462
  lib/engine/game/g_18_mex/game.rb
Labels: 18MEX

#11720 [1837] Handle edge case where merger happens when corporation is at or over the train limit
  lib/engine/game/g_1837/game.rb
Labels: 1837
