Repository tobymao/18xx, pull requests merged in 2025-01, with the labels that each got.

#11439 [1807] Rename 18BF → 1807
  .github/CODEOWNERS
  lib/engine/game/g_1807.rb
  lib/engine/game/g_1807/entities.rb
  lib/engine/game/g_1807/game.rb
  lib/engine/game/g_1807/map.rb
  lib/engine/game/g_1807/market.rb
  lib/engine/game/g_1807/meta.rb
  lib/engine/game/g_1807/step/special_track.rb
  lib/engine/game/g_1807/tiles.rb
  lib/engine/game/g_1807/trains.rb
  public/logos/1807/BE.svg
  public/logos/1807/BG.svg
  public/logos/1807/CR.svg
  public/logos/1807/EC.svg
  public/logos/1807/EG.svg
  public/logos/1807/EK.svg
  public/logos/1807/EPD.svg
  public/logos/1807/GA.svg
  public/logos/1807/GC.svg
  public/logos/1807/GCR.svg
  public/logos/1807/GER.svg
  public/logos/1807/GJ.svg
  public/logos/1807/GNR.svg
  public/logos/1807/GWR.svg
  public/logos/1807/LB.svg
  public/logos/1807/LBSC.svg
  public/logos/1807/LH.svg
  public/logos/1807/LMS.svg
  public/logos/1807/LNE.svg
  public/logos/1807/LNW.svg
  public/logos/1807/LR.svg
  public/logos/1807/LS.svg
  public/logos/1807/LSW.svg
  public/logos/1807/LY.svg
  public/logos/1807/LYR.svg
  public/logos/1807/MC.svg
  public/logos/1807/ML.svg
  public/logos/1807/MR.svg
  public/logos/1807/NBR.svg
  public/logos/1807/ND.svg
  public/logos/1807/NER.svg
  public/logos/1807/NM.svg
  public/logos/1807/NU.svg
  public/logos/1807/SAM.svg
  public/logos/1807/SE.svg
  public/logos/1807/SEC.svg
  public/logos/1807/SR.svg
  public/logos/1807/TV.svg
  public/logos/1807/VN.svg
  public/logos/1807/YNM.svg
Labels: new games, 1807

#11415 [18FR] Initial commit: map, tiles, info
  lib/engine/game/g_18_fr.rb
  lib/engine/game/g_18_fr/entities.rb
  lib/engine/game/g_18_fr/game.rb
  lib/engine/game/g_18_fr/map.rb
  lib/engine/game/g_18_fr/meta.rb
  lib/engine/game/g_18_fr/step/buy_sell_par_shares.rb
  lib/engine/game/g_18_fr/step/track.rb
  lib/engine/game/g_18_fr/step/tracker.rb
  public/icons/18_fr/beach.svg
Labels: new games, 18FR

#11435 [1837] Allow backtracking when considering token spots
  lib/engine/game/g_1837/game.rb
  lib/engine/graph.rb
  lib/engine/part/node.rb
  lib/engine/part/path.rb
Labels: new games, Core, 1837

#11397 [18india] Fixes tile IF1
  lib/engine/game/g_18_india/map.rb
Labels: archive_alpha_games, 18India

#11433 [Core] Don't modify TRAINS definition when creating train variants
  lib/engine/train.rb
Labels: Core

#11417 [1849] modification to code for variants
  lib/engine/game/g_1849/game.rb
  lib/engine/game/g_1849/step/bond.rb
  lib/engine/game/g_1849/step/bond_interest_payment.rb
  lib/engine/game/g_1849/step/buy_e_token.rb
  lib/engine/game/g_1849/step/buy_token.rb
Labels: pins, archive_alpha_games, 1849 variants

#11426 [18Norway] Setup privates for 1.5X
  lib/engine/game/g_18_norway/game.rb
Labels: new games, 18Norway

#11427 [18Norway] Only ships are allowed to use harbors
  lib/engine/game/g_18_norway/game.rb
Labels: new games, 18Norway

#11440 [1807] Update map and tile manifest
  lib/engine/game/g_1807/map.rb
  lib/engine/game/g_1807/tiles.rb
Labels: new games, 1807

#11441 [1807] Change terminology: public companies, not majors
  lib/engine/game/g_1807/entities.rb
  lib/engine/game/g_1807/trains.rb
Labels: new games, 1807

#11442 [1807] Minor fixes and improvements
  lib/engine/game/g_1807/game.rb
  lib/engine/game/g_1807/map.rb
Labels: new games, 1807

#11451 S18: 1D market fixes
  lib/engine/game/g_system18/game.rb
Labels: archive_alpha_games

#11209 [18Uruguay] Also add FCE shares to secondary corps
  lib/engine/game/g_18_uruguay/game.rb
  lib/engine/game/g_18_uruguay/nationalization.rb
  lib/engine/game/g_18_uruguay/step/nationalize_corporation.rb
Labels: archive_alpha_games, 18Uruguay
