Repository tobymao/18xx, pull requests merged in 2025-05, with the labels that each got.

#11704 [1848] reverts change #11630 - unexpected bugs
  assets/app/view/game/company.rb
  lib/engine/company.rb
  lib/engine/game/g_1848/entities.rb
  lib/engine/game/g_1848/step/dutch_auction.rb
Labels: 1848

#11686 [site] Discard Trains step to display page description instead of default 'Discard Trains'
  assets/app/view/game/discard_trains.rb
  lib/engine/game/g_18_ny/step/discard_train.rb
  lib/engine/step/discard_train.rb
Labels: Core

#11640 [18Norway] Reimplement that you only are allowed to have one ship per type
  lib/engine/game/g_18_norway/depot.rb
  lib/engine/game/g_18_norway/steps/buy_train.rb
  public/fixtures/18Norway/18_norway_buy_ship.json
  spec/lib/engine/games/g_18_norway/g_18_norway_buy_ship_spec.rb
  spec/lib/engine/games/g_18_norway/g_18_norway_hovebanen.rb
Labels: 18Norway

#11687 [18Norway] Dev stage alpha
  lib/engine/game/g_18_norway/meta.rb
Labels: hold-merge, 18Norway

#11629 [18FR] Add train discounts when exporting
  lib/engine/game/g_18_fr/game.rb
  lib/engine/game/g_18_fr/step/buy_train.rb
  lib/engine/game/g_18_fr/train.rb
Labels: new games, 18FR

#11653 [Core/1868WY] Add method for checking if a hex token can be removed
  assets/app/view/game/hex.rb
  lib/engine/game/g_1868_wy/step/development_token.rb
Labels: 1868WY, Core

#11717 [18Ardennes] Fix error after bankruptcy in stock round
  lib/engine/game/g_18_ardennes/game.rb
  lib/engine/game/g_18_ardennes/step/minor_auction.rb
Labels: 18Ardennes

#11722 [1822NRS] removes erroneous hex from map
  lib/engine/game/g_1822_nrs/map.rb
Labels: 1822nrs

#11727 [18ESP] Updated rules URLs
  lib/engine/game/g_18_esp/meta.rb
Labels: 18ESP

#11716 [1858 India] Add mail trains
  lib/engine/game/g_1858_india/game.rb
  lib/engine/game/g_1858_india/step/buy_train.rb
  lib/engine/game/g_1858_india/step/route.rb
Labels: new games, 1858India

#11748 [1858 Switzerland] Fix spelling of VSB private railway company
  lib/engine/game/g_1858_switzerland/entities.rb
Labels: 1858Switzerland

#11749 [1858] Fix error in hotseat games
  lib/engine/game/g_1858/step/buy_sell_par_shares.rb
Labels: 1858

#11738 [1849] Variants - remove bonds block
  lib/engine/game/g_1849/step/bond_interest_payment.rb
Labels: pins, 1849 variants

#11740 [18Norway] fixes coordinates for P1 from I23 to J23
  lib/engine/game/g_18_norway/companies.rb
Labels: archive_alpha_games, 18Norway

#11721 [18esp] fix mz mza cheater token
  lib/engine/game/g_18_esp/game.rb
  lib/engine/game/g_18_esp/step/home_token.rb
Labels: 18ESP
