Repository tobymao/18xx, pull requests merged in 2025-04, with the labels that each got.

#11625 [1852] highlights destination hex during tile laying step
  lib/engine/game/g_18_mo/step/track_and_token.rb
Labels: 1852: Missouri

#11649 Remove 1807 Kickstarter from the front page
  assets/app/view/welcome.rb
Labels: front page, 1807

#11639 [18Uruguay] Check for nil before check for closed
  lib/engine/game/g_18_uruguay/game.rb
Labels: 18Uruguay

#11651 [1844] Min price for corp to buy a private is 1 SFR
  lib/engine/game/g_1844/entities.rb
  public/fixtures/1844/160062.json
Labels: migrate_game, 1844

#11662 [18USA] Remove asterisks from private P3's description
  lib/engine/game/g_18_usa/entities.rb
Labels: 18USA

#11663 21Moon: Terminal teleport fix
  lib/engine/game/g_21_moon/entities.rb
Labels: pins, 21Moon

#11652 [1858/1858 Switzerland] Refactoring in preparation for 1858 India implementation
  lib/engine/game/g_1858/entities.rb
  lib/engine/game/g_1858/game.rb
  lib/engine/game/g_1858/graph.rb
  lib/engine/game/g_1858/market.rb
  lib/engine/game/g_1858/step/buy_train.rb
  lib/engine/game/g_1858/step/route.rb
  lib/engine/game/g_1858/step/track.rb
  lib/engine/game/g_1858/trains.rb
  lib/engine/game/g_1858_switzerland/entities.rb
  lib/engine/game/g_1858_switzerland/game.rb
Labels: 1858, 1858Switzerland

#11665 [18Ardennes] Fix error when priority player bankrupts
  lib/engine/game/g_18_ardennes/game.rb
  lib/engine/game/g_18_ardennes/step/exchange.rb
Labels: 18Ardennes

#11667 [18Norway] Correcte minor map issue in Kristiansand
  lib/engine/game/g_18_norway/map.rb
Labels: new games, 18Norway

#11668 21Moon: CR issue price drop fix
  lib/engine/game/g_21_moon/step/corporate_buy_sell_shares.rb
Labels: pins, 21Moon

#11632 [System18] Fixes Northern Italy price movement
  lib/engine/game/g_system18/map_northern_italy_customization.rb
Labels: archive_alpha_games, System18

#11682 [1849] fixes blocking step error in variants
  lib/engine/game/g_1849/game.rb
Labels: 1849, 1849 variants

#11685 [1877 Stockholm Tramways] clear graph after merger
  lib/engine/game/g_1877_stockholm_tramways/step/acquire.rb
Labels: pins, 1877: Stockholm Tramways

#11693 [1807] Updated company colours
  lib/engine/game/g_1807/entities.rb
  lib/engine/game/g_1807/game.rb
  lib/engine/game/g_1807/market.rb
  public/logos/1807/BE.svg
  public/logos/1807/BG.svg
  public/logos/1807/CR.svg
  public/logos/1807/EC.svg
  public/logos/1807/EG.svg
  public/logos/1807/EK.svg
  public/logos/1807/EPD.svg
  public/logos/1807/GA.svg
  public/logos/1807/GC.svg
  public/logos/1807/GCR.svg
  public/logos/1807/GER.svg
  public/logos/1807/GJ.svg
  public/logos/1807/GNR.svg
  public/logos/1807/GWR.svg
  public/logos/1807/LB.svg
  public/logos/1807/LBSC.svg
  public/logos/1807/LH.svg
  public/logos/1807/LMS.svg
  public/logos/1807/LNE.svg
  public/logos/1807/LNW.svg
  public/logos/1807/LR.svg
  public/logos/1807/LS.svg
  public/logos/1807/LSW.svg
  public/logos/1807/LY.svg
  public/logos/1807/LYR.svg
  public/logos/1807/MC.svg
  public/logos/1807/ML.svg
  public/logos/1807/MR.svg
  public/logos/1807/NBR.svg
  public/logos/1807/ND.svg
  public/logos/1807/NER.svg
  public/logos/1807/NM.svg
  public/logos/1807/NU.svg
  public/logos/1807/SAM.svg
  public/logos/1807/SE.svg
  public/logos/1807/SEC.svg
  public/logos/1807/SECR.svg
  public/logos/1807/SR.svg
  public/logos/1807/TV.svg
  public/logos/1807/VN.svg
  public/logos/1807/YNM.svg
Labels: new games, 1807

#11696 [1858 India] Map updates
  lib/engine/game/g_1858_india/entities.rb
  lib/engine/game/g_1858_india/map.rb
  public/icons/1858_india/BS+BT.svg
Labels: new games, 1858India

#11697 [1858 India] Add type attributes to companies and trains
  lib/engine/game/g_1858_india/entities.rb
  lib/engine/game/g_1858_india/game.rb
Labels: new games, 1858India

#11676 [18ESP] more bug fixes + add bank card custom info
  assets/app/view/game/bank.rb
  lib/engine/game/g_18_esp/game.rb
Labels: 18ESP
