Repository tobymao/18xx, pull requests merged in 2025-09, with the labels that each got.

#11952 [System 18] Scotland rule updates; Upward auction rule updates
  lib/engine/game/g_system18/map_northern_italy_customization.rb
  lib/engine/game/g_system18/map_poland_customization.rb
  lib/engine/game/g_system18/map_scotland_customization.rb
  lib/engine/game/g_system18/step/charter_auction.rb
  lib/engine/game/g_system18/step/order_auction.rb
  lib/engine/game/g_system18/step/upwards_auction.rb
Labels: pins

#11961 [18 India] Nationalization fix
  lib/engine/game/g_18_india/game.rb
  public/fixtures/18 India/Nationalization-Exchange-Token.json
  public/fixtures/18 India/Nationalization-Share-Return-GIPR.json
  public/fixtures/18 India/Nationalization-Share-Return-no-GIPR.json
  public/fixtures/18 India/Nationalization-Token-Conflict.json
Labels: archive_alpha_games

#11949 [18RoyalGorge] fix endgame trigger, add optional rule for alternate endgame
  lib/engine/game/base.rb
  lib/engine/game/g_18_royal_gorge/game.rb
  lib/engine/game/g_18_royal_gorge/meta.rb
  public/fixtures/18RoyalGorge/endgame_shorter_triggered_on_buy.json
  public/fixtures/18RoyalGorge/endgame_shorter_triggered_on_export.json
  public/fixtures/18RoyalGorge/endgame_triggered_on_buy.json
  public/fixtures/18RoyalGorge/endgame_triggered_on_export.json
  spec/game_spec_helper.rb
  spec/lib/engine/game/g_18_royal_gorge/game_spec.rb
Labels: pins

#11951 [18GB] Restrict buying president's certificate from the pool
  lib/engine/game/g_18_gb/step/buy_sell_par_shares.rb
Labels: pins, 18GB

#11966 [18Norway] new privates
  lib/engine/game/g_18_norway/companies.rb
  lib/engine/game/g_18_norway/game.rb
  lib/engine/game/g_18_norway/meta.rb
  lib/engine/game/g_18_norway/steps/build_tunnel.rb
  lib/engine/game/g_18_norway/steps/buy_train.rb
  public/fixtures/18Norway/18_norway_buy_ship.json
Labels: archive_alpha_games

#11943 [1824] Refactor to put all Cisleithania specifics in g_1824_cisleithania
  lib/engine/game/g_1824/corporation.rb
  lib/engine/game/g_1824/game.rb
  lib/engine/game/g_1824/map.rb
  lib/engine/game/g_1824/meta.rb
  lib/engine/game/g_1824/round/first_stock.rb
  lib/engine/game/g_1824/step/buy_sell_par_exchange_shares.rb
  lib/engine/game/g_1824/step/buy_sell_par_shares_first_sr.rb
  lib/engine/game/g_1824/step/buy_train.rb
  lib/engine/game/g_1824/step/dividend.rb
  lib/engine/game/g_1824/step/kk_token_choice.rb
  lib/engine/game/g_1824/trains.rb
  lib/engine/game/g_1824_cisleithania.rb
  lib/engine/game/g_1824_cisleithania/company.rb
  lib/engine/game/g_1824_cisleithania/corporation.rb
  lib/engine/game/g_1824_cisleithania/game.rb
  lib/engine/game/g_1824_cisleithania/map.rb
  lib/engine/game/g_1824_cisleithania/meta.rb
  lib/engine/game/g_1824_cisleithania/round/first_stock.rb
  lib/engine/game/g_1824_cisleithania/share_pool.rb
  lib/engine/game/g_1824_cisleithania/step/bond_token.rb
  lib/engine/game/g_1824_cisleithania/step/buy_sell_par_exchange_shares.rb
  lib/engine/game/g_1824_cisleithania/step/buy_sell_par_shares_first_sr.rb
  lib/engine/game/g_1824_cisleithania/step/buy_train.rb
  lib/engine/game/g_1824_cisleithania/step/dividend.rb
  lib/engine/game/g_1824_cisleithania/step/token.rb
  lib/engine/game/g_1824_cisleithania/step/track.rb
  lib/engine/game/g_1824_cisleithania/trains.rb
Labels: new games, 1824

#11968 [1824] Fix some bugs, and add reference games
  lib/engine/game/g_1824/corporation.rb
  lib/engine/game/g_1824/entities.rb
  lib/engine/game/g_1824/game.rb
  lib/engine/game/g_1824/round/first_stock.rb
  lib/engine/game/g_1824/round/operating.rb
  lib/engine/game/g_1824/step/buy_sell_par_exchange_shares.rb
  lib/engine/game/g_1824/step/buy_sell_par_shares_first_sr.rb
  lib/engine/game/g_1824/step/buy_train.rb
  lib/engine/game/g_1824/step/kk_token_choice.rb
  lib/engine/game/g_1824/step/track.rb
  lib/engine/game/g_1824_cisleithania/game.rb
  lib/engine/game/g_1824_cisleithania/round/first_stock.rb
  lib/engine/game/g_1824_cisleithania/step/buy_sell_par_exchange_shares.rb
  lib/engine/game/g_1824_cisleithania/step/buy_sell_par_shares_first_sr.rb
  lib/engine/game/g_1824_cisleithania/step/buy_train.rb
  public/fixtures/1824 Cisleithania/reference_game_2_players.json
  public/fixtures/1824/receivership_and_emergency_buy.json
  public/fixtures/1824/reference_game_4_players.json
Labels: new games, 1824

#11989 [1824] Fix map errors #11986
  lib/engine/game/g_1824/map.rb
  lib/engine/game/g_1824_cisleithania/map.rb
  public/fixtures/1824/receivership_and_emergency_buy.json
  public/fixtures/1824/reference_game_4_players.json
Labels: 1824, archive_alpha_games

#11990 [1824] Avoid showing multi exchange buttons #11988
  lib/engine/game/g_1824/game.rb
Labels: 1824

#11991 [1824] Fix pending_tokens error #11984
  lib/engine/game/g_1824/game.rb
  lib/engine/game/g_1824/round/operating.rb
  lib/engine/game/g_1824_cisleithania/game.rb
Labels: 1824

#11996 [1824] Disallow upgrade of yellow one town to yellow two town #11993
  lib/engine/game/g_1824/game.rb
Labels: 1824, archive_alpha_games

#12001 [1862] Initial commit to add solo variant to 1862 (EA)
  lib/engine/game/g_1862/meta.rb
  lib/engine/game/g_1862_solo.rb
  lib/engine/game/g_1862_solo/corporation.rb
  lib/engine/game/g_1862_solo/game.rb
  lib/engine/game/g_1862_solo/meta.rb
  lib/engine/game/g_1862_solo/step/buy_sell_par_shares.rb
Labels: new games, 1862

#12011 [1824] Add missing HomeToken step, fixes #12007
  lib/engine/game/g_1824/game.rb
  lib/engine/game/g_1824_cisleithania/game.rb
Labels: 1824

#12034 [System18] Russia and Mississippi fixes
  lib/engine/game/g_system18/game.rb
  lib/engine/game/g_system18/map_ms_customization.rb
  lib/engine/game/g_system18/map_russia_customization.rb
  lib/engine/game/g_system18/step/buy_sell_par_bid_merge.rb
  lib/engine/game/g_system18/step/buy_train.rb
Labels: pins

#11860 [18 India] fix OO SPD / NWR both floated #11699
  lib/engine/game/g_18_india/step/home_track.rb
  public/fixtures/18 India/OO-Fix.json
Labels: archive_alpha_games, 18India

#11977 [1846] don't allow buying company after emergency issuing
  lib/engine/game/g_1846/step/buy_company.rb
  public/fixtures/1846/222264.json
  spec/fixture_cache.rb
  spec/game_state_spec.rb
  spec/lib/engine/game/g_1846/game_spec.rb
  spec/lib/engine/game/g_1846_two_player_variant/game_spec.rb
Labels: pins

#11976 [1822PNW] fix share prices for starting minors in Starting Packet Variant
  lib/engine/game/g_1822_pnw/game.rb
Labels: archive_alpha_games

#12021 [1822] allow acquiring for two shares if major is in yellow
  lib/engine/game/g_1822/step/minor_acquisition.rb
Labels: pins

#12065 [1824] Add deep freeze of trains
  lib/engine/game/g_1824/game.rb
  lib/engine/game/g_1824_cisleithania/game.rb
Labels: 1824, archive_alpha_games

#11983 [1822MX] remove `home_as_token: true` from Graph setup
  lib/engine/game/g_1822/step/minor_acquisition.rb
  lib/engine/game/g_1822_mx/game.rb
  lib/engine/game/g_1822_mx/step/minor_acquisition.rb
  lib/engine/game/g_1822_pnw/step/connections.rb
  lib/engine/step/tracker.rb
  public/fixtures/1822MX/fcm_cannot_lay_thru_mexico_city.json
  spec/lib/engine/game/g_1822_mx/game_spec.rb
  spec/lib/engine/games/g_18_zoo_spec.rb
Labels: pins

#11975 [1822/1822PNW] fix merge for high-value minors, fix floating-point dividends
  lib/engine/game/g_1822/step/dividend.rb
  lib/engine/game/g_1822_pnw/step/conversion.rb
  lib/engine/game/g_1822_pnw/step/merge.rb
  public/fixtures/1822PNW/merger_high_value_minors.json
  spec/game_state_spec.rb
  spec/lib/engine/game/g_1822_pnw/game_spec.rb
Labels: pins
